import { ItemType } from '../interface';

export const emojItems: ItemType[] = [
  {
    name: '笑脸与情感的表情符号',
    children: [
      {
        name: '脸与微笑',
        children: [
          { emoj: '😀', name: '笑脸' },
          { emoj: '😃', name: '笑脸大眼睛' },
          { emoj: '😄', name: '笑脸和微笑的眼睛' },
          { emoj: '😁', name: '脸上带着微笑的眼睛' },
          { emoj: '😆', name: '眯着眼睛笑的脸' },
          { emoj: '😅', name: '满脸汗水的笑脸' },
          { emoj: '🤣', name: '笑得在地上打滚' },
          { emoj: '😂', name: '满脸喜悦的泪水' },
          { emoj: '🙂', name: '微微微笑的脸' },
          { emoj: '🙃', name: '颠倒的脸' },
          { emoj: '🫠', name: '融化的脸' },
          { emoj: '😉', name: '眨眼的脸' },
          { emoj: '😊', name: '微笑的脸和微笑的眼睛' },
          { emoj: '😇', name: '带光环的笑脸' },
        ]
      },
      {
        name: '脸与情感',
        children: [
          { emoj: '🥰', name: '笑脸与心' },
          { emoj: '😍', name: '心形眼睛的笑脸' },
          { emoj: '🤩', name: '追星的' },
          { emoj: '😘', name: '脸飞吻' },
          { emoj: '😗', name: '亲吻脸' },
          { emoj: '☺️', name: '微笑的面孔' },
          { emoj: '☺', name: '微笑的面孔' },
          { emoj: '😚', name: '闭着眼睛亲吻脸' },
          { emoj: '😙', name: '带着微笑的眼睛亲吻脸' },
          { emoj: '🥲', name: '含着泪水的笑脸' },
        ]
      },
      {
        name: '脸与舌头',
        children: [
          { emoj: '😋', name: '品尝食物的脸' },
          { emoj: '😛', name: '用舌头面对' },
          { emoj: '😜', name: '用舌头眨眼的脸' },
          { emoj: '🤪', name: '滑稽的脸' },
          { emoj: '😝', name: '用舌头眯着脸' },
          { emoj: '🤑', name: '钱嘴脸' },
        ]
      },
      {
        name: '脸与手势',
        children: [
          { emoj: '🤗', name: '张开双手微笑的脸' },
          { emoj: '🤭', name: '用手捂住嘴脸' },
          { emoj: '🫢', name: '睁开眼睛并用手捂住嘴' },
          { emoj: '🫣', name: '脸上有偷看的眼睛' },
          { emoj: '🤫', name: '嘘脸' },
          { emoj: '🤔', name: '思考的脸' },
          { emoj: '🫡', name: '敬礼的脸' },
        ]
      },
      {
        name: '脸与中性与怀疑',
        children: [
          { emoj: '🤐', name: '拉链嘴脸' },
          { emoj: '🤨', name: '扬眉的脸' },
          { emoj: '😐', name: '中性面孔' },
          { emoj: '😑', name: '面无表情' },
          { emoj: '😶', name: '没有嘴的脸' },
          { emoj: '🫥', name: '虚线面' },
          { emoj: '😶‍🌫️', name: '云中的脸' },
          { emoj: '😏', name: '傻笑的脸' },
          { emoj: '😒', name: '不高兴的脸' },
          { emoj: '🙄', name: '翻白眼的脸' },
          { emoj: '😬', name: '鬼脸' },
          { emoj: '😮‍💨', name: '面部呼气' },
          { emoj: '🤥', name: '说谎的脸' },
          { emoj: '🫨', name: '摇脸' },
        ]
      },
      {
        name: '脸与困倦',
        children: [
          { emoj: '😌', name: '释然的脸' },
          { emoj: '😔', name: '沉思的脸' },
          { emoj: '😪', name: '困倦的脸' },
          { emoj: '🤤', name: '流口水的脸' },
          { emoj: '😴', name: '睡脸' },
        ]
      },
      {
        name: '脸与不适',
        children: [
          { emoj: '😷', name: '带着医用口罩的脸' },
          { emoj: '🤒', name: '带温度计的脸' },
          { emoj: '🤕', name: '头上缠着绷带的脸' },
          { emoj: '🤢', name: '恶心的脸' },
          { emoj: '🤮', name: '脸部呕吐' },
          { emoj: '🤧', name: '打喷嚏的脸' },
          { emoj: '🥵', name: '脸热' },
          { emoj: '🥶', name: '冷脸' },
          { emoj: '🥴', name: '昏昏沉沉的脸' },
          { emoj: '😵', name: '交叉眼睛的脸' },
          { emoj: '😵‍💫', name: '螺旋形眼睛的脸' },
          { emoj: '🤯', name: '爆炸头' },
        ]
      },
      {
        name: '脸与帽子',
        children: [
          { emoj: '🤠', name: '牛仔帽脸' },
          { emoj: '🥳', name: '派对脸' },
          { emoj: '🥸', name: '伪装的脸' },

        ]
      },
      {
        name: '脸与眼镜',
        children: [
          { emoj: '😎', name: '戴着墨镜的笑脸' },
          { emoj: '🤓', name: '书呆子脸' },
          { emoj: '🧐', name: '带单片眼镜的脸' },
        ]
      },
      {
        name: '脸与担忧',
        children: [
          { emoj: '😕', name: '困惑的脸' },
          { emoj: '🫤', name: '斜嘴脸' },
          { emoj: '😟', name: '担心的脸' },
          { emoj: '🙁', name: '微微皱眉的脸' },
          { emoj: '☹️', name: '皱眉的脸' },
          { emoj: '☹', name: '皱眉的脸' },
          { emoj: '😮', name: '张开嘴的脸' },
          { emoj: '😯', name: '安静的脸' },
          { emoj: '😲', name: '惊讶的脸' },
          { emoj: '😳', name: '脸红了' },
          { emoj: '🥺', name: '恳求的脸' },
          { emoj: '🥹', name: '强忍着泪水的脸' },
          { emoj: '😦', name: '张开嘴皱着眉头' },
          { emoj: '😧', name: '痛苦的脸' },
          { emoj: '😨', name: '恐惧的脸' },
          { emoj: '😰', name: '满脸焦急满头大汗' },
          { emoj: '😥', name: '悲伤但如释重负的脸' },
          { emoj: '😢', name: '哭泣的脸' },
          { emoj: '😭', name: '大声哭泣的脸' },
          { emoj: '😱', name: '脸上因恐惧而尖叫' },
          { emoj: '😖', name: '困惑的脸' },
          { emoj: '😣', name: '坚忍的脸' },
          { emoj: '😞', name: '失望的脸' },
          { emoj: '😓', name: '满脸汗水低垂的脸' },
          { emoj: '😩', name: '疲倦的脸' },
          { emoj: '😫', name: '疲惫的脸' },
          { emoj: '🥱', name: '打呵欠的脸' },
        ]
      },
      {
        name: '脸与消极',
        children: [
          { emoj: '😤', name: '鼻子里冒着蒸汽的脸' },
          { emoj: '😡', name: '愤怒的脸' },
          { emoj: '😠', name: '愤怒的脸' },
          { emoj: '🤬', name: '嘴上有符号的脸' },
          { emoj: '😈', name: '带角的笑脸' },
          { emoj: '👿', name: '有角的愤怒的脸' },
          { emoj: '💀', name: '颅骨' },
          { emoj: '☠️', name: '骷髅和交叉骨' },
          { emoj: '☠', name: '骷髅和交叉骨' },
        ]
      },
      {
        name: '脸与服装',
        children: [
          { emoj: '💩', name: '一堆便便' },
          { emoj: '🤡', name: '小丑脸' },
          { emoj: '👹', name: '食人魔' },
          { emoj: '👺', name: '妖精' },
          { emoj: '👻', name: '鬼' },
          { emoj: '👽', name: '外星人' },
          { emoj: '👾', name: '外星怪物' },
          { emoj: '🤖', name: '机器人' },
        ]
      },
      {
        name: '猫与脸',
        children: [
          { emoj: '😺', name: '咧着嘴笑的猫' },
          { emoj: '😸', name: '微笑的猫，带着微笑的眼睛' },
          { emoj: '😹', name: '猫流着喜悦的泪水' },
          { emoj: '😻', name: '心形眼睛微笑的猫' },
          { emoj: '😼', name: '苦笑的猫' },
          { emoj: '😽', name: '接吻猫' },
          { emoj: '🙀', name: '疲倦的猫' },
          { emoj: '😿', name: '哭泣的猫' },
          { emoj: '😾', name: '撅嘴的猫' },
        ]
      },
      {
        name: '猴与脸',
        children: [
          { emoj: '🙈', name: '无恶不作的猴子' },
          { emoj: '🙉', name: '不闻不问的猴子' },
          { emoj: '🙊', name: '不说邪恶的猴子' },
        ]
      },
      {
        name: '心形',
        children: [
          { emoj: '💌', name: '爱情信' },
          { emoj: '💘', name: '带箭头的心' },
          { emoj: '💝', name: '带丝带的心' },
          { emoj: '💖', name: '闪闪发光的心' },
          { emoj: '💗', name: '成长的心' },
          { emoj: '💓', name: '跳动的心' },
          { emoj: '💞', name: '旋转的心' },
          { emoj: '💕', name: '两颗心' },
          { emoj: '💟', name: '心形装饰' },
          { emoj: '❣️', name: '心中感叹' },
          { emoj: '❣', name: '心中感叹' },
          { emoj: '💔', name: '破碎的心' },
          { emoj: '❤️‍🔥', name: '心脏着火' },
          { emoj: '❤️‍🩹', name: '修补心' },
          { emoj: '❤️', name: '红心' },
          { emoj: '❤', name: '红心' },
          { emoj: '🩷', name: '粉红色的心' },
          { emoj: '🧡', name: '橙色的心' },
          { emoj: '💛', name: '黄心' },
          { emoj: '💚', name: '绿心' },
          { emoj: '💙', name: '蓝色的心' },
          { emoj: '🩵', name: '淡蓝色的心' },
          { emoj: '💜', name: '紫心的心' },
          { emoj: '🤎', name: '棕色的心' },
          { emoj: '🖤', name: '黑心' },
          { emoj: '🩶', name: '灰色的心' },
          { emoj: '🤍', name: '白心' },
        ]
      },
      {
        name: '情感',
        children: [
          { emoj: '💋', name: '吻痕' },
          { emoj: '💯', name: '百分' },
          { emoj: '💢', name: '愤怒的象征' },
          { emoj: '💥', name: '碰撞' },
          { emoj: '💦', name: '汗滴' },
          { emoj: '💨', name: '匆匆而去' },
          { emoj: '🕳️', name: '洞' },
          { emoj: '💬', name: '语音气球' },
          { emoj: '👁️‍🗨️', name: '讲话泡泡中的眼睛' },
          { emoj: '🗨️', name: '左边的语音气泡' },
          { emoj: '🗯️', name: '右愤怒泡沫' },
          { emoj: '💭', name: '思想气球' },
          { emoj: '💤', name: 'ZZZ' },
        ]
      }
    ]
  },
  {
    name: '人物与身体的表情符号',
    children: [
      {
        name: '手与手指展开',
        children: [
          { emoj: '👋', name: '挥手' },
          { emoj: '👋🏻', name: '挥手 浅肤色' },
          { emoj: '👋🏼', name: '挥手 中浅肤色' },
          { emoj: '👋🏽', name: '挥手 中等肤色' },
          { emoj: '👋🏾', name: '挥手 中黑肤色' },
          { emoj: '👋🏿', name: '挥手 深色肤色' },
          { emoj: '🤚', name: '举起手背' },
          { emoj: '🤚🏻', name: '举起手背 浅肤色' },
          { emoj: '🤚🏼', name: '举起手背 中浅肤色' },
          { emoj: '🤚🏽', name: '举起手背 中等肤色' },
          { emoj: '🤚🏾', name: '举起手背 中黑肤色' },
          { emoj: '🤚🏿', name: '举起手背 深色肤色' },
          { emoj: '🖐', name: '手指张开的手' },
          { emoj: '🖐🏻', name: '手指张开的手 浅肤色' },
          { emoj: '🖐🏼', name: '手指张开的手 中浅肤色' },
          { emoj: '🖐🏽', name: '手指张开的手 中等肤色' },
          { emoj: '🖐🏾', name: '手指张开的手 中黑肤色' },
          { emoj: '🖐🏿', name: '手指张开的手 深色肤色' },
          { emoj: '✋', name: '举起手' },
          { emoj: '✋🏻', name: '举起手 浅肤色' },
          { emoj: '✋🏼', name: '举起手 中浅肤色' },
          { emoj: '✋🏽', name: '举起手 中等肤色' },
          { emoj: '✋🏾', name: '举起手 中黑肤色' },
          { emoj: '✋🏿', name: '举起手 深色肤色' },
          { emoj: '🖖', name: '瓦肯敬礼' },
          { emoj: '🖖🏻', name: '瓦肯敬礼 浅肤色' },
          { emoj: '🖖🏼', name: '瓦肯敬礼 中浅肤色' },
          { emoj: '🖖🏽', name: '瓦肯敬礼 中等肤色' },
          { emoj: '🖖🏾', name: '瓦肯敬礼 中黑肤色' },
          { emoj: '🖖🏿', name: '瓦肯敬礼 深色肤色' },
          { emoj: '🫱', name: '右手' },
          { emoj: '🫱🏻', name: '右手 浅肤色' },
          { emoj: '🫱🏼', name: '右手 中浅肤色' },
          { emoj: '🫱🏽', name: '右手 中等肤色' },
          { emoj: '🫱🏾', name: '右手 中黑肤色' },
          { emoj: '🫱🏿', name: '右手 深色肤色' },
          { emoj: '🫲', name: '左手' },
          { emoj: '🫲🏻', name: '左手 浅肤色' },
          { emoj: '🫲🏼', name: '左手 中浅肤色' },
          { emoj: '🫲🏽', name: '左手 中等肤色' },
          { emoj: '🫲🏾', name: '左手 中黑肤色' },
          { emoj: '🫲🏿', name: '左手 深色肤色' },
          { emoj: '🫳', name: '双手' },
          { emoj: '🫳🏻', name: '双手 浅肤色' },
          { emoj: '🫳🏼', name: '双手 中浅肤色' },
          { emoj: '🫳🏽', name: '双手 中等肤色' },
          { emoj: '🫳🏾', name: '双手 中黑肤色' },
          { emoj: '🫳🏿', name: '双手 深色肤色' },
        ]
      },
      {
        name: '手与部分手指',
        children: [
          { emoj: '👌', name: '好的手' },
          { emoj: '👌🏻', name: '好的手 浅肤色' },
          { emoj: '👌🏼', name: '好的手 中浅肤色' },
          { emoj: '👌🏽', name: '好的手 中等肤色' },
          { emoj: '👌🏾', name: '好的手 中黑肤色' },
          { emoj: '👌🏿', name: '好的手 深色肤色' },
          { emoj: '🤌', name: '捏手指' },
          { emoj: '🤌🏻', name: '捏手指 浅肤色' },
          { emoj: '🤌🏼', name: '捏手指 中浅肤色' },
          { emoj: '🤌🏽', name: '捏手指 中等肤色' },
          { emoj: '🤌🏾', name: '捏手指 中黑肤色' },
          { emoj: '🤌🏿', name: '捏手指 深色肤色' },
          { emoj: '🤏', name: '捏手' },
          { emoj: '🤏🏻', name: '捏手 浅肤色' },
          { emoj: '🤏🏼', name: '捏手 中浅肤色' },
          { emoj: '🤏🏽', name: '捏手 中等肤色' },
          { emoj: '🤏🏾', name: '捏手 中黑肤色' },
          { emoj: '🤏🏿', name: '捏手 深色肤色' },
          { emoj: '✌️', name: '胜利之手' },
          { emoj: '✌', name: '胜利之手' },
          { emoj: '✌🏻', name: '胜利之手 浅肤色' },
          { emoj: '✌🏼', name: '胜利之手 中浅肤色' },
          { emoj: '✌🏽', name: '胜利之手 中等肤色' },
          { emoj: '✌🏾', name: '胜利之手 中黑肤色' },
          { emoj: '✌🏿', name: '胜利之手 深色肤色' },
          { emoj: '🤞', name: '交叉手指' },
          { emoj: '🤞🏻', name: '交叉手指 浅肤色' },
          { emoj: '🤞🏼', name: '交叉手指 中浅肤色' },
          { emoj: '🤞🏽', name: '交叉手指 中等肤色' },
          { emoj: '🤞🏾', name: '交叉手指 中黑肤色' },
          { emoj: '🤞🏿', name: '交叉手指 深色肤色' },
          { emoj: '🫰', name: '食指和拇指交叉的手' },
        ]
      },
      {
        name: '手与单个手指',
        children: [
          { emoj: '👈', name: '反手食指指向左侧' },
          { emoj: '👈🏻', name: '反手食指指向左侧 浅肤色' },
          { emoj: '👈🏼', name: '反手食指指向左侧 中浅肤色' },
          { emoj: '👈🏽', name: '反手食指指向左侧 中等肤色' },
          { emoj: '👈🏾', name: '反手食指指向左侧 中黑肤色' },
          { emoj: '👈🏿', name: '反手食指指向左侧 深色肤色' },
          { emoj: '👉', name: '反手食指指向右侧' },
          { emoj: '👉🏻', name: '反手食指指向右侧 浅肤色' },
          { emoj: '👉🏼', name: '反手食指指向右侧 中浅肤色' },
          { emoj: '👉🏽', name: '反手食指指向右侧 中等肤色' },
          { emoj: '👉🏾', name: '反手食指指向右侧 中黑肤色' },
          { emoj: '👉🏿', name: '反手食指指向右侧 深色肤色' },
          { emoj: '👆', name: '反手指数向上' },
          { emoj: '👆🏻', name: '反手指数向上 浅肤色' },
          { emoj: '👆🏼', name: '反手指数向上 中浅肤色' },
          { emoj: '👆🏽', name: '反手指数向上 中等肤色' },
          { emoj: '👆🏾', name: '反手指数向上 中黑肤色' },
          { emoj: '👆🏿', name: '反手指数向上 深色肤色' },
          { emoj: '🖕', name: '中指' },
          { emoj: '🖕🏻', name: '中指 浅肤色' },
          { emoj: '🖕🏼', name: '中指 中浅肤色' },
          { emoj: '🖕🏽', name: '中指 中等肤色' },
          { emoj: '🖕🏾', name: '中指 中黑肤色' },
          { emoj: '🖕🏿', name: '中指 深色肤色' },
          { emoj: '👇', name: '反手指数朝下' },
          { emoj: '👇🏻', name: '反手指数朝下 浅肤色' },
          { emoj: '👇🏼', name: '反手指数朝下 中浅肤色' },
          { emoj: '👇🏽', name: '反手指数朝下 中等肤色' },
          { emoj: '👇🏾', name: '反手指数朝下 中黑肤色' },
          { emoj: '👇🏿', name: '反手指数朝下 深色肤色' },
          { emoj: '☝️', name: '索引向上' },
          { emoj: '🫴', name: '拇指' },
          { emoj: '🫴🏻', name: '拇指 浅肤色' },
          { emoj: '🫴🏼', name: '拇指 中浅肤色' },
          { emoj: '🫴🏽', name: '拇指 中等肤色' },
          { emoj: '🫴🏾', name: '拇指 中黑肤色' },
          { emoj: '🫴🏿', name: '拇指 深色肤色' }

        ]
      },
      {
        name: '手与手指合拢',
        children: [
          { emoj: '👍', name: '竖起大拇指' },
          { emoj: '👍🏻', name: '竖起大拇指 浅肤色' },
          { emoj: '👍🏼', name: '竖起大拇指 中浅肤色' },
          { emoj: '👍🏽', name: '竖起大拇指 中等肤色' },
          { emoj: '👍🏾', name: '竖起大拇指 中黑肤色' },
          { emoj: '👍🏿', name: '竖起大拇指 深色肤色' },
          { emoj: '👎', name: '不看好' },
          { emoj: '👎🏻', name: '不看好 浅肤色' },
          { emoj: '👎🏼', name: '不看好 中浅肤色' },
          { emoj: '👎🏽', name: '不看好 中等肤色' },
          { emoj: '👎🏾', name: '不看好 中黑肤色' },
          { emoj: '👎🏿', name: '不看好 深色肤色' },
          { emoj: '✊', name: '拳头' },
          { emoj: '✊🏻', name: '拳头 浅肤色' },
          { emoj: '✊🏼', name: '拳头 中浅肤色' },
          { emoj: '✊🏽', name: '拳头 中等肤色' },
          { emoj: '✊🏾', name: '拳头 中黑肤色' },
          { emoj: '✊🏿', name: '拳头 深色肤色' },
          { emoj: '👊', name: '迎面而来的拳头' },
          { emoj: '👊🏻', name: '迎面而来的拳头 浅肤色' },
          { emoj: '👊🏼', name: '迎面而来的拳头 中浅肤色' },
          { emoj: '👊🏽', name: '迎面而来的拳头 中等肤色' },
          { emoj: '👊🏾', name: '迎面而来的拳头 中黑肤色' },
          { emoj: '👊🏿', name: '迎面而来的拳头 深色肤色' },
          { emoj: '🤛', name: '向左握拳' },
          { emoj: '🤛🏻', name: '向左握拳 浅肤色' },
          { emoj: '🤛🏼', name: '向左握拳 中浅肤色' },
          { emoj: '🤛🏽', name: '向左握拳 中等肤色' },
          { emoj: '🤛🏾', name: '向左握拳 中黑肤色' },
          { emoj: '🤛🏿', name: '向左握拳 深色肤色' },
          { emoj: '🤜', name: '向右握拳' },
          { emoj: '🤜🏻', name: '向右握拳 浅肤色' },
          { emoj: '🤜🏼', name: '向右握拳 中浅肤色' },
          { emoj: '🤜🏽', name: '向右握拳 中等肤色' },
          { emoj: '🤜🏾', name: '向右握拳 中黑肤色' },
          { emoj: '🤜🏿', name: '向右握拳 深色肤色' }
        ]
      },
      {
        name: '双手',
        children: [
          { emoj: '👏', name: '拍手' },
          { emoj: '👏🏻', name: '拍手 浅肤色' },
          { emoj: '👏🏼', name: '拍手 中浅肤色' },
          { emoj: '👏🏽', name: '拍手 中等肤色' },
          { emoj: '👏🏾', name: '拍手 中黑肤色' },
          { emoj: '👏🏿', name: '拍手 深色肤色' },
          { emoj: '🙌', name: '举手' },
          { emoj: '🙌🏻', name: '举手 浅肤色' },
          { emoj: '🙌🏼', name: '举手 中浅肤色' },
          { emoj: '🙌🏽', name: '举手 中等肤色' },
          { emoj: '🙌🏾', name: '举手 中黑肤色' },
          { emoj: '🙌🏿', name: '举手 深色肤色' },
          { emoj: '🫶', name: '心形手' },
          { emoj: '🫶🏻', name: '心形手 浅肤色' },
          { emoj: '🫶🏼', name: '心形手 中浅肤色' },
          { emoj: '🫶🏽', name: '心形手 中等肤色' },
          { emoj: '🫶🏾', name: '心形手 中黑肤色' },
          { emoj: '🫶🏿', name: '心形手 深色肤色' },
          { emoj: '👐', name: '张开双手' },
          { emoj: '👐🏻', name: '张开双手 浅肤色' },
          { emoj: '👐🏼', name: '张开双手 中浅肤色' },
          { emoj: '👐🏽', name: '张开双手 中等肤色' },
          { emoj: '👐🏾', name: '张开双手 中黑肤色' },
          { emoj: '👐🏿', name: '张开双手 深色肤色' },
          { emoj: '🤲', name: '手掌向上并拢' },
          { emoj: '🤲🏻', name: '手掌向上并拢 浅肤色' },
          { emoj: '🤲🏼', name: '手掌向上并拢 中浅肤色' },
          { emoj: '🤲🏽', name: '手掌向上并拢 中等肤色' },
          { emoj: '🤲🏾', name: '手掌向上并拢 中黑肤色' },
          { emoj: '🤲🏿', name: '手掌向上并拢 深色肤色' },
          { emoj: '🤝', name: '握手' },
          { emoj: '🤝🏻', name: '握手 浅肤色' },
          { emoj: '🤝🏼', name: '握手 中浅肤色' },
          { emoj: '🤝🏽', name: '握手 中等肤色' },
          { emoj: '🤝🏾', name: '握手 中黑肤色' },
          { emoj: '🤝🏿', name: '握手 深色肤色' },
        ]
      },
      {
        name: '手与道具',
        children: [
          { emoj: '✍️', name: '写字的手' },
          { emoj: '✍🏻', name: '写字的手 浅肤色' },
          { emoj: '✍🏼', name: '写字的手 中浅肤色' },
          { emoj: '✍🏽', name: '写字的手 中等肤色' },
          { emoj: '✍🏾', name: '写字的手 中黑肤色' },
          { emoj: '✍🏿', name: '写字的手 深色肤色' },
          { emoj: '💅', name: '指甲油' },
          { emoj: '💅🏻', name: '指甲油 浅肤色' },
          { emoj: '💅🏼', name: '指甲油 中浅肤色' },
          { emoj: '💅🏽', name: '指甲油 中等肤色' },
          { emoj: '💅🏾', name: '指甲油 中黑肤色' },
          { emoj: '💅🏿', name: '指甲油 深色肤色' },
          { emoj: '🤳', name: '自拍' },
          { emoj: '🤳🏻', name: '自拍 浅肤色' },
          { emoj: '🤳🏼', name: '自拍 中浅肤色' },
          { emoj: '🤳🏽', name: '自拍 中等肤色' },
          { emoj: '🤳🏾', name: '自拍 中黑肤色' },
          { emoj: '🤳🏿', name: '自拍 深色肤色' },
        ]
      },
      {
        name: '身体与部位',
        children: [
          { emoj: '💪', name: '弯曲的二头肌' },
          { emoj: '💪🏻', name: '弯曲的二头肌 浅肤色' },
          { emoj: '💪🏼', name: '弯曲的二头肌 中浅肤色' },
          { emoj: '💪🏽', name: '弯曲的二头肌 中等肤色' },
          { emoj: '💪🏾', name: '弯曲的二头肌 中黑肤色' },
          { emoj: '💪🏿', name: '弯曲的二头肌 深色肤色' },
          { emoj: '🦾', name: '机械臂' },
          { emoj: '🦿', name: '机械腿' },
          { emoj: '🦵', name: '腿' },
          { emoj: '🦵🏻', name: '腿 浅肤色' },
          { emoj: '🦵🏼', name: '腿 中浅肤色' },
          { emoj: '🦵🏽', name: '腿 中等肤色' },
          { emoj: '🦵🏾', name: '腿 中黑肤色' },
          { emoj: '🦵🏿', name: '腿 深色肤色' },
          { emoj: '🦶', name: '脚' },
          { emoj: '🦶🏻', name: '脚 浅肤色' },
          { emoj: '🦶🏼', name: '脚 中浅肤色' },
          { emoj: '🦶🏽', name: '脚 中等肤色' },
          { emoj: '🦶🏾', name: '脚 中黑肤色' },
          { emoj: '🦶🏿', name: '脚 深色肤色' },
          { emoj: '👂', name: '耳朵' },
          { emoj: '👂🏻', name: '耳朵 浅肤色' },
          { emoj: '👂🏼', name: '耳朵 中浅肤色' },
          { emoj: '👂🏽', name: '耳朵 中等肤色' },
          { emoj: '👂🏾', name: '耳朵 中黑肤色' },
          { emoj: '👂🏿', name: '耳朵 深色肤色' },
          { emoj: '🦻', name: '带助听器的耳朵' },
          { emoj: '🦻🏻', name: '带助听器的耳朵 浅肤色' },
          { emoj: '🦻🏼', name: '带助听器的耳朵 中浅肤色' },
          { emoj: '🦻🏽', name: '带助听器的耳朵 中等肤色' },
          { emoj: '🦻🏾', name: '带助听器的耳朵 中黑肤色' },
          { emoj: '🦻🏿', name: '带助听器的耳朵 深色肤色' },
        ]
      },
      {
        name: '人物',
        children: [
          { emoj: '👶', name: '婴儿' },
          { emoj: '👶🏻', name: '婴儿 浅肤色' },
          { emoj: '👶🏼', name: '婴儿 中浅肤色' },
          { emoj: '👶🏽', name: '婴儿 中等肤色' },
          { emoj: '👶🏾', name: '婴儿 中黑肤色' },
          { emoj: '👶🏿', name: '婴儿 深色肤色' },
          { emoj: '🧒', name: '孩子' },
          { emoj: '🧒🏻', name: '孩子 浅肤色' },
          { emoj: '🧒🏼', name: '孩子 中浅肤色' },
          { emoj: '🧒🏽', name: '孩子 中等肤色' },
          { emoj: '🧒🏾', name: '孩子 中黑肤色' },
          { emoj: '🧒🏿', name: '孩子 深色肤色' },
          { emoj: '👦', name: '男生' },
          { emoj: '👦🏻', name: '男生 浅肤色' },
          { emoj: '👦🏼', name: '男生 中浅肤色' },
          { emoj: '👦🏽', name: '男生 中等肤色' },
          { emoj: '👦🏾', name: '男生 中黑肤色' },
          { emoj: '👦🏿', name: '男生 深色肤色' },
          { emoj: '👧', name: '女生' },
          { emoj: '👧🏻', name: '女生 浅肤色' },
          { emoj: '👧🏼', name: '女生 中浅肤色' },
          { emoj: '👧🏽', name: '女生 中等肤色' },
          { emoj: '👧🏾', name: '女生 中黑肤色' },
          { emoj: '👧🏿', name: '女生 深色肤色' },
          { emoj: '🧑', name: '人' },
          { emoj: '🧑🏻', name: '人 浅肤色' },
          { emoj: '🧑🏼', name: '人 中浅肤色' },
          { emoj: '🧑🏽', name: '人 中等肤色' },
          { emoj: '🧑🏾', name: '人 中黑肤色' },
          { emoj: '🧑🏿', name: '人 深色肤色' },
          { emoj: '👱', name: '男人' },
          { emoj: '👱🏻', name: '男人 浅肤色' },
          { emoj: '👱🏼', name: '男人 中浅肤色' },
          { emoj: '👱🏽', name: '男人 中等肤色' },
          { emoj: '👱🏾', name: '男人 中黑肤色' },
          { emoj: '👱🏿', name: '男人 深色肤色' },
          { emoj: '👱', name: 'blond hair' },
          { emoj: '👱🏻', name: 'blond hair 浅肤色' },
          { emoj: '👱🏼', name: 'blond hair 中浅肤色' },
          { emoj: '👱🏽', name: 'blond hair 中等肤色' },
          { emoj: '👱🏾', name: 'blond hair 中黑肤色' },
          { emoj: '👱🏿', name: 'blond hair 深色肤色' },
        ]
      },
      {
        name: '人物与手势',
        children: [
          { "emoj": "🙍", "name": "皱眉的人" },
          { "emoj": "🙍🏻", "name": "皱眉的人 浅肤色" },
          { "emoj": "🙍🏼", "name": "皱眉的人 中浅肤色" },
          { "emoj": "🙍🏽", "name": "皱眉的人 中等肤色" },
          { "emoj": "🙍🏾", "name": "皱眉的人 中黑肤色" },
          { "emoj": "🙍🏿", "name": "皱眉的人 深色肤色" },
          { "emoj": "🙍‍♂", "name": "男人皱眉" },
          { "emoj": "🙍🏻‍♂️", "name": "男人皱眉 浅肤色" },
          { "emoj": "🙍🏼‍♂", "name": "男人皱眉 中浅肤色" },
          { "emoj": "🙍🏽‍♂", "name": "男人皱眉 中等肤色" },
          { "emoj": "🙍🏾‍♂️", "name": "男人皱眉 中黑肤色" },
          { "emoj": "🙍🏿‍♂", "name": "男人皱眉 深色肤色" },
          { "emoj": "🙍‍♀️", "name": "女人皱眉" },
          { "emoj": "🙍🏻‍♀️", "name": "女人皱眉 浅肤色" },
          { "emoj": "🙍🏼‍♀️", "name": "女人皱眉 中浅肤色" },
          { "emoj": "🙍🏼‍♀", "name": "女人皱眉 中浅肤色" },
          { "emoj": "🙍🏽‍♀", "name": "女人皱眉 中等肤色" },
          { "emoj": "🙍🏾‍♀️", "name": "女人皱眉 中黑肤色" },
          { "emoj": "🙍🏿‍♀", "name": "女人皱眉 深色肤色" },
          { "emoj": "🙎", "name": "撅嘴的人" },
          { "emoj": "🙎🏻", "name": "撅嘴的人 浅肤色" },
          { "emoj": "🙎🏼", "name": "撅嘴的人 中浅肤色" },
          { "emoj": "🙎🏽", "name": "撅嘴的人 中等肤色" },
          { "emoj": "🙎🏾", "name": "撅嘴的人 中黑肤色" },
          { "emoj": "🙎🏿", "name": "撅嘴的人 深色肤色" },
          { "emoj": "🙎‍♂️", "name": "男人撅嘴" },
          { "emoj": "🙎🏻‍♂", "name": "男人撅嘴 浅肤色" },
          { "emoj": "🙎🏼‍♂️", "name": "男人撅嘴 中浅肤色" },
          { "emoj": "🙎🏽‍♂", "name": "男人撅嘴 中等肤色" },
          { "emoj": "🙎🏾‍♂️", "name": "男人撅嘴 中黑肤色" },
          { "emoj": "🙎🏿‍♂", "name": "男人撅嘴 深色肤色" },
          { "emoj": "🙎‍♀️", "name": "女人撅嘴" },
          { "emoj": "🙎🏻‍♀", "name": "女人撅嘴 浅肤色" },
          { "emoj": "🙎🏼‍♀️", "name": "女人撅嘴 中浅肤色" },
          { "emoj": "🙎🏼‍♀", "name": "女人撅嘴 中浅肤色" },
          { "emoj": "🙎🏽‍♀️", "name": "女人撅嘴 中等肤色" },
          { "emoj": "🙎🏾‍♀", "name": "女人撅嘴 中黑肤色" },
          { "emoj": "🙎🏿‍♀️", "name": "女人撅嘴 深色肤色" },
          { "emoj": "🙅", "name": "打手势“不”的人" },
          { "emoj": "🙅🏻", "name": "打手势“不”的人 浅肤色" },
          { "emoj": "🙅🏼", "name": "打手势“不”的人 中浅肤色" },
          { "emoj": "🙅🏽", "name": "打手势“不”的人 中等肤色" },
          { "emoj": "🙅🏾", "name": "打手势“不”的人 中黑肤色" },
          { "emoj": "🙅🏿", "name": "打手势“不”的人 深色肤色" },
          { "emoj": "🙅‍♂", "name": "男人打手势“不”" },
          { "emoj": "🙅🏻‍♂", "name": "男人打手势“不” 浅肤色" },
          { "emoj": "🙅🏼‍♂", "name": "男人打手势“不” 中浅肤色" },
          { "emoj": "🙅🏽‍♂", "name": "男人打手势“不” 中等肤色" },
          { "emoj": "🙅🏾‍♂️", "name": "男人打手势“不” 中黑肤色" },
          { "emoj": "🙅🏿‍♂", "name": "男人打手势“不” 深色肤色" },
          { "emoj": "🙅‍♀", "name": "女人打手势“不”" },
          { "emoj": "🙅🏻‍♀", "name": "女人打手势“不” 浅肤色" },
          { "emoj": "🙅🏼‍♀️", "name": "女人打手势“不” 中浅肤色" },
          { "emoj": "🙅🏽‍♀️", "name": "女人打手势“不” 中等肤色" },
          { "emoj": "🙅🏾‍♀", "name": "女人打手势“不” 中黑肤色" },
          { "emoj": "🙅🏿‍♀️", "name": "女人打手势“不” 深色肤色" }
        ]
      },
      {
        name: '人物与幻想',
        children: [
          { "emoj": "👼", "name": "宝贝天使" },
          { "emoj": "👼🏻", "name": "宝贝天使 浅肤色" },
          { "emoj": "👼🏼", "name": "宝贝天使 中浅肤色" },
          { "emoj": "👼🏽", "name": "宝贝天使 中等肤色" },
          { "emoj": "👼🏾", "name": "宝贝天使 中黑肤色" },
          { "emoj": "👼🏿", "name": "宝贝天使 深色肤色" },
          { "emoj": "🎅", "name": "圣诞老人" },
          { "emoj": "🎅🏻", "name": "圣诞老人 浅肤色" },
          { "emoj": "🎅🏼", "name": "圣诞老人 中浅肤色" },
          { "emoj": "🎅🏽", "name": "圣诞老人 中等肤色" },
          { "emoj": "🎅🏾", "name": "圣诞老人 中黑肤色" },
          { "emoj": "🎅🏿", "name": "圣诞老人 深色肤色" },
          { "emoj": "🤶", "name": "克劳斯夫人" },
          { "emoj": "🤶🏻", "name": "克劳斯夫人 浅肤色" },
          { "emoj": "🤶🏼", "name": "克劳斯夫人 中浅肤色" },
          { "emoj": "🤶🏽", "name": "克劳斯夫人 中等肤色" },
          { "emoj": "🤶🏾", "name": "克劳斯夫人 中黑肤色" },
          { "emoj": "🤶🏿", "name": "克劳斯夫人 深色肤色" },
          { "emoj": "🧑‍🎄", "name": "MX 克劳斯" },
          { "emoj": "🧑🏻‍🎄", "name": "MX 克劳斯 浅肤色" },
          { "emoj": "🧑🏼‍🎄", "name": "MX 克劳斯 中浅肤色" },
          { "emoj": "🧑🏽‍🎄", "name": "MX 克劳斯 中等肤色" },
          { "emoj": "🧑🏾‍🎄", "name": "MX 克劳斯 中黑肤色" },
          { "emoj": "🧑🏿‍🎄", "name": "MX 克劳斯 深色肤色" },
          { "emoj": "🦸", "name": "超级英雄" },
          { "emoj": "🦸🏻", "name": "超级英雄 浅肤色" },
          { "emoj": "🦸🏼", "name": "超级英雄 中浅肤色" },
          { "emoj": "🦸🏽", "name": "超级英雄 中等肤色" },
          { "emoj": "🦸🏾", "name": "超级英雄 中黑肤色" },
          { "emoj": "🦸🏿", "name": "超级英雄 深色肤色" },
          { "emoj": "🦸‍♂", "name": "男人超级英雄" }
        ]
      },
      {
        name: '人物与活动',
        children: [
          { "emoj": "💆", "name": "接受按摩的人" },
          { "emoj": "💆🏻", "name": "接受按摩的人 浅肤色" },
          { "emoj": "💆🏼", "name": "接受按摩的人 中浅肤色" },
          { "emoj": "💆🏽", "name": "接受按摩的人 中等肤色" },
          { "emoj": "💆🏾", "name": "接受按摩的人 中黑肤色" },
          { "emoj": "💆🏿", "name": "接受按摩的人 深色肤色" },
          { "emoj": "💆‍♂", "name": "男人接受按摩" },
          { "emoj": "💆🏻‍♂️", "name": "男人接受按摩 浅肤色" },
          { "emoj": "💆🏼‍♂️", "name": "男人接受按摩 中浅肤色" },
          { "emoj": "💆🏽‍♂", "name": "男人接受按摩 中等肤色" },
          { "emoj": "💆🏾‍♂️", "name": "男人接受按摩 中黑肤色" },
          { "emoj": "💆🏿‍♂", "name": "男人接受按摩 深色肤色" },
          { "emoj": "💆‍♀️", "name": "正在接受按摩的女人" },
          { "emoj": "💆🏻‍♀️", "name": "正在接受按摩的女人 浅肤色" },
          { "emoj": "💆🏼‍♀️", "name": "正在接受按摩的女人 中浅肤色" },
          { "emoj": "💆🏽‍♀️", "name": "正在接受按摩的女人 中等肤色" },
          { "emoj": "💆🏾‍♀️", "name": "正在接受按摩的女人 中黑肤色" },
          { "emoj": "💆🏿‍♀", "name": "正在接受按摩的女人 深色肤色" },
          { "emoj": "💇", "name": "理发的人" },
          { "emoj": "💇🏻", "name": "理发的人 浅肤色" },
          { "emoj": "💇🏼", "name": "理发的人 中浅肤色" },
          { "emoj": "💇🏽", "name": "理发的人 中等肤色" },
          { "emoj": "💇🏾", "name": "理发的人 中黑肤色" },
          { "emoj": "💇🏿", "name": "理发的人 深色肤色" },
        ]
      },
      {
        name: '人物与运动',
        children: [
          { "emoj": "🤺", "name": "人击剑" },
          { "emoj": "🏇", "name": "赛马" },
          { "emoj": "🏇🏻", "name": "赛马 浅肤色" },
          { "emoj": "🏇🏼", "name": "赛马 中浅肤色" },
          { "emoj": "🏇🏽", "name": "赛马 中等肤色" },
          { "emoj": "🏇🏾", "name": "赛马 中黑肤色" },
          { "emoj": "🏇🏿", "name": "赛马 深色肤色" },
          { "emoj": "⛷️", "name": "滑雪者" },
          { "emoj": "🏂", "name": "单板滑雪者" },
          { "emoj": "🏂🏻", "name": "单板滑雪者 浅肤色" },
          { "emoj": "🏂🏼", "name": "单板滑雪者 中浅肤色" },
          { "emoj": "🏂🏽", "name": "单板滑雪者 中等肤色" },
          { "emoj": "🏂🏾", "name": "单板滑雪者 中黑肤色" },
          { "emoj": "🏂🏿", "name": "单板滑雪者 深色肤色" },
          { "emoj": "🏌️", "name": "打高尔夫球的人" },
          { "emoj": "🏌🏻", "name": "打高尔夫球的人 浅肤色" },
          { "emoj": "🏌🏼", "name": "打高尔夫球的人 中浅肤色" },
          { "emoj": "🏌🏽", "name": "打高尔夫球的人 中等肤色" },
          { "emoj": "🏌🏾", "name": "打高尔夫球的人 中黑肤色" },
          { "emoj": "🏌🏿", "name": "打高尔夫球的人 深色肤色" },
          { "emoj": "🏌️‍♂️", "name": "男子打高尔夫球" },
          { "emoj": "🏌🏻‍♂️", "name": "男子打高尔夫球 浅肤色" },
          { "emoj": "🏌🏼‍♂️", "name": "男子打高尔夫球 中浅肤色" },
          { "emoj": "🏌🏽‍♂️", "name": "男子打高尔夫球 中等肤色" },
          { "emoj": "🏌🏾‍♂️", "name": "男子打高尔夫球 中黑肤色" },
          { "emoj": "🏌🏿‍♂️", "name": "男子打高尔夫球 深色肤色" },
          { "emoj": "🏌️‍♀️", "name": "打高尔夫球的女人" },
          { "emoj": "🏌🏻‍♀️", "name": "打高尔夫球的女人 浅肤色" },
          { "emoj": "🏌🏼‍♀️", "name": "打高尔夫球的女人 中浅肤色" },
          { "emoj": "🏌🏽‍♀️", "name": "打高尔夫球的女人 中等肤色" },
          { "emoj": "🏌🏾‍♀️", "name": "打高尔夫球的女人 中黑肤色" },
          { "emoj": "🏌🏿‍♀️", "name": "打高尔夫球的女人 深色肤色" },
          { "emoj": "🏄", "name": "冲浪的人" },
          { "emoj": "🏄🏻", "name": "冲浪的人 浅肤色" },
          { "emoj": "🏄🏼", "name": "冲浪的人 中浅肤色" },
          { "emoj": "🏄🏽", "name": "冲浪的人 中等肤色" },
          { "emoj": "🏄🏾", "name": "冲浪的人 中黑肤色" },
          { "emoj": "🏄🏿", "name": "冲浪的人 深色肤色" },
          { "emoj": "🏄‍♂️", "name": "男子冲浪" },
          { "emoj": "🏄🏻‍♂️", "name": "男子冲浪 浅肤色" },
          { "emoj": "🏄🏼‍♂️", "name": "男子冲浪 中浅肤色" },
          { "emoj": "🏄🏽‍♂️", "name": "男子冲浪 中等肤色" },
          { "emoj": "🏄🏾‍♂️", "name": "男子冲浪 中黑肤色" },
          { "emoj": "🏄🏿‍♂️", "name": "男子冲浪 深色肤色" },
          { "emoj": "🏄‍♀️", "name": "女子冲浪" },
          { "emoj": "🏄🏻‍♀️", "name": "女子冲浪 浅肤色" },
          { "emoj": "🏄🏼‍♀️", "name": "女子冲浪 中浅肤色" },
          { "emoj": "🏄🏽‍♀️", "name": "女子冲浪 中等肤色" },
          { "emoj": "🏄🏾‍♀️", "name": "女子冲浪 中黑肤色" },
          { "emoj": "🏄🏿‍♀️", "name": "女子冲浪 深色肤色" }
        ]
      },
      {
        name: '人物与休息',
        children: [
          { "emoj": "🧘", "name": "莲花坐的人" },
          { "emoj": "🧘🏻", "name": "莲花坐的人 浅肤色" },
          { "emoj": "🧘🏼", "name": "莲花坐的人 中浅肤色" },
          { "emoj": "🧘🏽", "name": "莲花坐的人 中等肤色" },
          { "emoj": "🧘🏾", "name": "莲花坐的人 中黑肤色" },
          { "emoj": "🧘🏿", "name": "莲花坐的人 深色肤色" },
          { "emoj": "🧘‍♂️", "name": "莲花坐的男人" },
          { "emoj": "🧘🏻‍♂️", "name": "莲花坐的男人 浅肤色" },
          { "emoj": "🧘🏼‍♂️", "name": "莲花坐的男人 中浅肤色" },
          { "emoj": "🧘🏽‍♂️", "name": "莲花坐的男人 中等肤色" },
          { "emoj": "🧘🏾‍♂️", "name": "莲花坐的男人 中黑肤色" },
          { "emoj": "🧘🏿‍♂️", "name": "莲花坐的男人 深色肤色" },
          { "emoj": "🧘‍♀️", "name": "莲花坐的女人" },
          { "emoj": "🧘🏻‍♀️", "name": "莲花坐的女人 浅肤色" },
          { "emoj": "🧘🏼‍♀️", "name": "莲花坐的女人 中浅肤色" },
          { "emoj": "🧘🏽‍♀️", "name": "莲花坐的女人 中等肤色" },
          { "emoj": "🧘🏾‍♀️", "name": "莲花坐的女人 中黑肤色" },
          { "emoj": "🧘🏿‍♀️", "name": "莲花坐的女人 深色肤色" },
          { "emoj": "🛀", "name": "洗澡的人" }
        ]
      },
      {
        name: '家庭',
        children: [
          { "emoj": "🧑‍🤝‍🧑", "name": "人们手牵着手" },
          { "emoj": "🧑🏻‍🤝‍🧑🏻", "name": "人们手牵着手 浅肤色" },
          { "emoj": "🧑🏻‍🤝‍🧑🏼", "name": "人们手牵着手 浅肤色 / 中浅肤色" },
          { "emoj": "🧑🏻‍🤝‍🧑🏽", "name": "人们手牵着手 浅肤色 / 中等肤色" },
          { "emoj": "🧑🏻‍🤝‍🧑🏾", "name": "人们手牵着手 浅肤色 / 中黑肤色" },
          { "emoj": "🧑🏻‍🤝‍🧑🏿", "name": "人们手牵着手 浅肤色 / 深色肤色" },
          { "emoj": "🧑🏼‍🤝‍🧑🏻", "name": "人们手牵着手 中浅肤色 / 浅肤色" },
          { "emoj": "🧑🏼‍🤝‍🧑🏼", "name": "人们手牵着手 中浅肤色" },
          { "emoj": "🧑🏼‍🤝‍🧑🏽", "name": "人们手牵着手 中浅肤色 / 中等肤色" },
          { "emoj": "🧑🏼‍🤝‍🧑🏾", "name": "人们手牵着手 中浅肤色 / 中黑肤色" },
          { "emoj": "🧑🏼‍🤝‍🧑🏿", "name": "人们手牵着手 中浅肤色 / 深色肤色" },
          { "emoj": "🧑🏽‍🤝‍🧑🏻", "name": "人们手牵着手 中等肤色 / 浅肤色" },
          { "emoj": "🧑🏽‍🤝‍🧑🏼", "name": "人们手牵着手 中等肤色 / 中浅肤色" },
          { "emoj": "🧑🏽‍🤝‍🧑🏽", "name": "人们手牵着手 中等肤色" },
          { "emoj": "🧑🏽‍🤝‍🧑🏾", "name": "人们手牵着手 中等肤色 / 中黑肤色" },
          { "emoj": "🧑🏽‍🤝‍🧑🏿", "name": "人们手牵着手 中等肤色 / 深色肤色" },
          { "emoj": "🧑🏾‍🤝‍🧑🏻", "name": "人们手牵着手 中黑肤色 / 浅肤色" },
          { "emoj": "🧑🏾‍🤝‍🧑🏼", "name": "人们手牵着手 中黑肤色 / 中浅肤色" },
          { "emoj": "🧑🏾‍🤝‍🧑🏽", "name": "人们手牵着手 中黑肤色 / 中等肤色" },
          { "emoj": "🧑🏾‍🤝‍🧑🏾", "name": "人们手牵着手 中黑肤色" },
          { "emoj": "🧑🏾‍🤝‍🧑🏿", "name": "人们手牵着手 中黑肤色 / 深色肤色" },
          { "emoj": "🧑🏿‍🤝‍🧑🏻", "name": "人们手牵着手 深色肤色 / 浅肤色" },
          { "emoj": "🧑🏿‍🤝‍🧑🏼", "name": "人们手牵着手 深色肤色 / 中浅肤色" },
          { "emoj": "🧑🏿‍🤝‍🧑🏽", "name": "人们手牵着手 深色肤色 / 中等肤色" },
          { "emoj": "🧑🏿‍🤝‍🧑🏾", "name": "人们手牵着手 深色肤色 / 中黑肤色" },
          { "emoj": "🧑🏿‍🤝‍🧑🏿", "name": "人们手牵着手 深色肤色" },
          { "emoj": "👭", "name": "妇女手牵着手" },
          { "emoj": "👭🏻", "name": "妇女手牵着手 浅肤色" },
          { "emoj": "👩🏻‍🤝‍👩🏼", "name": "妇女手牵着手 浅肤色 / 中浅肤色" },
          { "emoj": "👩🏻‍🤝‍👩🏽", "name": "妇女手牵着手 浅肤色 / 中等肤色" },
          { "emoj": "👩🏻‍🤝‍👩🏾", "name": "妇女手牵着手 浅肤色 / 中黑肤色" },
          { "emoj": "👩🏻‍🤝‍👩🏿", "name": "妇女手牵着手 浅肤色 / 深色肤色" }
        ]
      },
      {
        name: '人物与符号',
        children: [
          { emoj: '🗣️', name: '说话的头' },
          { emoj: '👤', name: '半身像的剪影' },
          { emoj: '👥', name: '半身像的剪影' },
          { emoj: '🫂', name: '人们拥抱' },
          { emoj: '👣', name: '脚印' }
        ]
      }
    ]
  },
  {
    name: '零件的表情符号',
    children: [
      {
        name: '皮肤与色调',
        children: [
          { emoj: '🏻', name: '浅肤色' },
          { emoj: '🏼', name: '中浅肤色' },
          { emoj: '🏽', name: '中等肤色' },
          { emoj: '🏾', name: '中黑肤色' },
          { emoj: '🏿', name: '深色肤色' }
        ]
      },
      {
        name: '发型与风格',
        children: [
          { emoj: '🦰', name: '红发' },
          { emoj: '🦱', name: '卷发' },
          { emoj: '🦳', name: '白色的头发' },
          { emoj: '🦲', name: '秃' }
        ]
      }
    ]
  },
  {
    name: '动物与自然的表情符号',
    children: [
      {
        name: '哺乳动物',
        children: [
          { "emoj": "🐵", "name": "猴脸" },
          { "emoj": "🐒", "name": "猴" },
          { "emoj": "🦍", "name": "大猩猩" },
          { "emoj": "🦧", "name": "猩猩" },
          { "emoj": "🐶", "name": "狗脸" },
          { "emoj": "🐕", "name": "狗" },
          { "emoj": "🦮", "name": "导盲犬" },
          { "emoj": "🐕‍🦺", "name": "服务犬" },
          { "emoj": "🐩", "name": "贵宾犬" },
          { "emoj": "🐺", "name": "狼" },
          { "emoj": "🦊", "name": "狐狸" },
          { "emoj": "🦝", "name": "狸" },
          { "emoj": "🐱", "name": "猫脸" },
          { "emoj": "🐈", "name": "猫" },
          { "emoj": "🐈‍⬛", "name": "黑猫" },
          { "emoj": "🦁", "name": "狮子" },
          { "emoj": "🐯", "name": "虎脸" },
          { "emoj": "🐅", "name": "老虎" },
          { "emoj": "🐆", "name": "豹" },
          { "emoj": "🐴", "name": "马脸" },
          { "emoj": "🫎", "name": "驼鹿" },
          { "emoj": "🫏", "name": "驴" },
          { "emoj": "🐎", "name": "马" },
          { "emoj": "🦄", "name": "独角兽" },
          { "emoj": "🦓", "name": "斑马" },
          { "emoj": "🦌", "name": "鹿" },
          { "emoj": "🦬", "name": "野牛" },
          { "emoj": "🐮", "name": "牛脸" },
          { "emoj": "🐂", "name": "牛" },
          { "emoj": "🐃", "name": "水牛" },
          { "emoj": "🐄", "name": "奶牛" },
          { "emoj": "🐷", "name": "猪脸" }
        ]
      },
      {
        name: '鸟类',
        children: [
          { "emoj": "🦃", "name": "火鸡" },
          { "emoj": "🐔", "name": "鸡" },
          { "emoj": "🐓", "name": "公鸡" },
          { "emoj": "🐣", "name": "孵化小鸡" },
          { "emoj": "🐤", "name": "小鸡" },
          { "emoj": "🐥", "name": "正面朝前的小鸡" },
          { "emoj": "🐦", "name": "鸟" },
          { "emoj": "🐧", "name": "企鹅" },
          { "emoj": "🕊️", "name": "鸽子" },
          { "emoj": "🦅", "name": "鹰" },
          { "emoj": "🦆", "name": "鸭子" },
          { "emoj": "🦢", "name": "天鹅" },
          { "emoj": "🦉", "name": "猫头鹰" },
          { "emoj": "🦤", "name": "渡渡鸟" },
          { "emoj": "🪶", "name": "羽毛" },
          { "emoj": "🦩", "name": "火烈鸟" },
          { "emoj": "🦚", "name": "孔雀" },
          { "emoj": "🦜", "name": "鹦鹉" },
          { "emoj": "🪽", "name": "翅膀" },
          { "emoj": "🐦‍⬛", "name": "黑鸟" },
          { "emoj": "🪿", "name": "鹅" }
        ]
      },
      {
        name: '两栖动物',
        children: [
          { "emoj": "🐸", "name": "青蛙" },
        ]
      },
      {
        name: '爬行动物',
        children: [
          { "emoj": "🐊", "name": "鳄鱼" },
          { "emoj": "🐢", "name": "龟" },
          { "emoj": "🦎", "name": "蜥蜴" },
          { "emoj": "🐍", "name": "蛇" },
          { "emoj": "🐲", "name": "龙脸" },
          { "emoj": "🐉", "name": "龙" },
          { "emoj": "🦕", "name": "蜥脚类动物" },
          { "emoj": "🦖", "name": "霸王龙" }
        ]
      },
      {
        name: '海洋动物',
        children: [
          { "emoj": "🐳", "name": "喷水鲸" },
          { "emoj": "🐋", "name": "鲸" },
          { "emoj": "🐬", "name": "海豚" },
          { "emoj": "🦭", "name": "海豹" },
          { "emoj": "🐟", "name": "鱼" },
          { "emoj": "🐠", "name": "热带鱼" },
          { "emoj": "🐡", "name": "河豚鱼" },
          { "emoj": "🦈", "name": "鲨鱼" },
          { "emoj": "🐙", "name": "章鱼" },
          { "emoj": "🐚", "name": "螺" },
          { "emoj": "🪸", "name": "珊瑚" },
          { "emoj": "🪼", "name": "海蜇" }
        ]
      },
      {
        name: '昆虫',
        children: [
          { "emoj": "🐌", "name": "蜗牛" },
          { "emoj": "🦋", "name": "蝴蝶" },
          { "emoj": "🐛", "name": "漏洞" },
          { "emoj": "🐜", "name": "蚂蚁" },
          { "emoj": "🐝", "name": "蜜蜂" },
          { "emoj": "🪲", "name": "甲虫" },
          { "emoj": "🐞", "name": "瓢虫" },
          { "emoj": "🦗", "name": "蟋蟀" },
          { "emoj": "🪳", "name": "蟑螂" },
          { "emoj": "🕷️", "name": "蜘蛛" },
          { "emoj": "🕸️", "name": "蜘蛛网" },
          { "emoj": "🦂", "name": "蝎" },
          { "emoj": "🦟", "name": "蚊子" },
          { "emoj": "🪰", "name": "飞" },
          { "emoj": "🪱", "name": "虫" },
          { "emoj": "🦠", "name": "微生物" }
        ]
      },
      {
        name: '植物与花朵',
        children: [
          { "emoj": "💐", "name": "花束" },
          { "emoj": "🌸", "name": "樱花" },
          { "emoj": "💮", "name": "白色的花" },
          { "emoj": "🪷", "name": "莲花" },
          { "emoj": "🏵️", "name": "玫瑰花结" },
          { "emoj": "🌹", "name": "玫瑰" },
          { "emoj": "🥀", "name": "枯萎的花" },
          { "emoj": "🌺", "name": "芙蓉" },
          { "emoj": "🌻", "name": "向日葵" },
          { "emoj": "🌼", "name": "开花" },
          { "emoj": "🌷", "name": "郁金香" },
          { "emoj": "🪻", "name": "风信子" }
        ]
      },
      {
        name: '植物与其他',
        children: [
          { "emoj": "🌱", "name": "幼苗" },
          { "emoj": "🪴", "name": "盆栽" },
          { "emoj": "🌲", "name": "常青树" },
          { "emoj": "🌳", "name": "落叶树" },
          { "emoj": "🌴", "name": "棕榈树" },
          { "emoj": "🌵", "name": "仙人掌" },
          { "emoj": "🌾", "name": "一捆米饭" },
          { "emoj": "🌿", "name": "草本植物" },
          { "emoj": "☘️", "name": "三叶草" },
          { "emoj": "☘", "name": "三叶草" },
          { "emoj": "🍀", "name": "四叶草" },
          { "emoj": "🍁", "name": "枫叶" },
          { "emoj": "🍂", "name": "落叶" },
          { "emoj": "🍃", "name": "树叶在风中飘扬" },
          { "emoj": "🪹", "name": "空巢" },
          { "emoj": "🪺", "name": "与蛋筑巢" },
          { "emoj": "🍄", "name": "蘑菇" }
        ]
      }
    ]
  },
  {
    name: '食物与饮料的表情符号',
    children: [
      {
        name: '水果',
        children: [
          { "emoj": "🍇", "name": "葡萄" },
          { "emoj": "🍈", "name": "瓜" },
          { "emoj": "🍉", "name": "西瓜" },
          { "emoj": "🍊", "name": "柑橘" },
          { "emoj": "🍋", "name": "柠檬" },
          { "emoj": "🍌", "name": "香蕉" },
          { "emoj": "🍍", "name": "菠萝" },
          { "emoj": "🥭", "name": "芒果" },
          { "emoj": "🍎", "name": "红苹果" },
          { "emoj": "🍏", "name": "青苹果" },
          { "emoj": "🍐", "name": "梨" },
          { "emoj": "🍑", "name": "桃" },
          { "emoj": "🍒", "name": "樱桃" },
          { "emoj": "🍓", "name": "草莓" },
          { "emoj": "🫐", "name": "蓝莓" },
          { "emoj": "🥝", "name": "奇异果" },
          { "emoj": "🍅", "name": "番茄" },
          { "emoj": "🫒", "name": "橄榄" },
          { "emoj": "🥥", "name": "椰子" }
        ]
      },
      {
        name: '蔬菜',
        children: [
          { "emoj": "🥑", "name": "牛油果" },
          { "emoj": "🍆", "name": "茄子" },
          { "emoj": "🥔", "name": "土豆" },
          { "emoj": "🥕", "name": "胡萝卜" },
          { "emoj": "🌽", "name": "玉米穗" },
          { "emoj": "🌶️", "name": "辣椒" },
          { "emoj": "🫑", "name": "灯笼椒" },
          { "emoj": "🥒", "name": "黄瓜" },
          { "emoj": "🥬", "name": "绿叶" },
          { "emoj": "🥦", "name": "西兰花" },
          { "emoj": "🧄", "name": "蒜" },
          { "emoj": "🧅", "name": "洋葱" },
          { "emoj": "🥜", "name": "花生" },
          { "emoj": "🫘", "name": "豆子" },
          { "emoj": "🌰", "name": "板栗" },
          { "emoj": "🫚", "name": "姜根" },
          { "emoj": "🫛", "name": "豌豆荚" }
        ]
      },
      {
        name: '加工食品',
        children: [
          { "emoj": "🍞", "name": "面包" },
          { "emoj": "🥐", "name": "羊角面包" },
          { "emoj": "🥖", "name": "长棍面包" },
          { "emoj": "🫓", "name": "大饼" },
          { "emoj": "🥨", "name": "椒盐卷饼" },
          { "emoj": "🥯", "name": "百吉饼" },
          { "emoj": "🥞", "name": "薄煎饼" },
          { "emoj": "🧇", "name": "胡扯" },
          { "emoj": "🧀", "name": "奶酪角" },
          { "emoj": "🍖", "name": "骨头上的肉" },
          { "emoj": "🍗", "name": "家禽腿" },
          { "emoj": "🥩", "name": "切肉" },
          { "emoj": "🥓", "name": "熏肉" },
          { "emoj": "🍔", "name": "汉堡包" },
          { "emoj": "🍟", "name": "炸薯条" },
          { "emoj": "🍕", "name": "比萨" },
          { "emoj": "🌭", "name": "热狗" },
          { "emoj": "🥪", "name": "三明治" },
          { "emoj": "🌮", "name": "炸玉米饼" },
          { "emoj": "🌯", "name": "墨西哥卷饼" },
          { "emoj": "🫔", "name": "塔马利" },
          { "emoj": "🥙", "name": "酿大饼" },
          { "emoj": "🧆", "name": "沙拉三明治" },
          { "emoj": "🥚", "name": "蛋" },
          { "emoj": "🍳", "name": "烹饪" },
          { "emoj": "🥘", "name": "浅盘食物" },
          { "emoj": "🍲", "name": "一锅食物" },
          { "emoj": "🫕", "name": "火锅" },
          { "emoj": "🥣", "name": "带勺子的碗" },
          { "emoj": "🥗", "name": "绿色的沙拉" },
          { "emoj": "🍿", "name": "爆米花" },
          { "emoj": "🧈", "name": "黄油" }
        ]
      },
      {
        name: '亚洲食品',
        children: [
          { "emoj": "🍱", "name": "便当盒" },
          { "emoj": "🍘", "name": "米果" },
          { "emoj": "🍙", "name": "饭团" },
          { "emoj": "🍚", "name": "熟米饭" },
          { "emoj": "🍛", "name": "咖喱饭" },
          { "emoj": "🍜", "name": "蒸碗" },
          { "emoj": "🍝", "name": "意大利细面条" },
          { "emoj": "🍠", "name": "烤红薯" },
          { "emoj": "🍢", "name": "奥登" },
          { "emoj": "🍣", "name": "寿司" },
          { "emoj": "🍤", "name": "炒虾仁" },
          { "emoj": "🍥", "name": "带漩涡的鱼饼" },
          { "emoj": "🥮", "name": "月饼" },
          { "emoj": "🍡", "name": "团子" },
          { "emoj": "🥟", "name": "饺子" },
          { "emoj": "🥠", "name": "幸运饼干" },
          { "emoj": "🥡", "name": "外卖盒" }
        ]
      },
      {
        name: '海鲜',
        children: [
          { "emoj": "🦀", "name": "螃蟹" },
          { "emoj": "🦞", "name": "龙虾" },
          { "emoj": "🦐", "name": "虾" },
          { "emoj": "🦑", "name": "乌贼" },
          { "emoj": "🦪", "name": "牡蛎" }
        ]
      },
      {
        name: '甜食',
        children: [
          { "emoj": "🍦", "name": "软冰淇淋" },
          { "emoj": "🍧", "name": "刨冰" },
          { "emoj": "🍨", "name": "冰淇淋" },
          { "emoj": "🍩", "name": "油炸圈饼" },
          { "emoj": "🍪", "name": "曲奇饼" },
          { "emoj": "🎂", "name": "生日蛋糕" },
          { "emoj": "🍰", "name": "脆饼" },
          { "emoj": "🧁", "name": "纸杯蛋糕" },
          { "emoj": "🥧", "name": "馅饼" },
          { "emoj": "🍫", "name": "巧克力吧" },
          { "emoj": "🍬", "name": "糖果" },
          { "emoj": "🍭", "name": "棒糖" },
          { "emoj": "🍮", "name": "卡仕达酱" },
          { "emoj": "🍯", "name": "蜜罐" }
        ]
      },
      {
        name: '饮料',
        children: [
          { "emoj": "🍼", "name": "婴儿奶瓶" },
          { "emoj": "🥛", "name": "一杯牛奶" },
          { "emoj": "☕", "name": "热饮" },
          { "emoj": "🫖", "name": "茶壶" },
          { "emoj": "🍵", "name": "没有把手的茶杯" },
          { "emoj": "🍶", "name": "清酒" },
          { "emoj": "🍾", "name": "软木塞爆开的瓶子" },
          { "emoj": "🍷", "name": "红酒杯" },
          { "emoj": "🍸", "name": "鸡尾酒杯" },
          { "emoj": "🍹", "name": "热带饮料" },
          { "emoj": "🍺", "name": "啤酒杯" },
          { "emoj": "🍻", "name": "叮当作响的啤酒杯" },
          { "emoj": "🥂", "name": "叮当作响的眼镜" },
          { "emoj": "🥃", "name": "玻璃杯" },
          { "emoj": "🫗", "name": "倾倒液体" },
          { "emoj": "🥤", "name": "带吸管的杯子" },
          { "emoj": "🧋", "name": "珍珠奶茶" },
          { "emoj": "🧃", "name": "饮料盒" },
          { "emoj": "🧉", "name": "伴侣" },
          { "emoj": "🧊", "name": "冰" }
        ]
      },
      {
        name: '餐具',
        children: [
          { "emoj": "🥢", "name": "筷子" },
          { "emoj": "🍽️", "name": "带盘子的叉子和刀子" },
          { "emoj": "🍴", "name": "刀叉" },
          { "emoj": "🥄", "name": "勺子" },
          { "emoj": "🔪", "name": "菜刀" },
          { "emoj": "🫙", "name": "罐" },
          { "emoj": "🏺", "name": "双耳瓶" }
        ]
      }
    ]
  },
  {
    name: '旅行与地点的表情符号',
    children: [
      {
        name: '地点与地图',
        children: [
          { "emoj": "🌍", "name": "显示欧洲-非洲的地球仪" },
          { "emoj": "🌎", "name": "显示美洲的地球仪" },
          { "emoj": "🌏", "name": "显示亚洲-澳大利亚的地球仪" },
          { "emoj": "🌐", "name": "有经络的地球仪" },
          { "emoj": "🗺️", "name": "世界地图" },
          { "emoj": "🗾", "name": "日本地图" },
          { "emoj": "🧭", "name": "罗盘" }
        ]
      },
      {
        name: '地理位置',
        children: [
          { "emoj": "🏔️", "name": "雪山" },
          { "emoj": "⛰️", "name": "山" },
          { "emoj": "🌋", "name": "火山" },
          { "emoj": "🗻", "name": "富士山" },
          { "emoj": "🏕️", "name": "野营" },
          { "emoj": "🏖️", "name": "带伞的海滩" },
          { "emoj": "🏜️", "name": "沙漠" },
          { "emoj": "🏝️", "name": "沙漠荒岛" },
          { "emoj": "🏞️", "name": "国家公园" }
        ]
      },
      {
        name: '建筑物',
        children: [
          { "emoj": "🏟️", "name": "体育场" },
          { "emoj": "🏛️", "name": "古典建筑" },
          { "emoj": "🏗️", "name": "建筑施工" },
          { "emoj": "🧱", "name": "砖" },
          { "emoj": "🪨", "name": "岩石" },
          { "emoj": "🪵", "name": "木头" },
          { "emoj": "🛖", "name": "小屋" },
          { "emoj": "🏘️", "name": "房屋" },
          { "emoj": "🏚️", "name": "废弃的房子" },
          { "emoj": "🏠", "name": "房子" },
          { "emoj": "🏡", "name": "带花园的房子" },
          { "emoj": "🏢", "name": "办公楼" },
          { "emoj": "🏣", "name": "日本邮局" },
          { "emoj": "🏤", "name": "邮局" },
          { "emoj": "🏥", "name": "医院" },
          { "emoj": "🏦", "name": "银行" },
          { "emoj": "🏨", "name": "酒店" },
          { "emoj": "🏩", "name": "爱情酒店" },
          { "emoj": "🏪", "name": "便利店" },
          { "emoj": "🏫", "name": "学校" },
          { "emoj": "🏬", "name": "百货商店" },
          { "emoj": "🏭", "name": "工厂" },
          { "emoj": "🏯", "name": "日本城堡" },
          { "emoj": "🏰", "name": "城堡" },
          { "emoj": "💒", "name": "婚礼" },
          { "emoj": "🗼", "name": "东京塔" },
          { "emoj": "🗽", "name": "自由女神像" }
        ]
      },
      {
        name: '宗教建筑',
        children: [
          { "emoj": "⛪", "name": "教会" },
          { "emoj": "🕌", "name": "清真寺" },
          { "emoj": "🛕", "name": "印度教寺庙" },
          { "emoj": "🕍", "name": "犹太教堂" },
          { "emoj": "⛩️", "name": "神社" },
          { "emoj": "🕋", "name": "天房" }
        ]
      },
      {
        name: '其他地点',
        children: [
          { "emoj": "⛲", "name": "喷泉" },
          { "emoj": "⛺", "name": "帐篷" },
          { "emoj": "🌁", "name": "有雾" },
          { "emoj": "🌃", "name": "有星星的夜晚" },
          { "emoj": "🏙️", "name": "城市景观" },
          { "emoj": "🌄", "name": "山上的日出" },
          { "emoj": "🌅", "name": "日出" },
          { "emoj": "🌆", "name": "黄昏时的城市景观" },
          { "emoj": "🌇", "name": "日落" },
          { "emoj": "🌉", "name": "晚上的桥" },
          { "emoj": "♨️", "name": "温泉" },
          { "emoj": "🎠", "name": "旋转木马" },
          { "emoj": "🛝", "name": "游乐场滑梯" },
          { "emoj": "🎡", "name": "摩天轮" },
          { "emoj": "🎢", "name": "过山车" },
          { "emoj": "💈", "name": "理发店招牌" },
          { "emoj": "🎪", "name": "马戏团帐篷" }
        ]
      },
      {
        name: '陆地交通工具',
        children: [
          { "emoj": "🚂", "name": "机车" },
          { "emoj": "🚃", "name": "火车车厢" },
          { "emoj": "🚄", "name": "高速火车" },
          { "emoj": "🚅", "name": "子弹头列车" },
          { "emoj": "🚆", "name": "火车" },
          { "emoj": "🚇", "name": "地铁" },
          { "emoj": "🚈", "name": "轻轨" },
          { "emoj": "🚉", "name": "车站" },
          { "emoj": "🚊", "name": "电车" },
          { "emoj": "🚝", "name": "单轨铁路" },
          { "emoj": "🚞", "name": "山区铁路" },
          { "emoj": "🚋", "name": "有轨电车" },
          { "emoj": "🚌", "name": "公共汽车" },
          { "emoj": "🚍", "name": "迎面而来的巴士" },
          { "emoj": "🚎", "name": "电车" },
          { "emoj": "🚐", "name": "小巴" },
          { "emoj": "🚑", "name": "救护车" },
          { "emoj": "🚒", "name": "消防车" },
          { "emoj": "🚓", "name": "警车" },
          { "emoj": "🚔", "name": "迎面而来的警车" },
          { "emoj": "🚕", "name": "出租车" },
          { "emoj": "🚖", "name": "迎面而来的出租车" },
          { "emoj": "🚗", "name": "汽车" },
          { "emoj": "🚘", "name": "迎面而来的汽车" },
          { "emoj": "🚙", "name": "运动型多用途车" },
          { "emoj": "🛻", "name": "皮卡车" },
          { "emoj": "🚚", "name": "送货卡车" },
          { "emoj": "🚛", "name": "铰接式货车" },
          { "emoj": "🚜", "name": "拖拉机" },
          { "emoj": "🏎️", "name": "赛车" },
          { "emoj": "🏍️", "name": "摩托车" }
        ]
      },
      {
        name: '水上交通工具',
        children: [
          { "emoj": "⚓", "name": "锚" },
          { "emoj": "🛟", "name": "环形浮标" },
          { "emoj": "⛵", "name": "帆船" },
          { "emoj": "🛶", "name": "独木舟" },
          { "emoj": "🚤", "name": "快艇" },
          { "emoj": "🛳️", "name": "客船" },
          { "emoj": "⛴️", "name": "渡船" },
          { "emoj": "🛥️", "name": "摩托艇" },
          { "emoj": "🚢", "name": "船" }
        ]
      },
      {
        name: '空中交通工具',
        children: [
          { "emoj": "✈️", "name": "飞机" },
          { "emoj": "🛫", "name": "飞机起飞" },
          { "emoj": "🛬", "name": "飞机到达" },
          { "emoj": "🛩️", "name": "小飞机" },
          { "emoj": "🪂", "name": "降落伞" },
          { "emoj": "💺", "name": "座位" },
          { "emoj": "🚁", "name": "直升机" },
          { "emoj": "🚟", "name": "悬索铁路" },
          { "emoj": "🚠", "name": "山地索道" },
          { "emoj": "🚡", "name": "空中缆车" },
          { "emoj": "🛰️", "name": "卫星" },
          { "emoj": "🚀", "name": "火箭" },
          { "emoj": "🛸", "name": "飞碟" }
        ]
      },
      {
        name: '酒店',
        children: [
          { "emoj": "🛎️", "name": "侍者铃" },
          { "emoj": "🧳", "name": "行李" }
        ]
      },
      {
        name: '时间',
        children: [
          { "emoj": "⌛", "name": "沙漏完成" },
          { "emoj": "⏳", "name": "沙漏未完成" },
          { "emoj": "⌚", "name": "手表" },
          { "emoj": "⏰", "name": "闹钟" },
          { "emoj": "⏱️", "name": "跑表" },
          { "emoj": "⏲️", "name": "定时器时钟" },
          { "emoj": "🕰️", "name": "壁炉台钟" },
          { "emoj": "🕛", "name": "12点" },
          { "emoj": "🕧", "name": "12点半" },
          { "emoj": "🕐", "name": "1点" },
          { "emoj": "🕜", "name": "1点半" },
          { "emoj": "🕑", "name": "2点" },
          { "emoj": "🕝", "name": "2点半" },
          { "emoj": "🕒", "name": "3点" },
          { "emoj": "🕞", "name": "3点半" },
          { "emoj": "🕓", "name": "4点" },
          { "emoj": "🕟", "name": "4点半" },
          { "emoj": "🕔", "name": "5点" },
          { "emoj": "🕠", "name": "5点半" },
          { "emoj": "🕕", "name": "6点" },
          { "emoj": "🕡", "name": "6点半" },
          { "emoj": "🕖", "name": "7点" },
          { "emoj": "🕢", "name": "7点半" },
          { "emoj": "🕗", "name": "8点" },
          { "emoj": "🕣", "name": "8点半" },
          { "emoj": "🕘", "name": "9点" },
          { "emoj": "🕤", "name": "9点半" },
          { "emoj": "🕙", "name": "10点" },
          { "emoj": "🕥", "name": "10点半" }
        ]
      },
      {
        name: '天空与天气',
        children: [
          { "emoj": "🌑", "name": "新月" },
          { "emoj": "🌒", "name": "峨眉月（初亏月）" },
          { "emoj": "🌓", "name": "上弦月" },
          { "emoj": "🌔", "name": "盈凸月" },
          { "emoj": "🌕", "name": "满月" },
          { "emoj": "🌖", "name": "亏凸月" },
          { "emoj": "🌗", "name": "下弦月" },
          { "emoj": "🌘", "name": "残月" },
          { "emoj": "🌙", "name": "弯弯的月亮" },
          { "emoj": "🌚", "name": "新月脸" },
          { "emoj": "🌛", "name": "上弦月脸" },
          { "emoj": "🌜", "name": "下弦月脸" },
          { "emoj": "🌡️", "name": "温度计" },
          { "emoj": "☀️", "name": "太阳" },
          { "emoj": "🌝", "name": "满月脸" },
          { "emoj": "🌞", "name": "太阳笑脸" },
          { "emoj": "🪐", "name": "环行星" },
          { "emoj": "⭐", "name": "星星" },
          { "emoj": "🌟", "name": "闪烁的星星" },
          { "emoj": "🌠", "name": "流星" },
          { "emoj": "🌌", "name": "银河系" },
          { "emoj": "☁️", "name": "云" },
          { "emoj": "⛅", "name": "太阳和云" },
          { "emoj": "⛈️", "name": "雷雨云" },
          { "emoj": "🌤️", "name": "阳光穿过小云" },
          { "emoj": "🌥️", "name": "太阳在大片云后" },
          { "emoj": "🌦️", "name": "太阳在雨云后" },
          { "emoj": "🌧️", "name": "下雨的云" },
          { "emoj": "🌨️", "name": "下雪的云" },
          { "emoj": "🌩️", "name": "闪电的云" },
          { "emoj": "🌪️", "name": "龙卷风" },
          { "emoj": "🌫️", "name": "雾" },
          { "emoj": "🌬️", "name": "风脸" },
          { "emoj": "🌀", "name": "漩涡" },
          { "emoj": "🌈", "name": "彩虹" },
          { "emoj": "🌂", "name": "折叠伞" },
          { "emoj": "☂️", "name": "伞" },
          { "emoj": "☔", "name": "带雨滴的伞" },
          { "emoj": "⛱️", "name": "沙滩伞" },
          { "emoj": "⚡", "name": "高压电" },
          { "emoj": "❄️", "name": "雪花" },
          { "emoj": "☃️", "name": "雪人" },
          { "emoj": "⛄", "name": "无雪的雪人" },
          { "emoj": "☄️", "name": "彗星" },
          { "emoj": "🔥", "name": "火焰" },
          { "emoj": "💧", "name": "水滴" },
          { "emoj": "🌊", "name": "海浪" }
        ]
      }
    ]
  }
]
