import { ItemType } from '../interface';

export const emojItems: ItemType[] = [
  {
    name: '笑脸与情感的表情符号',
    children: [
      {
        name: '脸与微笑',
        children: [
          { emoj: '😀', name: '笑脸' },
          { emoj: '😃', name: '笑脸大眼睛' },
          { emoj: '😄', name: '笑脸和微笑的眼睛' },
          { emoj: '😁', name: '脸上带着微笑的眼睛' },
          { emoj: '😆', name: '眯着眼睛笑的脸' },
          { emoj: '😅', name: '满脸汗水的笑脸' },
          { emoj: '🤣', name: '笑得在地上打滚' },
          { emoj: '😂', name: '满脸喜悦的泪水' },
          { emoj: '🙂', name: '微微微笑的脸' },
          { emoj: '🙃', name: '颠倒的脸' },
          { emoj: '🫠', name: '融化的脸' },
          { emoj: '😉', name: '眨眼的脸' },
          { emoj: '😊', name: '微笑的脸和微笑的眼睛' },
          { emoj: '😇', name: '带光环的笑脸' },
        ]
      },
      {
        name: '脸与情感',
        children: [
          { emoj: '🥰', name: '笑脸与心' },
          { emoj: '😍', name: '心形眼睛的笑脸' },
          { emoj: '🤩', name: '追星的' },
          { emoj: '😘', name: '脸飞吻' },
          { emoj: '😗', name: '亲吻脸' },
          { emoj: '☺️', name: '微笑的面孔' },
          { emoj: '☺', name: '微笑的面孔' },
          { emoj: '😚', name: '闭着眼睛亲吻脸' },
          { emoj: '😙', name: '带着微笑的眼睛亲吻脸' },
          { emoj: '🥲', name: '含着泪水的笑脸' },
        ]
      },
      {
        name: '脸与舌头',
        children: [
          { emoj: '😋', name: '品尝食物的脸' },
          { emoj: '😛', name: '用舌头面对' },
          { emoj: '😜', name: '用舌头眨眼的脸' },
          { emoj: '🤪', name: '滑稽的脸' },
          { emoj: '😝', name: '用舌头眯着脸' },
          { emoj: '🤑', name: '钱嘴脸' },
        ]
      },
      {
        name: '脸与手势',
        children: [
          { emoj: '🤗', name: '张开双手微笑的脸' },
          { emoj: '🤭', name: '用手捂住嘴脸' },
          { emoj: '🫢', name: '睁开眼睛并用手捂住嘴' },
          { emoj: '🫣', name: '脸上有偷看的眼睛' },
          { emoj: '🤫', name: '嘘脸' },
          { emoj: '🤔', name: '思考的脸' },
          { emoj: '🫡', name: '敬礼的脸' },
        ]
      },
      {
        name: '脸与中性与怀疑',
        children: [
          { emoj: '🤐', name: '拉链嘴脸' },
          { emoj: '🤨', name: '扬眉的脸' },
          { emoj: '😐', name: '中性面孔' },
          { emoj: '😑', name: '面无表情' },
          { emoj: '😶', name: '没有嘴的脸' },
          { emoj: '🫥', name: '虚线面' },
          { emoj: '😶‍🌫️', name: '云中的脸' },
          { emoj: '😏', name: '傻笑的脸' },
          { emoj: '😒', name: '不高兴的脸' },
          { emoj: '🙄', name: '翻白眼的脸' },
          { emoj: '😬', name: '鬼脸' },
          { emoj: '😮‍💨', name: '面部呼气' },
          { emoj: '🤥', name: '说谎的脸' },
          { emoj: '🫨', name: '摇脸' },
        ]
      },
      {
        name: '脸与困倦',
        children: [
          { emoj: '😌', name: '释然的脸' },
          { emoj: '😔', name: '沉思的脸' },
          { emoj: '😪', name: '困倦的脸' },
          { emoj: '🤤', name: '流口水的脸' },
          { emoj: '😴', name: '睡脸' },
        ]
      },
      {
        name: '脸与不适',
        children: [
          { emoj: '😷', name: '带着医用口罩的脸' },
          { emoj: '🤒', name: '带温度计的脸' },
          { emoj: '🤕', name: '头上缠着绷带的脸' },
          { emoj: '🤢', name: '恶心的脸' },
          { emoj: '🤮', name: '脸部呕吐' },
          { emoj: '🤧', name: '打喷嚏的脸' },
          { emoj: '🥵', name: '脸热' },
          { emoj: '🥶', name: '冷脸' },
          { emoj: '🥴', name: '昏昏沉沉的脸' },
          { emoj: '😵', name: '交叉眼睛的脸' },
          { emoj: '😵‍💫', name: '螺旋形眼睛的脸' },
          { emoj: '🤯', name: '爆炸头' },
        ]
      },
      {
        name: '脸与帽子',
        children: [
          { emoj: '🤠', name: '牛仔帽脸' },
          { emoj: '🥳', name: '派对脸' },
          { emoj: '🥸', name: '伪装的脸' },

        ]
      },
      {
        name: '脸与眼镜',
        children: [
          { emoj: '😎', name: '戴着墨镜的笑脸' },
          { emoj: '🤓', name: '书呆子脸' },
          { emoj: '🧐', name: '带单片眼镜的脸' },
        ]
      },
      {
        name: '脸与担忧',
        children: [
          { emoj: '😕', name: '困惑的脸' },
          { emoj: '🫤', name: '斜嘴脸' },
          { emoj: '😟', name: '担心的脸' },
          { emoj: '🙁', name: '微微皱眉的脸' },
          { emoj: '☹️', name: '皱眉的脸' },
          { emoj: '☹', name: '皱眉的脸' },
          { emoj: '😮', name: '张开嘴的脸' },
          { emoj: '😯', name: '安静的脸' },
          { emoj: '😲', name: '惊讶的脸' },
          { emoj: '😳', name: '脸红了' },
          { emoj: '🥺', name: '恳求的脸' },
          { emoj: '🥹', name: '强忍着泪水的脸' },
          { emoj: '😦', name: '张开嘴皱着眉头' },
          { emoj: '😧', name: '痛苦的脸' },
          { emoj: '😨', name: '恐惧的脸' },
          { emoj: '😰', name: '满脸焦急满头大汗' },
          { emoj: '😥', name: '悲伤但如释重负的脸' },
          { emoj: '😢', name: '哭泣的脸' },
          { emoj: '😭', name: '大声哭泣的脸' },
          { emoj: '😱', name: '脸上因恐惧而尖叫' },
          { emoj: '😖', name: '困惑的脸' },
          { emoj: '😣', name: '坚忍的脸' },
          { emoj: '😞', name: '失望的脸' },
          { emoj: '😓', name: '满脸汗水低垂的脸' },
          { emoj: '😩', name: '疲倦的脸' },
          { emoj: '😫', name: '疲惫的脸' },
          { emoj: '🥱', name: '打呵欠的脸' },
        ]
      },
      {
        name: '脸与消极',
        children: [
          { emoj: '😤', name: '鼻子里冒着蒸汽的脸' },
          { emoj: '😡', name: '愤怒的脸' },
          { emoj: '😠', name: '愤怒的脸' },
          { emoj: '🤬', name: '嘴上有符号的脸' },
          { emoj: '😈', name: '带角的笑脸' },
          { emoj: '👿', name: '有角的愤怒的脸' },
          { emoj: '💀', name: '颅骨' },
          { emoj: '☠️', name: '骷髅和交叉骨' },
          { emoj: '☠', name: '骷髅和交叉骨' },
        ]
      },
      {
        name: '脸与服装',
        children: [
          { emoj: '💩', name: '一堆便便' },
          { emoj: '🤡', name: '小丑脸' },
          { emoj: '👹', name: '食人魔' },
          { emoj: '👺', name: '妖精' },
          { emoj: '👻', name: '鬼' },
          { emoj: '👽', name: '外星人' },
          { emoj: '👾', name: '外星怪物' },
          { emoj: '🤖', name: '机器人' },
        ]
      },
      {
        name: '猫与脸',
        children: [
          { emoj: '😺', name: '咧着嘴笑的猫' },
          { emoj: '😸', name: '微笑的猫，带着微笑的眼睛' },
          { emoj: '😹', name: '猫流着喜悦的泪水' },
          { emoj: '😻', name: '心形眼睛微笑的猫' },
          { emoj: '😼', name: '苦笑的猫' },
          { emoj: '😽', name: '接吻猫' },
          { emoj: '🙀', name: '疲倦的猫' },
          { emoj: '😿', name: '哭泣的猫' },
          { emoj: '😾', name: '撅嘴的猫' },
        ]
      },
      {
        name: '猴与脸',
        children: [
          { emoj: '🙈', name: '无恶不作的猴子' },
          { emoj: '🙉', name: '不闻不问的猴子' },
          { emoj: '🙊', name: '不说邪恶的猴子' },
        ]
      },
      {
        name: '心形',
        children: [
          { emoj: '💌', name: '爱情信' },
          { emoj: '💘', name: '带箭头的心' },
          { emoj: '💝', name: '带丝带的心' },
          { emoj: '💖', name: '闪闪发光的心' },
          { emoj: '💗', name: '成长的心' },
          { emoj: '💓', name: '跳动的心' },
          { emoj: '💞', name: '旋转的心' },
          { emoj: '💕', name: '两颗心' },
          { emoj: '💟', name: '心形装饰' },
          { emoj: '❣️', name: '心中感叹' },
          { emoj: '❣', name: '心中感叹' },
          { emoj: '💔', name: '破碎的心' },
          { emoj: '❤️‍🔥', name: '心脏着火' },
          { emoj: '❤️‍🩹', name: '修补心' },
          { emoj: '❤️', name: '红心' },
          { emoj: '❤', name: '红心' },
          { emoj: '🩷', name: '粉红色的心' },
          { emoj: '🧡', name: '橙色的心' },
          { emoj: '💛', name: '黄心' },
          { emoj: '💚', name: '绿心' },
          { emoj: '💙', name: '蓝色的心' },
          { emoj: '🩵', name: '淡蓝色的心' },
          { emoj: '💜', name: '紫心的心' },
          { emoj: '🤎', name: '棕色的心' },
          { emoj: '🖤', name: '黑心' },
          { emoj: '🩶', name: '灰色的心' },
          { emoj: '🤍', name: '白心' },
        ]
      },
      {
        name: '情感',
        children: [
          { emoj: '💋', name: '吻痕' },
          { emoj: '💯', name: '百分' },
          { emoj: '💢', name: '愤怒的象征' },
          { emoj: '💥', name: '碰撞' },
          { emoj: '💦', name: '汗滴' },
          { emoj: '💨', name: '匆匆而去' },
          { emoj: '🕳️', name: '洞' },
          { emoj: '💬', name: '语音气球' },
          { emoj: '👁️‍🗨️', name: '讲话泡泡中的眼睛' },
          { emoj: '🗨️', name: '左边的语音气泡' },
          { emoj: '🗯️', name: '右愤怒泡沫' },
          { emoj: '💭', name: '思想气球' },
          { emoj: '💤', name: 'ZZZ' },
        ]
      }
    ]
  },
  {
    name: '人物与身体的表情符号',
    children: [
      {
        name: '手与手指展开',
        children: [
          { emoj: '👋', name: '挥手' },
          { emoj: '👋🏻', name: '挥手 浅肤色' },
          { emoj: '👋🏼', name: '挥手 中浅肤色' },
          { emoj: '👋🏽', name: '挥手 中等肤色' },
          { emoj: '👋🏾', name: '挥手 中黑肤色' },
          { emoj: '👋🏿', name: '挥手 深色肤色' },
          { emoj: '🤚', name: '举起手背' },
          { emoj: '🤚🏻', name: '举起手背 浅肤色' },
          { emoj: '🤚🏼', name: '举起手背 中浅肤色' },
          { emoj: '🤚🏽', name: '举起手背 中等肤色' },
          { emoj: '🤚🏾', name: '举起手背 中黑肤色' },
          { emoj: '🤚🏿', name: '举起手背 深色肤色' },
          { emoj: '🖐', name: '手指张开的手' },
          { emoj: '🖐🏻', name: '手指张开的手 浅肤色' },
          { emoj: '🖐🏼', name: '手指张开的手 中浅肤色' },
          { emoj: '🖐🏽', name: '手指张开的手 中等肤色' },
          { emoj: '🖐🏾', name: '手指张开的手 中黑肤色' },
          { emoj: '🖐🏿', name: '手指张开的手 深色肤色' },
          { emoj: '✋', name: '举起手' },
          { emoj: '✋🏻', name: '举起手 浅肤色' },
          { emoj: '✋🏼', name: '举起手 中浅肤色' },
          { emoj: '✋🏽', name: '举起手 中等肤色' },
          { emoj: '✋🏾', name: '举起手 中黑肤色' },
          { emoj: '✋🏿', name: '举起手 深色肤色' },
          { emoj: '🖖', name: '瓦肯敬礼' },
          { emoj: '🖖🏻', name: '瓦肯敬礼 浅肤色' },
          { emoj: '🖖🏼', name: '瓦肯敬礼 中浅肤色' },
          { emoj: '🖖🏽', name: '瓦肯敬礼 中等肤色' },
          { emoj: '🖖🏾', name: '瓦肯敬礼 中黑肤色' },
          { emoj: '🖖🏿', name: '瓦肯敬礼 深色肤色' },
          { emoj: '🫱', name: '右手' },
          { emoj: '🫱🏻', name: '右手 浅肤色' },
          { emoj: '🫱🏼', name: '右手 中浅肤色' },
          { emoj: '🫱🏽', name: '右手 中等肤色' },
          { emoj: '🫱🏾', name: '右手 中黑肤色' },
          { emoj: '🫱🏿', name: '右手 深色肤色' },
          { emoj: '🫲', name: '左手' },
          { emoj: '🫲🏻', name: '左手 浅肤色' },
          { emoj: '🫲🏼', name: '左手 中浅肤色' },
          { emoj: '🫲🏽', name: '左手 中等肤色' },
          { emoj: '🫲🏾', name: '左手 中黑肤色' },
          { emoj: '🫲🏿', name: '左手 深色肤色' },
          { emoj: '🫳', name: '双手' },
          { emoj: '🫳🏻', name: '双手 浅肤色' },
          { emoj: '🫳🏼', name: '双手 中浅肤色' },
          { emoj: '🫳🏽', name: '双手 中等肤色' },
          { emoj: '🫳🏾', name: '双手 中黑肤色' },
          { emoj: '🫳🏿', name: '双手 深色肤色' },
        ]
      },
      {
        name: '手与部分手指',
        children: [
          { emoj: '👌', name: '好的手' },
          { emoj: '👌🏻', name: '好的手 浅肤色' },
          { emoj: '👌🏼', name: '好的手 中浅肤色' },
          { emoj: '👌🏽', name: '好的手 中等肤色' },
          { emoj: '👌🏾', name: '好的手 中黑肤色' },
          { emoj: '👌🏿', name: '好的手 深色肤色' },
          { emoj: '🤌', name: '捏手指' },
          { emoj: '🤌🏻', name: '捏手指 浅肤色' },
          { emoj: '🤌🏼', name: '捏手指 中浅肤色' },
          { emoj: '🤌🏽', name: '捏手指 中等肤色' },
          { emoj: '🤌🏾', name: '捏手指 中黑肤色' },
          { emoj: '🤌🏿', name: '捏手指 深色肤色' },
          { emoj: '🤏', name: '捏手' },
          { emoj: '🤏🏻', name: '捏手 浅肤色' },
          { emoj: '🤏🏼', name: '捏手 中浅肤色' },
          { emoj: '🤏🏽', name: '捏手 中等肤色' },
          { emoj: '🤏🏾', name: '捏手 中黑肤色' },
          { emoj: '🤏🏿', name: '捏手 深色肤色' },
          { emoj: '✌️', name: '胜利之手' },
          { emoj: '✌', name: '胜利之手' },
          { emoj: '✌🏻', name: '胜利之手 浅肤色' },
          { emoj: '✌🏼', name: '胜利之手 中浅肤色' },
          { emoj: '✌🏽', name: '胜利之手 中等肤色' },
          { emoj: '✌🏾', name: '胜利之手 中黑肤色' },
          { emoj: '✌🏿', name: '胜利之手 深色肤色' },
          { emoj: '🤞', name: '交叉手指' },
          { emoj: '🤞🏻', name: '交叉手指 浅肤色' },
          { emoj: '🤞🏼', name: '交叉手指 中浅肤色' },
          { emoj: '🤞🏽', name: '交叉手指 中等肤色' },
          { emoj: '🤞🏾', name: '交叉手指 中黑肤色' },
          { emoj: '🤞🏿', name: '交叉手指 深色肤色' },
          { emoj: '🫰', name: '食指和拇指交叉的手' },
        ]
      },
      {
        name: '手与单个手指',
        children: [
          { emoj: '👈', name: '反手食指指向左侧' },
          { emoj: '👈🏻', name: '反手食指指向左侧 浅肤色' },
          { emoj: '👈🏼', name: '反手食指指向左侧 中浅肤色' },
          { emoj: '👈🏽', name: '反手食指指向左侧 中等肤色' },
          { emoj: '👈🏾', name: '反手食指指向左侧 中黑肤色' },
          { emoj: '👈🏿', name: '反手食指指向左侧 深色肤色' },
          { emoj: '👉', name: '反手食指指向右侧' },
          { emoj: '👉🏻', name: '反手食指指向右侧 浅肤色' },
          { emoj: '👉🏼', name: '反手食指指向右侧 中浅肤色' },
          { emoj: '👉🏽', name: '反手食指指向右侧 中等肤色' },
          { emoj: '👉🏾', name: '反手食指指向右侧 中黑肤色' },
          { emoj: '👉🏿', name: '反手食指指向右侧 深色肤色' },
          { emoj: '👆', name: '反手指数向上' },
          { emoj: '👆🏻', name: '反手指数向上 浅肤色' },
          { emoj: '👆🏼', name: '反手指数向上 中浅肤色' },
          { emoj: '👆🏽', name: '反手指数向上 中等肤色' },
          { emoj: '👆🏾', name: '反手指数向上 中黑肤色' },
          { emoj: '👆🏿', name: '反手指数向上 深色肤色' },
          { emoj: '🖕', name: '中指' },
          { emoj: '🖕🏻', name: '中指 浅肤色' },
          { emoj: '🖕🏼', name: '中指 中浅肤色' },
          { emoj: '🖕🏽', name: '中指 中等肤色' },
          { emoj: '🖕🏾', name: '中指 中黑肤色' },
          { emoj: '🖕🏿', name: '中指 深色肤色' },
          { emoj: '👇', name: '反手指数朝下' },
          { emoj: '👇🏻', name: '反手指数朝下 浅肤色' },
          { emoj: '👇🏼', name: '反手指数朝下 中浅肤色' },
          { emoj: '👇🏽', name: '反手指数朝下 中等肤色' },
          { emoj: '👇🏾', name: '反手指数朝下 中黑肤色' },
          { emoj: '👇🏿', name: '反手指数朝下 深色肤色' },
          { emoj: '☝️', name: '索引向上' },
          { emoj: '🫴', name: '拇指' },
          { emoj: '🫴🏻', name: '拇指 浅肤色' },
          { emoj: '🫴🏼', name: '拇指 中浅肤色' },
          { emoj: '🫴🏽', name: '拇指 中等肤色' },
          { emoj: '🫴🏾', name: '拇指 中黑肤色' },
          { emoj: '🫴🏿', name: '拇指 深色肤色' }

        ]
      },
      {
        name: '手与手指合拢',
        children: [
          { emoj: '👍', name: '竖起大拇指' },
          { emoj: '👍🏻', name: '竖起大拇指 浅肤色' },
          { emoj: '👍🏼', name: '竖起大拇指 中浅肤色' },
          { emoj: '👍🏽', name: '竖起大拇指 中等肤色' },
          { emoj: '👍🏾', name: '竖起大拇指 中黑肤色' },
          { emoj: '👍🏿', name: '竖起大拇指 深色肤色' },
          { emoj: '👎', name: '不看好' },
          { emoj: '👎🏻', name: '不看好 浅肤色' },
          { emoj: '👎🏼', name: '不看好 中浅肤色' },
          { emoj: '👎🏽', name: '不看好 中等肤色' },
          { emoj: '👎🏾', name: '不看好 中黑肤色' },
          { emoj: '👎🏿', name: '不看好 深色肤色' },
          { emoj: '✊', name: '拳头' },
          { emoj: '✊🏻', name: '拳头 浅肤色' },
          { emoj: '✊🏼', name: '拳头 中浅肤色' },
          { emoj: '✊🏽', name: '拳头 中等肤色' },
          { emoj: '✊🏾', name: '拳头 中黑肤色' },
          { emoj: '✊🏿', name: '拳头 深色肤色' },
          { emoj: '👊', name: '迎面而来的拳头' },
          { emoj: '👊🏻', name: '迎面而来的拳头 浅肤色' },
          { emoj: '👊🏼', name: '迎面而来的拳头 中浅肤色' },
          { emoj: '👊🏽', name: '迎面而来的拳头 中等肤色' },
          { emoj: '👊🏾', name: '迎面而来的拳头 中黑肤色' },
          { emoj: '👊🏿', name: '迎面而来的拳头 深色肤色' },
          { emoj: '🤛', name: '向左握拳' },
          { emoj: '🤛🏻', name: '向左握拳 浅肤色' },
          { emoj: '🤛🏼', name: '向左握拳 中浅肤色' },
          { emoj: '🤛🏽', name: '向左握拳 中等肤色' },
          { emoj: '🤛🏾', name: '向左握拳 中黑肤色' },
          { emoj: '🤛🏿', name: '向左握拳 深色肤色' },
          { emoj: '🤜', name: '向右握拳' },
          { emoj: '🤜🏻', name: '向右握拳 浅肤色' },
          { emoj: '🤜🏼', name: '向右握拳 中浅肤色' },
          { emoj: '🤜🏽', name: '向右握拳 中等肤色' },
          { emoj: '🤜🏾', name: '向右握拳 中黑肤色' },
          { emoj: '🤜🏿', name: '向右握拳 深色肤色' }
        ]
      },
      {
        name: '双手',
        children: [
          { emoj: '👏', name: '拍手' },
          { emoj: '👏🏻', name: '拍手 浅肤色' },
          { emoj: '👏🏼', name: '拍手 中浅肤色' },
          { emoj: '👏🏽', name: '拍手 中等肤色' },
          { emoj: '👏🏾', name: '拍手 中黑肤色' },
          { emoj: '👏🏿', name: '拍手 深色肤色' },
          { emoj: '🙌', name: '举手' },
          { emoj: '🙌🏻', name: '举手 浅肤色' },
          { emoj: '🙌🏼', name: '举手 中浅肤色' },
          { emoj: '🙌🏽', name: '举手 中等肤色' },
          { emoj: '🙌🏾', name: '举手 中黑肤色' },
          { emoj: '🙌🏿', name: '举手 深色肤色' },
          { emoj: '🫶', name: '心形手' },
          { emoj: '🫶🏻', name: '心形手 浅肤色' },
          { emoj: '🫶🏼', name: '心形手 中浅肤色' },
          { emoj: '🫶🏽', name: '心形手 中等肤色' },
          { emoj: '🫶🏾', name: '心形手 中黑肤色' },
          { emoj: '🫶🏿', name: '心形手 深色肤色' },
          { emoj: '👐', name: '张开双手' },
          { emoj: '👐🏻', name: '张开双手 浅肤色' },
          { emoj: '👐🏼', name: '张开双手 中浅肤色' },
          { emoj: '👐🏽', name: '张开双手 中等肤色' },
          { emoj: '👐🏾', name: '张开双手 中黑肤色' },
          { emoj: '👐🏿', name: '张开双手 深色肤色' },
          { emoj: '🤲', name: '手掌向上并拢' },
          { emoj: '🤲🏻', name: '手掌向上并拢 浅肤色' },
          { emoj: '🤲🏼', name: '手掌向上并拢 中浅肤色' },
          { emoj: '🤲🏽', name: '手掌向上并拢 中等肤色' },
          { emoj: '🤲🏾', name: '手掌向上并拢 中黑肤色' },
          { emoj: '🤲🏿', name: '手掌向上并拢 深色肤色' },
          { emoj: '🤝', name: '握手' },
          { emoj: '🤝🏻', name: '握手 浅肤色' },
          { emoj: '🤝🏼', name: '握手 中浅肤色' },
          { emoj: '🤝🏽', name: '握手 中等肤色' },
          { emoj: '🤝🏾', name: '握手 中黑肤色' },
          { emoj: '🤝🏿', name: '握手 深色肤色' },
        ]
      },
      {
        name: '手与道具',
        children: [
          { emoj: '✍️', name: '写字的手' },
          { emoj: '✍🏻', name: '写字的手 浅肤色' },
          { emoj: '✍🏼', name: '写字的手 中浅肤色' },
          { emoj: '✍🏽', name: '写字的手 中等肤色' },
          { emoj: '✍🏾', name: '写字的手 中黑肤色' },
          { emoj: '✍🏿', name: '写字的手 深色肤色' },
          { emoj: '💅', name: '指甲油' },
          { emoj: '💅🏻', name: '指甲油 浅肤色' },
          { emoj: '💅🏼', name: '指甲油 中浅肤色' },
          { emoj: '💅🏽', name: '指甲油 中等肤色' },
          { emoj: '💅🏾', name: '指甲油 中黑肤色' },
          { emoj: '💅🏿', name: '指甲油 深色肤色' },
          { emoj: '🤳', name: '自拍' },
          { emoj: '🤳🏻', name: '自拍 浅肤色' },
          { emoj: '🤳🏼', name: '自拍 中浅肤色' },
          { emoj: '🤳🏽', name: '自拍 中等肤色' },
          { emoj: '🤳🏾', name: '自拍 中黑肤色' },
          { emoj: '🤳🏿', name: '自拍 深色肤色' },
        ]
      },
      {
        name: '身体与部位',
        children: [
          { emoj: '💪', name: '弯曲的二头肌' },
          { emoj: '💪🏻', name: '弯曲的二头肌 浅肤色' },
          { emoj: '💪🏼', name: '弯曲的二头肌 中浅肤色' },
          { emoj: '💪🏽', name: '弯曲的二头肌 中等肤色' },
          { emoj: '💪🏾', name: '弯曲的二头肌 中黑肤色' },
          { emoj: '💪🏿', name: '弯曲的二头肌 深色肤色' },
          { emoj: '🦾', name: '机械臂' },
          { emoj: '🦿', name: '机械腿' },
          { emoj: '🦵', name: '腿' },
          { emoj: '🦵🏻', name: '腿 浅肤色' },
          { emoj: '🦵🏼', name: '腿 中浅肤色' },
          { emoj: '🦵🏽', name: '腿 中等肤色' },
          { emoj: '🦵🏾', name: '腿 中黑肤色' },
          { emoj: '🦵🏿', name: '腿 深色肤色' },
          { emoj: '🦶', name: '脚' },
          { emoj: '🦶🏻', name: '脚 浅肤色' },
          { emoj: '🦶🏼', name: '脚 中浅肤色' },
          { emoj: '🦶🏽', name: '脚 中等肤色' },
          { emoj: '🦶🏾', name: '脚 中黑肤色' },
          { emoj: '🦶🏿', name: '脚 深色肤色' },
          { emoj: '👂', name: '耳朵' },
          { emoj: '👂🏻', name: '耳朵 浅肤色' },
          { emoj: '👂🏼', name: '耳朵 中浅肤色' },
          { emoj: '👂🏽', name: '耳朵 中等肤色' },
          { emoj: '👂🏾', name: '耳朵 中黑肤色' },
          { emoj: '👂🏿', name: '耳朵 深色肤色' },
          { emoj: '🦻', name: '带助听器的耳朵' },
          { emoj: '🦻🏻', name: '带助听器的耳朵 浅肤色' },
          { emoj: '🦻🏼', name: '带助听器的耳朵 中浅肤色' },
          { emoj: '🦻🏽', name: '带助听器的耳朵 中等肤色' },
          { emoj: '🦻🏾', name: '带助听器的耳朵 中黑肤色' },
          { emoj: '🦻🏿', name: '带助听器的耳朵 深色肤色' },
        ]
      },
      {
        name: '人物',
        children: [
          { emoj: '👶', name: '婴儿' },
          { emoj: '👶🏻', name: '婴儿 浅肤色' },
          { emoj: '👶🏼', name: '婴儿 中浅肤色' },
          { emoj: '👶🏽', name: '婴儿 中等肤色' },
          { emoj: '👶🏾', name: '婴儿 中黑肤色' },
          { emoj: '👶🏿', name: '婴儿 深色肤色' },
          { emoj: '🧒', name: '孩子' },
          { emoj: '🧒🏻', name: '孩子 浅肤色' },
          { emoj: '🧒🏼', name: '孩子 中浅肤色' },
          { emoj: '🧒🏽', name: '孩子 中等肤色' },
          { emoj: '🧒🏾', name: '孩子 中黑肤色' },
          { emoj: '🧒🏿', name: '孩子 深色肤色' },
          { emoj: '👦', name: '男生' },
          { emoj: '👦🏻', name: '男生 浅肤色' },
          { emoj: '👦🏼', name: '男生 中浅肤色' },
          { emoj: '👦🏽', name: '男生 中等肤色' },
          { emoj: '👦🏾', name: '男生 中黑肤色' },
          { emoj: '👦🏿', name: '男生 深色肤色' },
          { emoj: '👧', name: '女生' },
          { emoj: '👧🏻', name: '女生 浅肤色' },
          { emoj: '👧🏼', name: '女生 中浅肤色' },
          { emoj: '👧🏽', name: '女生 中等肤色' },
          { emoj: '👧🏾', name: '女生 中黑肤色' },
          { emoj: '👧🏿', name: '女生 深色肤色' },
          { emoj: '🧑', name: '人' },
          { emoj: '🧑🏻', name: '人 浅肤色' },
          { emoj: '🧑🏼', name: '人 中浅肤色' },
          { emoj: '🧑🏽', name: '人 中等肤色' },
          { emoj: '🧑🏾', name: '人 中黑肤色' },
          { emoj: '🧑🏿', name: '人 深色肤色' },
          { emoj: '👱', name: '男人' },
          { emoj: '👱🏻', name: '男人 浅肤色' },
          { emoj: '👱🏼', name: '男人 中浅肤色' },
          { emoj: '👱🏽', name: '男人 中等肤色' },
          { emoj: '👱🏾', name: '男人 中黑肤色' },
          { emoj: '👱🏿', name: '男人 深色肤色' },
          { emoj: '👱', name: 'blond hair' },
          { emoj: '👱🏻', name: 'blond hair 浅肤色' },
          { emoj: '👱🏼', name: 'blond hair 中浅肤色' },
          { emoj: '👱🏽', name: 'blond hair 中等肤色' },
          { emoj: '👱🏾', name: 'blond hair 中黑肤色' },
          { emoj: '👱🏿', name: 'blond hair 深色肤色' },
        ]
      }
    ]
  }
]
