import { ItemType } from '../interface';

export const emojItems: ItemType[] = [
  {
    name: '笑脸与情感的表情符号',
    children: [
      { emoj: '😀', name: '笑脸' },
      { emoj: '😃', name: '笑脸大眼睛' },
      { emoj: '😄', name: '笑脸和微笑的眼睛' },
      { emoj: '😁', name: '脸上带着微笑的眼睛' },
      { emoj: '😆', name: '眯着眼睛笑的脸' },
      { emoj: '😅', name: '满脸汗水的笑脸' },
      { emoj: '🤣', name: '笑得在地上打滚' },
      { emoj: '😂', name: '满脸喜悦的泪水' },
      { emoj: '🙂', name: '微微微笑的脸' },
      { emoj: '🙃', name: '颠倒的脸' },
      { emoj: '🫠', name: '融化的脸' },
      { emoj: '😉', name: '眨眼的脸' },
      { emoj: '😊', name: '微笑的脸和微笑的眼睛' },
      { emoj: '😇', name: '带光环的笑脸' },
      { emoj: '🥰', name: '笑脸与心' },
      { emoj: '😍', name: '心形眼睛的笑脸' },
      { emoj: '🤩', name: '追星的' },
      { emoj: '😘', name: '脸飞吻' },
      { emoj: '😗', name: '亲吻脸' },
      { emoj: '☺️', name: '微笑的面孔' },
      { emoj: '☺', name: '微笑的面孔' },
      { emoj: '😚', name: '闭着眼睛亲吻脸' },
      { emoj: '😙', name: '带着微笑的眼睛亲吻脸' },
      { emoj: '🥲', name: '含着泪水的笑脸' },
      { emoj: '😋', name: '品尝食物的脸' },
      { emoj: '😛', name: '用舌头面对' },
      { emoj: '😜', name: '用舌头眨眼的脸' },
      { emoj: '🤪', name: '滑稽的脸' },
      { emoj: '😝', name: '用舌头眯着脸' },
      { emoj: '🤑', name: '钱嘴脸' },
      { emoj: '🤗', name: '张开双手微笑的脸' },
      { emoj: '🤭', name: '用手捂住嘴脸' },
      { emoj: '🫢', name: '睁开眼睛并用手捂住嘴' },
      { emoj: '🫣', name: '脸上有偷看的眼睛' },
      { emoj: '🤫', name: '嘘脸' },
      { emoj: '🤔', name: '思考的脸' },
      { emoj: '🫡', name: '敬礼的脸' },
      { emoj: '🤐', name: '拉链嘴脸' },
      { emoj: '🤨', name: '扬眉的脸' },
      { emoj: '😐', name: '中性面孔' },
      { emoj: '😑', name: '面无表情' },
      { emoj: '😶', name: '没有嘴的脸' },
      { emoj: '🫥', name: '虚线面' },
      { emoj: '😶‍🌫️', name: '云中的脸' },
      { emoj: '😏', name: '傻笑的脸' },
      { emoj: '😒', name: '不高兴的脸' },
      { emoj: '🙄', name: '翻白眼的脸' },
      { emoj: '😬', name: '鬼脸' },
      { emoj: '😮‍💨', name: '面部呼气' },
      { emoj: '🤥', name: '说谎的脸' },
      { emoj: '🫨', name: '摇脸' },
      { emoj: '😌', name: '释然的脸' },
      { emoj: '😔', name: '沉思的脸' },
      { emoj: '😪', name: '困倦的脸' },
      { emoj: '🤤', name: '流口水的脸' },
      { emoj: '😴', name: '睡脸' },
      { emoj: '😷', name: '带着医用口罩的脸' },
      { emoj: '🤒', name: '带温度计的脸' },
      { emoj: '🤕', name: '头上缠着绷带的脸' },
      { emoj: '🤢', name: '恶心的脸' },
      { emoj: '🤮', name: '脸部呕吐' },
      { emoj: '🤧', name: '打喷嚏的脸' },
      { emoj: '🥵', name: '脸热' },
      { emoj: '🥶', name: '冷脸' },
      { emoj: '🥴', name: '昏昏沉沉的脸' },
      { emoj: '😵', name: '交叉眼睛的脸' },
      { emoj: '😵‍💫', name: '螺旋形眼睛的脸' },
      { emoj: '🤯', name: '爆炸头' },
      { emoj: '🤠', name: '牛仔帽脸' },
      { emoj: '🥳', name: '派对脸' },
      { emoj: '🥸', name: '伪装的脸' },
      { emoj: '😎', name: '戴着墨镜的笑脸' },
      { emoj: '🤓', name: '书呆子脸' },
      { emoj: '🧐', name: '带单片眼镜的脸' },
      { emoj: '😕', name: '困惑的脸' },
      { emoj: '🫤', name: '斜嘴脸' },
      { emoj: '😟', name: '担心的脸' },
      { emoj: '🙁', name: '微微皱眉的脸' },
      { emoj: '☹️', name: '皱眉的脸' },
      { emoj: '☹', name: '皱眉的脸' },
      { emoj: '😮', name: '张开嘴的脸' },
      { emoj: '😯', name: '安静的脸' },
      { emoj: '😲', name: '惊讶的脸' },
      { emoj: '😳', name: '脸红了' },
      { emoj: '🥺', name: '恳求的脸' },
      { emoj: '🥹', name: '强忍着泪水的脸' },
      { emoj: '😦', name: '张开嘴皱着眉头' },
      { emoj: '😧', name: '痛苦的脸' },
      { emoj: '😨', name: '恐惧的脸' },
      { emoj: '😰', name: '满脸焦急满头大汗' },
      { emoj: '😥', name: '悲伤但如释重负的脸' },
      { emoj: '😢', name: '哭泣的脸' },
      { emoj: '😭', name: '大声哭泣的脸' },
      { emoj: '😱', name: '脸上因恐惧而尖叫' },
      { emoj: '😖', name: '困惑的脸' },
      { emoj: '😣', name: '坚忍的脸' },
      { emoj: '😞', name: '失望的脸' },
      { emoj: '😓', name: '满脸汗水低垂的脸' },
      { emoj: '😩', name: '疲倦的脸' },
      { emoj: '😫', name: '疲惫的脸' },
      { emoj: '🥱', name: '打呵欠的脸' },
      { emoj: '😤', name: '鼻子里冒着蒸汽的脸' },
      { emoj: '😡', name: '愤怒的脸' },
      { emoj: '😠', name: '愤怒的脸' },
      { emoj: '🤬', name: '嘴上有符号的脸' },
      { emoj: '😈', name: '带角的笑脸' },
      { emoj: '👿', name: '有角的愤怒的脸' },
      { emoj: '💀', name: '颅骨' },
      { emoj: '☠️', name: '骷髅和交叉骨' },
      { emoj: '☠', name: '骷髅和交叉骨' },
      { emoj: '💩', name: '一堆便便' },
      { emoj: '🤡', name: '小丑脸' },
      { emoj: '👹', name: '食人魔' },
      { emoj: '👺', name: '妖精' },
      { emoj: '👻', name: '鬼' },
      { emoj: '👽', name: '外星人' },
      { emoj: '👾', name: '外星怪物' },
      { emoj: '🤖', name: '机器人' },
      { emoj: '😺', name: '咧着嘴笑的猫' },
      { emoj: '😸', name: '微笑的猫，带着微笑的眼睛' },
      { emoj: '😹', name: '猫流着喜悦的泪水' },
      { emoj: '😻', name: '心形眼睛微笑的猫' },
      { emoj: '😼', name: '苦笑的猫' },
      { emoj: '😽', name: '接吻猫' },
      { emoj: '🙀', name: '疲倦的猫' },
      { emoj: '😿', name: '哭泣的猫' },
      { emoj: '😾', name: '撅嘴的猫' },
      { emoj: '🙈', name: '无恶不作的猴子' },
      { emoj: '🙉', name: '不闻不问的猴子' },
      { emoj: '🙊', name: '不说邪恶的猴子' },
      { emoj: '💌', name: '爱情信' },
      { emoj: '💘', name: '带箭头的心' },
      { emoj: '💝', name: '带丝带的心' },
      { emoj: '💖', name: '闪闪发光的心' },
      { emoj: '💗', name: '成长的心' },
      { emoj: '💓', name: '跳动的心' },
      { emoj: '💞', name: '旋转的心' },
      { emoj: '💕', name: '两颗心' },
      { emoj: '💟', name: '心形装饰' },
      { emoj: '❣️', name: '心中感叹' },
      { emoj: '❣', name: '心中感叹' },
      { emoj: '💔', name: '破碎的心' },
      { emoj: '❤️‍🔥', name: '心脏着火' },
      { emoj: '❤️‍🩹', name: '修补心' },
      { emoj: '❤️', name: '红心' },
      { emoj: '❤', name: '红心' },
      { emoj: '🩷', name: '粉红色的心' },
      { emoj: '🧡', name: '橙色的心' },
      { emoj: '💛', name: '黄心' },
      { emoj: '💚', name: '绿心' },
      { emoj: '💙', name: '蓝色的心' },
      { emoj: '🩵', name: '淡蓝色的心' },
      { emoj: '💜', name: '紫心的心' },
      { emoj: '🤎', name: '棕色的心' },
      { emoj: '🖤', name: '黑心' },
      { emoj: '🩶', name: '灰色的心' },
      { emoj: '🤍', name: '白心' },
      { emoj: '💋', name: '吻痕' },
      { emoj: '💯', name: '百分' },
      { emoj: '💢', name: '愤怒的象征' },
      { emoj: '💥', name: '碰撞' },
      { emoj: '💦', name: '汗滴' },
      { emoj: '💨', name: '匆匆而去' },
      { emoj: '🕳️', name: '洞' },
      { emoj: '💬', name: '语音气球' },
      { emoj: '👁️‍🗨️', name: '讲话泡泡中的眼睛' },
      { emoj: '🗨️', name: '左边的语音气泡' },
      { emoj: '🗯️', name: '右愤怒泡沫' },
      { emoj: '💭', name: '思想气球' },
      { emoj: '💤', name: 'ZZZ' },
    ]
  },
  {
    name: '人物与身体的表情符号',
    children: [
      { emoj: '👋', name: '挥手' },
      { emoj: '🤚', name: '举起手背' },
      { emoj: '🖐', name: '手指张开的手' },
      { emoj: '✋', name: '举起手' },
      { emoj: '🖖', name: '瓦肯敬礼' },
      { emoj: '🫱', name: '右手' },
      { emoj: '🫲', name: '左手' },
      { emoj: '🫳', name: '双手' },
      { emoj: '👌', name: '好的手' },
      { emoj: '🤌', name: '捏手指' },
      { emoj: '🤏', name: '捏手' },
      { emoj: '✌️', name: '胜利之手' },
      { emoj: '🤞', name: '交叉手指' },
      { emoj: '🫰', name: '食指和拇指交叉的手' },
      { emoj: '👈', name: '反手食指指向左侧' },
      { emoj: '👉', name: '反手食指指向右侧' },
      { emoj: '👆', name: '反手指数向上' },
      { emoj: '🖕', name: '中指' },
      { emoj: '👇', name: '反手指数朝下' },
      { emoj: '☝️', name: '索引向上' },
      { emoj: '🫴', name: '拇指' },
      { emoj: '👍', name: '竖起大拇指' },
      { emoj: '👎', name: '不看好' },
      { emoj: '✊', name: '拳头' },
      { emoj: '👊', name: '迎面而来的拳头' },
      { emoj: '🤛', name: '向左握拳' },
      { emoj: '🤜', name: '向右握拳' },
      { emoj: '👏', name: '拍手' },
      { emoj: '🙌', name: '举手' },
      { emoj: '🫶', name: '心形手' },
      { emoj: '👐', name: '张开双手' },
      { emoj: '🤲', name: '手掌向上并拢' },
      { emoj: '🤝', name: '握手' },
      { emoj: '✍️', name: '写字的手' },
      { emoj: '💅', name: '指甲油' },
      { emoj: '🤳', name: '自拍' },
      { emoj: '💪', name: '弯曲的二头肌' },
      { emoj: '🦾', name: '机械臂' },
      { emoj: '🦿', name: '机械腿' },
      { emoj: '🦵', name: '腿' },
      { emoj: '🦶', name: '脚' },
      { emoj: '👂', name: '耳朵' },
      { emoj: '🦻', name: '带助听器的耳朵' },
      { emoj: '👶', name: '婴儿' },
      { emoj: '🧒', name: '孩子' },
      { emoj: '👦', name: '男生' },
      { emoj: '👧', name: '女生' },
      { emoj: '🧑', name: '人' },
      { emoj: '👱', name: '男人' },
      { emoj: '👱', name: 'blond hair' },
      { emoj: "🙍", "name": "皱眉的人" },
      { emoj: "🙍‍♂", "name": "男人皱眉" },
      { emoj: "🙍‍♀️", "name": "女人皱眉" },
      { emoj: "🙎", "name": "撅嘴的人" },
      { emoj: "🙎‍♂️", "name": "男人撅嘴" },
      { emoj: "🙎‍♀️", "name": "女人撅嘴" },
      { emoj: "🙅", "name": "打手势“不”的人" },
      { emoj: "🙅‍♂", "name": "男人打手势“不”" },
      { emoj: "🙅‍♀", "name": "女人打手势“不”" },
      { emoj: "🧑‍⚕️", "name": "卫生工作者" },
      { emoj: "👨‍⚕️", "name": "男子健康工作者" },
      { emoj: "👩‍⚕️", "name": "女卫生工作者" },
      { emoj: "🧑‍🎓", "name": "学生" },
      { emoj: "👨‍🎓", "name": "男学生" },
      { emoj: "👩‍🎓", "name": "女学生" },
      { emoj: "🧑‍🏫", "name": "老师" },
      { emoj: "👨‍🏫", "name": "男老师" },
      { emoj: "👩‍🏫", "name": "女老师" },
      { emoj: "🧑‍⚖️", "name": "法官" },
      { emoj: "👨‍⚖️", "name": "男子法官" },
      { emoj: "👩‍⚖️", "name": "女法官" },
      { emoj: "🧑‍🌾", "name": "农民" },
      { emoj: "👨‍🌾", "name": "农夫" },
      { emoj: "👩‍🌾", "name": "农妇" },
      { emoj: "🧑‍🍳", "name": "厨师" },
      { emoj: "👨‍🍳", "name": "男厨师" },
      { emoj: "👩‍🍳", "name": "女厨师" },
      { emoj: "🧑‍🔧", "name": "技工" },
      { emoj: "👨‍🔧", "name": "男技工" },
      { emoj: "👩‍🔧", "name": "女技工" },
      { emoj: "🧑‍🏭", "name": "工人" },
      { emoj: "👨‍🏭", "name": "男工人" },
      { emoj: "👩‍🏭", "name": "女工人" },
      { emoj: "🧑‍💼", "name": "白领" },
      { emoj: "👨‍💼", "name": "男白领" },
      { emoj: "👩‍💼", "name": "女白领" },
      { emoj: "🧑‍🔬", "name": "科学家" },
      { emoj: "👨‍🔬", "name": "男科学家" },
      { emoj: "👩‍🔬", "name": "女科学家" },
      { emoj: "🧑‍💻", "name": "程序员" },
      { emoj: "👨‍💻", "name": "男程序员" },
      { emoj: "👩‍💻", "name": "女程序员" },
      { emoj: "🧑‍🎤", "name": "歌手" },
      { emoj: "👨‍🎤", "name": "男歌手" },
      { emoj: "👩‍🎤", "name": "女歌手" },
      { emoj: "🧑‍🎨", "name": "艺术家" },
      { emoj: "👨‍🎨", "name": "男艺术家" },
      { emoj: "👩‍🎨", "name": "女艺术家" },
      { emoj: "🧑‍✈️", "name": "飞行员" },
      { emoj: "👨‍✈️", "name": "男子飞行员" },
      { emoj: "👩‍✈️", "name": "女飞行员" },
      { emoj: "🧑‍🚀", "name": "宇航员" },
      { emoj: "👨‍🚀", "name": "男宇航员" },
      { emoj: "👩‍🚀", "name": "女宇航员" },
      { emoj: "🧑‍🚒", "name": "消防员" },
      { emoj: "👨‍🚒", "name": "男消防员" },
      { emoj: "👩‍🚒", "name": "女消防员" },
      { emoj: "👮", "name": "警察" },
      { emoj: "👮‍♂️", "name": "男警官" },
      { emoj: "👮‍♀️", "name": "女警官" },
      { emoj: "🕵️", "name": "侦探" },
      { emoj: "🕵️‍♂️", "name": "男侦探" },
      { emoj: "🕵️‍♀️", "name": "女侦探" },
      { emoj: "💂", "name": "卫兵" },
      { emoj: "💂‍♂️", "name": "男警卫" },
      { emoj: "💂‍♀️", "name": "女警卫" },
      { emoj: "🥷", "name": "忍者" },
      { emoj: "👷", "name": "建筑工人" },
      { emoj: "👷‍♂️", "name": "男子建筑工人" },
      { emoj: "👷‍♀️", "name": "女建筑工人" },
      { emoj: "🫅", "name": "戴王冠的人" },
      { emoj: "🤴", "name": "王子" },
      { emoj: "👸", "name": "公主" },
      { emoj: "👳", "name": "戴头巾的人" },
      { emoj: "👳‍♂️", "name": "男子戴着头巾" },
      { emoj: "👳‍♀️", "name": "女人戴着头巾" },
      { emoj: "👲", "name": "戴瓜皮帽的人" },
      { emoj: "🧕", "name": "带头饰的女人" },
      { emoj: "🤵", "name": "穿燕尾服的人" },
      { emoj: "🤵‍♂️", "name": "穿礼服的男人" },
      { emoj: "🤵‍♀️", "name": "穿礼服的女人" },
      { emoj: "👰", "name": "戴头纱的人" },
      { emoj: "👰‍♂️", "name": "戴头纱的男人" },
      { emoj: "👰‍♀️", "name": "戴头纱的女人" },
      { emoj: "🤰", "name": "孕妇" },
      { emoj: "🫃", "name": "怀孕的男人" },
      { emoj: "🫄", "name": "怀孕的人" },
      { emoj: "🤱", "name": "母乳喂养" },
      { emoj: "👩‍🍼", "name": "哺乳的女人" },
      { emoj: "👨‍🍼", "name": "哺乳的男人" },
      { emoj: "🧑‍🍼", "name": "哺乳的人" },
      { emoj: "👼", "name": "小天使" },
      { emoj: "🎅", "name": "圣诞老人" },
      { emoj: "🤶", "name": "圣诞奶奶" },
      { emoj: "🧑‍🎄", "name": "圣诞人" },
      { emoj: "🦸", "name": "超级英雄" },
      { emoj: "🦸‍♂️", "name": "男超级英雄" },
      { emoj: "🦸‍♀️", "name": "女超级英雄" },
      { emoj: "🦹", "name": "超级大坏蛋" },
      { emoj: "🦹‍♂️", "name": "男超级反派" },
      { emoj: "🦹‍♀️", "name": "女超级反派" },
      { emoj: "🧙", "name": "法师" },
      { emoj: "🧙‍♂️", "name": "男法师" },
      { emoj: "🧙‍♀️", "name": "女法师" },
      { emoj: "🧚", "name": "精灵" },
      { emoj: "🧚‍♂️", "name": "男仙子" },
      { emoj: "🧚‍♀️", "name": "女仙子" },
      { emoj: "🧛", "name": "吸血鬼" },
      { emoj: "🧛‍♂️", "name": "男吸血鬼" },
      { emoj: "🧛‍♀️", "name": "女吸血鬼" },
      { emoj: "🧜", "name": "人鱼" },
      { emoj: "🧜‍♂️", "name": "男人鱼" },
      { emoj: "🧜‍♀️", "name": "美人鱼" },
      { emoj: "🧝", "name": "小精灵" },
      { emoj: "🧝‍♂️", "name": "男精灵" },
      { emoj: "🧝‍♀️", "name": "女精灵" },
      { emoj: "🧞", "name": "妖怪" },
      { emoj: "🧞‍♂️", "name": "男人精灵" },
      { emoj: "🧞‍♀️", "name": "女人精灵" },
      { emoj: "🧟", "name": "僵尸" },
      { emoj: "🧟‍♂️", "name": "男人僵尸" },
      { emoj: "🧟‍♀️", "name": "女人僵尸" },
      { emoj: "🧌", "name": "穴居巨怪" },
      { emoj: "🧑‍🍼", "name": "哺乳的人" },
      { emoj: "💆", "name": "按摩" },
      { emoj: "💆‍♂️", "name": "男人接受按摩" },
      { emoj: "💆‍♀️", "name": "女人接受按摩" },
      { emoj: "💇", "name": "理发" },
      { emoj: "💇‍♂️", "name": "男人理发" },
      { emoj: "💇‍♀️", "name": "女人理发" },
      { emoj: "🚶", "name": "行人" },
      { emoj: "🚶‍♂️", "name": "男人走路" },
      { emoj: "🚶‍♀️", "name": "女人走路" },
      { emoj: "🧍", "name": "站立者" },
      { emoj: "🧍‍♂️", "name": "男人站立" },
      { emoj: "🧍‍♀️", "name": "女人站立" },
      { emoj: "🧎", "name": "下跪者" },
      { emoj: "🧎‍♂️", "name": "男人跪着" },
      { emoj: "🧎‍♀️", "name": "女人跪着" },
      { emoj: "🧑‍🦯", "name": "拄盲杖的人" },
      { emoj: "👨‍🦯", "name": "拄盲杖的男人" },
      { emoj: "👩‍🦯", "name": "拄盲杖的女人" },
      { emoj: "🧑‍🦼", "name": "坐电动轮椅的人" },
      { emoj: "👨‍🦼", "name": "坐电动轮椅的男人" },
      { emoj: "👩‍🦼", "name": "坐电动轮椅的女人" },
      { emoj: "🧑‍🦽", "name": "坐手动轮椅的人" },
      { emoj: "👨‍🦽", "name": "坐手动轮椅的男人" },
      { emoj: "👩‍🦽", "name": "坐手动轮椅的女人" },
      { emoj: "🏃", "name": "跑步者" },
      { emoj: "🏃‍♂️", "name": "跑步的男人" },
      { emoj: "🏃‍♀️", "name": "跑步的女人" },
      { emoj: "💃", "name": "跳舞的女人" },
      { emoj: "🕺", "name": "跳舞的男人" },
      { emoj: "🕴️", "name": "西装革履的人" },
      { emoj: "👯", "name": "戴兔耳朵的人" },
      { emoj: "👯‍♂️", "name": "戴兔子耳朵的男人们" },
      { emoj: "👯‍♀️", "name": "戴兔子耳朵的女人们" },
      { emoj: "🧖", "name": "蒸房里的人" },
      { emoj: "🧖‍♂️", "name": "蒸汽房间里的男人" },
      { emoj: "🧖‍♀️", "name": "蒸汽房间里的女人" },
      { emoj: "🧗", "name": "攀爬的人" },
      { emoj: "🧗‍♂️", "name": "男子攀爬" },
      { emoj: "🧗‍♀️", "name": "女人攀爬" },
      { emoj: "🤺", "name": "击剑选手" },
      { emoj: "🏇", "name": "赛马" },
      { emoj: "⛷️", "name": "滑雪的人" },
      { emoj: "🏂", "name": "滑雪板" },
      { emoj: "🏌️", "name": "打高尔夫的人" },
      { emoj: "🏌️‍♂️", "name": "男子高尔夫球" },
      { emoj: "🏌️‍♀️", "name": "女子高尔夫球" },
      { emoj: "🏄", "name": "冲浪" },
      { emoj: "🏄‍♂️", "name": "冲浪的男人" },
      { emoj: "🏄‍♀️", "name": "冲浪的女人" },
      { emoj: "🚣", "name": "划艇" },
      { emoj: "🚣‍♂️", "name": "男子划艇" },
      { emoj: "🚣‍♀️", "name": "女子划艇" },
      { emoj: "🏊", "name": "游泳" },
      { emoj: "🏊‍♂️", "name": "游泳的男人" },
      { emoj: "🏊‍♀️", "name": "游泳的女人" },
      { emoj: "⛹️", "name": "玩球" },
      { emoj: "⛹️‍♂️", "name": "拍球的男人" },
      { emoj: "⛹️‍♀️", "name": "拍球的女人" },
      { emoj: "🏋️", "name": "举重" },
      { emoj: "🏋️‍♂️", "name": "男子举重" },
      { emoj: "🏋️‍♀️", "name": "女子举重" },
      { emoj: "🚴", "name": "骑自行车" },
      { emoj: "🚴‍♂️", "name": "骑自行车的男人" },
      { emoj: "🚴‍♀️", "name": "骑自行车的女人" },
      { emoj: "🚵", "name": "骑山地车" },
      { emoj: "🚵‍♂️", "name": "男子山地自行车" },
      { emoj: "🚵‍♀️", "name": "女子山地自行车" },
      { emoj: "🤸", "name": "侧手翻" },
      { emoj: "🤸‍♂️", "name": "男人翻筋斗" },
      { emoj: "🤸‍♀️", "name": "女人翻筋斗" },
      { emoj: "🤼", "name": "摔跤选手" },
      { emoj: "🤼‍♂️", "name": "男子摔跤" },
      { emoj: "🤼‍♀️", "name": "女子摔跤" },
      { emoj: "🤽", "name": "水球" },
      { emoj: "🤽‍♂️", "name": "男子玩水球" },
      { emoj: "🤽‍♀️", "name": "女人玩水球" },
      { emoj: "🤾", "name": "手球" },
      { emoj: "🤾‍♂️", "name": "男子玩手球" },
      { emoj: "🤾‍♀️", "name": "女人玩手球" },
      { emoj: "🤹", "name": "抛接杂耍" },
      { emoj: "🤹‍♂️", "name": "男人玩杂耍" },
      { emoj: "🤹‍♀️", "name": "女人玩杂耍" },
      { emoj: "🧘", "name": "盘腿的人" },
      { emoj: "🧘‍♂️", "name": "打坐的男人" },
      { emoj: "🧘‍♀️", "name": "打坐的女人" },
      { emoj: "🛀", "name": "洗澡的人" },
      { emoj: "🛌", "name": "躺在床上的人" },
      { emoj: '👪', name: '家庭' },
      { emoj: "🧑‍🤝‍🧑", "name": "手拉手的两个人" },
      { emoj: "👭", "name": "手拉手的两个女人" },
      { emoj: "👫", "name": "手拉手的一男一女" },
      { emoj: "👬", "name": "手拉手的两个男人" },
      { emoj: "💏", "name": "亲吻" },
      { emoj: "👩‍❤️‍💋‍👨", "name": "吻：女人和男人" },
      { emoj: "👨‍❤️‍💋‍👨", "name": "亲吻：男人和男人" },
      { emoj: "👩‍❤️‍💋‍👩", "name": "亲吻: 女人和女人" },
      { emoj: "💑", "name": "情侣" },
      { emoj: "👩‍❤️‍👨", "name": "带心的夫妇：女人和男人" },
      { emoj: "👨‍❤️‍👨", "name": "带心的夫妇：男人和男人" },
      { emoj: "👩‍❤️‍👩", "name": "情侣: 女人和女人" },
      { emoj: "👨‍👩‍👦", "name": "家庭: 男人、女人、男孩" },
      { emoj: "👨‍👩‍👧", "name": "家庭: 男人、女人、女孩" },
      { emoj: "👨‍👩‍👧‍👦", "name": "家庭: 男人、女人、女孩、男孩" },
      { emoj: "👨‍👩‍👦‍👦", "name": "家庭: 男人、女人、男孩、男孩" },
      { emoj: "👨‍👩‍👧‍👧", "name": "家庭: 男人、女人、女孩、女孩" },
      { emoj: "👨‍👨‍👦", "name": "家庭: 男人、男人、男孩" },
      { emoj: "👨‍👨‍👧", "name": "家庭: 男人、男人、女孩" },
      { emoj: "👨‍👨‍👧‍👦", "name": "家庭: 男人、男人、女孩、男孩" },
      { emoj: "👨‍👨‍👦‍👦", "name": "家庭: 男人、男人、男孩、男孩" },
      { emoj: "👨‍👨‍👧‍👧", "name": "家庭: 男人、男人、女孩、女孩" },
      { emoj: "👩‍👩‍👦", "name": "家庭: 女人、女人、男孩" },
      { emoj: "👩‍👩‍👧", "name": "家庭: 女人、女人、女孩" },
      { emoj: "👩‍👩‍👧‍👦", "name": "家庭: 女人、女人、女孩、男孩" },
      { emoj: "👩‍👩‍👦‍👦", "name": "家庭: 女人、女人、男孩、男孩" },
      { emoj: "👩‍👩‍👧‍👧", "name": "家庭: 女人、女人、女孩、女孩" },
      { emoj: "👨‍👦", "name": "家庭: 男人、男孩" },
      { emoj: "👨‍👦‍👦", "name": "家庭: 男人、男孩、男孩" },
      { emoj: "👨‍👧", "name": "家庭: 男人、女孩" },
      { emoj: "👨‍👧‍👦", "name": "家庭: 男人、女孩、男孩" },
      { emoj: "👨‍👧‍👧", "name": "家庭: 男人、女孩、女孩" },
      { emoj: "👩‍👦", "name": "家庭: 女人、男孩" },
      { emoj: "👩‍👦‍👦", "name": "家庭: 女人、男孩、男孩" },
      { emoj: "👩‍👧", "name": "家庭: 女人、女孩" },
      { emoj: "👩‍👧‍👦", "name": "家庭: 女人、女孩、男孩" },
      { emoj: "👩‍👧‍👧", "name": "家庭: 女人、女孩、女孩" },
      { emoj: '🗣️', name: '说话的头' },
      { emoj: '👤', name: '半身像的剪影' },
      { emoj: '👥', name: '半身像的剪影' },
      { emoj: '🫂', name: '人们拥抱' },
      { emoj: '👣', name: '脚印' }
    ]
  },
  {
    name: '零件的表情符号',
    children: [
      { emoj: '🏻', name: '浅肤色' },
      { emoj: '🏼', name: '中浅肤色' },
      { emoj: '🏽', name: '中等肤色' },
      { emoj: '🏾', name: '中黑肤色' },
      { emoj: '🏿', name: '深色肤色' },
      { emoj: '🦰', name: '红发' },
      { emoj: '🦱', name: '卷发' },
      { emoj: '🦳', name: '白色的头发' },
      { emoj: '🦲', name: '秃' }
    ]
  },
  {
    name: '动物与自然的表情符号',
    children: [
      { emoj: "🐵", "name": "猴脸" },
      { emoj: "🐒", "name": "猴" },
      { emoj: "🦍", "name": "大猩猩" },
      { emoj: "🦧", "name": "猩猩" },
      { emoj: "🐶", "name": "狗脸" },
      { emoj: "🐕", "name": "狗" },
      { emoj: "🦮", "name": "导盲犬" },
      { emoj: "🐕‍🦺", "name": "服务犬" },
      { emoj: "🐩", "name": "贵宾犬" },
      { emoj: "🐺", "name": "狼" },
      { emoj: "🦊", "name": "狐狸" },
      { emoj: "🦝", "name": "狸" },
      { emoj: "🐱", "name": "猫脸" },
      { emoj: "🐈", "name": "猫" },
      { emoj: "🐈‍⬛", "name": "黑猫" },
      { emoj: "🦁", "name": "狮子" },
      { emoj: "🐯", "name": "虎脸" },
      { emoj: "🐅", "name": "老虎" },
      { emoj: "🐆", "name": "豹" },
      { emoj: "🐴", "name": "马脸" },
      { emoj: "🫎", "name": "驼鹿" },
      { emoj: "🫏", "name": "驴" },
      { emoj: "🐎", "name": "马" },
      { emoj: "🦄", "name": "独角兽" },
      { emoj: "🦓", "name": "斑马" },
      { emoj: "🦌", "name": "鹿" },
      { emoj: "🦬", "name": "野牛" },
      { emoj: "🐮", "name": "牛脸" },
      { emoj: "🐂", "name": "牛" },
      { emoj: "🐃", "name": "水牛" },
      { emoj: "🐄", "name": "奶牛" },
      { emoj: "🐷", "name": "猪脸" },
      { emoj: "🦃", "name": "火鸡" },
      { emoj: "🐔", "name": "鸡" },
      { emoj: "🐓", "name": "公鸡" },
      { emoj: "🐣", "name": "孵化小鸡" },
      { emoj: "🐤", "name": "小鸡" },
      { emoj: "🐥", "name": "正面朝前的小鸡" },
      { emoj: "🐦", "name": "鸟" },
      { emoj: "🐧", "name": "企鹅" },
      { emoj: "🕊️", "name": "鸽子" },
      { emoj: "🦅", "name": "鹰" },
      { emoj: "🦆", "name": "鸭子" },
      { emoj: "🦢", "name": "天鹅" },
      { emoj: "🦉", "name": "猫头鹰" },
      { emoj: "🦤", "name": "渡渡鸟" },
      { emoj: "🪶", "name": "羽毛" },
      { emoj: "🦩", "name": "火烈鸟" },
      { emoj: "🦚", "name": "孔雀" },
      { emoj: "🦜", "name": "鹦鹉" },
      { emoj: "🪽", "name": "翅膀" },
      { emoj: "🐦‍⬛", "name": "黑鸟" },
      { emoj: "🪿", "name": "鹅" },
      { emoj: "🐸", "name": "青蛙" },
      { emoj: "🐊", "name": "鳄鱼" },
      { emoj: "🐢", "name": "龟" },
      { emoj: "🦎", "name": "蜥蜴" },
      { emoj: "🐍", "name": "蛇" },
      { emoj: "🐲", "name": "龙脸" },
      { emoj: "🐉", "name": "龙" },
      { emoj: "🦕", "name": "蜥脚类动物" },
      { emoj: "🦖", "name": "霸王龙" },
      { emoj: "🐳", "name": "喷水鲸" },
      { emoj: "🐋", "name": "鲸" },
      { emoj: "🐬", "name": "海豚" },
      { emoj: "🦭", "name": "海豹" },
      { emoj: "🐟", "name": "鱼" },
      { emoj: "🐠", "name": "热带鱼" },
      { emoj: "🐡", "name": "河豚鱼" },
      { emoj: "🦈", "name": "鲨鱼" },
      { emoj: "🐙", "name": "章鱼" },
      { emoj: "🐚", "name": "螺" },
      { emoj: "🪸", "name": "珊瑚" },
      { emoj: "🪼", "name": "海蜇" },
      { emoj: "🐌", "name": "蜗牛" },
      { emoj: "🦋", "name": "蝴蝶" },
      { emoj: "🐛", "name": "漏洞" },
      { emoj: "🐜", "name": "蚂蚁" },
      { emoj: "🐝", "name": "蜜蜂" },
      { emoj: "🪲", "name": "甲虫" },
      { emoj: "🐞", "name": "瓢虫" },
      { emoj: "🦗", "name": "蟋蟀" },
      { emoj: "🪳", "name": "蟑螂" },
      { emoj: "🕷️", "name": "蜘蛛" },
      { emoj: "🕸️", "name": "蜘蛛网" },
      { emoj: "🦂", "name": "蝎" },
      { emoj: "🦟", "name": "蚊子" },
      { emoj: "🪰", "name": "飞" },
      { emoj: "🪱", "name": "虫" },
      { emoj: "🦠", "name": "微生物" },
      { emoj: "💐", "name": "花束" },
      { emoj: "🌸", "name": "樱花" },
      { emoj: "💮", "name": "白色的花" },
      { emoj: "🪷", "name": "莲花" },
      { emoj: "🏵️", "name": "玫瑰花结" },
      { emoj: "🌹", "name": "玫瑰" },
      { emoj: "🥀", "name": "枯萎的花" },
      { emoj: "🌺", "name": "芙蓉" },
      { emoj: "🌻", "name": "向日葵" },
      { emoj: "🌼", "name": "开花" },
      { emoj: "🌷", "name": "郁金香" },
      { emoj: "🪻", "name": "风信子" },
      { emoj: "🌱", "name": "幼苗" },
      { emoj: "🪴", "name": "盆栽" },
      { emoj: "🌲", "name": "常青树" },
      { emoj: "🌳", "name": "落叶树" },
      { emoj: "🌴", "name": "棕榈树" },
      { emoj: "🌵", "name": "仙人掌" },
      { emoj: "🌾", "name": "一捆米饭" },
      { emoj: "🌿", "name": "草本植物" },
      { emoj: "☘️", "name": "三叶草" },
      { emoj: "☘", "name": "三叶草" },
      { emoj: "🍀", "name": "四叶草" },
      { emoj: "🍁", "name": "枫叶" },
      { emoj: "🍂", "name": "落叶" },
      { emoj: "🍃", "name": "树叶在风中飘扬" },
      { emoj: "🪹", "name": "空巢" },
      { emoj: "🪺", "name": "与蛋筑巢" },
      { emoj: "🍄", "name": "蘑菇" }
    ]
  },
  {
    name: '食物与饮料的表情符号',
    children: [
      { emoj: "🍇", "name": "葡萄" },
      { emoj: "🍈", "name": "瓜" },
      { emoj: "🍉", "name": "西瓜" },
      { emoj: "🍊", "name": "柑橘" },
      { emoj: "🍋", "name": "柠檬" },
      { emoj: "🍌", "name": "香蕉" },
      { emoj: "🍍", "name": "菠萝" },
      { emoj: "🥭", "name": "芒果" },
      { emoj: "🍎", "name": "红苹果" },
      { emoj: "🍏", "name": "青苹果" },
      { emoj: "🍐", "name": "梨" },
      { emoj: "🍑", "name": "桃" },
      { emoj: "🍒", "name": "樱桃" },
      { emoj: "🍓", "name": "草莓" },
      { emoj: "🫐", "name": "蓝莓" },
      { emoj: "🥝", "name": "奇异果" },
      { emoj: "🍅", "name": "番茄" },
      { emoj: "🫒", "name": "橄榄" },
      { emoj: "🥥", "name": "椰子" },
      { emoj: "🥑", "name": "牛油果" },
      { emoj: "🍆", "name": "茄子" },
      { emoj: "🥔", "name": "土豆" },
      { emoj: "🥕", "name": "胡萝卜" },
      { emoj: "🌽", "name": "玉米穗" },
      { emoj: "🌶️", "name": "辣椒" },
      { emoj: "🫑", "name": "灯笼椒" },
      { emoj: "🥒", "name": "黄瓜" },
      { emoj: "🥬", "name": "绿叶" },
      { emoj: "🥦", "name": "西兰花" },
      { emoj: "🧄", "name": "蒜" },
      { emoj: "🧅", "name": "洋葱" },
      { emoj: "🥜", "name": "花生" },
      { emoj: "🫘", "name": "豆子" },
      { emoj: "🌰", "name": "板栗" },
      { emoj: "🫚", "name": "姜根" },
      { emoj: "🫛", "name": "豌豆荚" },
      { emoj: "🍞", "name": "面包" },
      { emoj: "🥐", "name": "羊角面包" },
      { emoj: "🥖", "name": "长棍面包" },
      { emoj: "🫓", "name": "大饼" },
      { emoj: "🥨", "name": "椒盐卷饼" },
      { emoj: "🥯", "name": "百吉饼" },
      { emoj: "🥞", "name": "薄煎饼" },
      { emoj: "🧇", "name": "胡扯" },
      { emoj: "🧀", "name": "奶酪角" },
      { emoj: "🍖", "name": "骨头上的肉" },
      { emoj: "🍗", "name": "家禽腿" },
      { emoj: "🥩", "name": "切肉" },
      { emoj: "🥓", "name": "熏肉" },
      { emoj: "🍔", "name": "汉堡包" },
      { emoj: "🍟", "name": "炸薯条" },
      { emoj: "🍕", "name": "比萨" },
      { emoj: "🌭", "name": "热狗" },
      { emoj: "🥪", "name": "三明治" },
      { emoj: "🌮", "name": "炸玉米饼" },
      { emoj: "🌯", "name": "墨西哥卷饼" },
      { emoj: "🫔", "name": "塔马利" },
      { emoj: "🥙", "name": "酿大饼" },
      { emoj: "🧆", "name": "沙拉三明治" },
      { emoj: "🥚", "name": "蛋" },
      { emoj: "🍳", "name": "烹饪" },
      { emoj: "🥘", "name": "浅盘食物" },
      { emoj: "🍲", "name": "一锅食物" },
      { emoj: "🫕", "name": "火锅" },
      { emoj: "🥣", "name": "带勺子的碗" },
      { emoj: "🥗", "name": "绿色的沙拉" },
      { emoj: "🍿", "name": "爆米花" },
      { emoj: "🧈", "name": "黄油" },
      { emoj: "🍱", "name": "便当盒" },
      { emoj: "🍘", "name": "米果" },
      { emoj: "🍙", "name": "饭团" },
      { emoj: "🍚", "name": "熟米饭" },
      { emoj: "🍛", "name": "咖喱饭" },
      { emoj: "🍜", "name": "蒸碗" },
      { emoj: "🍝", "name": "意大利细面条" },
      { emoj: "🍠", "name": "烤红薯" },
      { emoj: "🍢", "name": "奥登" },
      { emoj: "🍣", "name": "寿司" },
      { emoj: "🍤", "name": "炒虾仁" },
      { emoj: "🍥", "name": "带漩涡的鱼饼" },
      { emoj: "🥮", "name": "月饼" },
      { emoj: "🍡", "name": "团子" },
      { emoj: "🥟", "name": "饺子" },
      { emoj: "🥠", "name": "幸运饼干" },
      { emoj: "🥡", "name": "外卖盒" },
      { emoj: "🦀", "name": "螃蟹" },
      { emoj: "🦞", "name": "龙虾" },
      { emoj: "🦐", "name": "虾" },
      { emoj: "🦑", "name": "乌贼" },
      { emoj: "🦪", "name": "牡蛎" },
      { emoj: "🍦", "name": "软冰淇淋" },
      { emoj: "🍧", "name": "刨冰" },
      { emoj: "🍨", "name": "冰淇淋" },
      { emoj: "🍩", "name": "油炸圈饼" },
      { emoj: "🍪", "name": "曲奇饼" },
      { emoj: "🎂", "name": "生日蛋糕" },
      { emoj: "🍰", "name": "脆饼" },
      { emoj: "🧁", "name": "纸杯蛋糕" },
      { emoj: "🥧", "name": "馅饼" },
      { emoj: "🍫", "name": "巧克力吧" },
      { emoj: "🍬", "name": "糖果" },
      { emoj: "🍭", "name": "棒糖" },
      { emoj: "🍮", "name": "卡仕达酱" },
      { emoj: "🍯", "name": "蜜罐" },
      { emoj: "🍼", "name": "婴儿奶瓶" },
      { emoj: "🥛", "name": "一杯牛奶" },
      { emoj: "☕", "name": "热饮" },
      { emoj: "🫖", "name": "茶壶" },
      { emoj: "🍵", "name": "没有把手的茶杯" },
      { emoj: "🍶", "name": "清酒" },
      { emoj: "🍾", "name": "软木塞爆开的瓶子" },
      { emoj: "🍷", "name": "红酒杯" },
      { emoj: "🍸", "name": "鸡尾酒杯" },
      { emoj: "🍹", "name": "热带饮料" },
      { emoj: "🍺", "name": "啤酒杯" },
      { emoj: "🍻", "name": "叮当作响的啤酒杯" },
      { emoj: "🥂", "name": "叮当作响的眼镜" },
      { emoj: "🥃", "name": "玻璃杯" },
      { emoj: "🫗", "name": "倾倒液体" },
      { emoj: "🥤", "name": "带吸管的杯子" },
      { emoj: "🧋", "name": "珍珠奶茶" },
      { emoj: "🧃", "name": "饮料盒" },
      { emoj: "🧉", "name": "伴侣" },
      { emoj: "🧊", "name": "冰" },
      { emoj: "🥢", "name": "筷子" },
      { emoj: "🍽️", "name": "带盘子的叉子和刀子" },
      { emoj: "🍴", "name": "刀叉" },
      { emoj: "🥄", "name": "勺子" },
      { emoj: "🔪", "name": "菜刀" },
      { emoj: "🫙", "name": "罐" },
      { emoj: "🏺", "name": "双耳瓶" }
    ]
  },
  {
    name: '旅行与地点的表情符号',
    children: [
      { emoj: "🌍", "name": "显示欧洲-非洲的地球仪" },
      { emoj: "🌎", "name": "显示美洲的地球仪" },
      { emoj: "🌏", "name": "显示亚洲-澳大利亚的地球仪" },
      { emoj: "🌐", "name": "有经络的地球仪" },
      { emoj: "🗺️", "name": "世界地图" },
      { emoj: "🗾", "name": "日本地图" },
      { emoj: "🧭", "name": "罗盘" },
      { emoj: "🏔️", "name": "雪山" },
      { emoj: "⛰️", "name": "山" },
      { emoj: "🌋", "name": "火山" },
      { emoj: "🗻", "name": "富士山" },
      { emoj: "🏕️", "name": "野营" },
      { emoj: "🏖️", "name": "带伞的海滩" },
      { emoj: "🏜️", "name": "沙漠" },
      { emoj: "🏝️", "name": "沙漠荒岛" },
      { emoj: "🏞️", "name": "国家公园" },
      { emoj: "🏟️", "name": "体育场" },
      { emoj: "🏛️", "name": "古典建筑" },
      { emoj: "🏗️", "name": "建筑施工" },
      { emoj: "🧱", "name": "砖" },
      { emoj: "🪨", "name": "岩石" },
      { emoj: "🪵", "name": "木头" },
      { emoj: "🛖", "name": "小屋" },
      { emoj: "🏘️", "name": "房屋" },
      { emoj: "🏚️", "name": "废弃的房子" },
      { emoj: "🏠", "name": "房子" },
      { emoj: "🏡", "name": "带花园的房子" },
      { emoj: "🏢", "name": "办公楼" },
      { emoj: "🏣", "name": "日本邮局" },
      { emoj: "🏤", "name": "邮局" },
      { emoj: "🏥", "name": "医院" },
      { emoj: "🏦", "name": "银行" },
      { emoj: "🏨", "name": "酒店" },
      { emoj: "🏩", "name": "爱情酒店" },
      { emoj: "🏪", "name": "便利店" },
      { emoj: "🏫", "name": "学校" },
      { emoj: "🏬", "name": "百货商店" },
      { emoj: "🏭", "name": "工厂" },
      { emoj: "🏯", "name": "日本城堡" },
      { emoj: "🏰", "name": "城堡" },
      { emoj: "💒", "name": "婚礼" },
      { emoj: "🗼", "name": "东京塔" },
      { emoj: "🗽", "name": "自由女神像" },
      { emoj: "⛪", "name": "教会" },
      { emoj: "🕌", "name": "清真寺" },
      { emoj: "🛕", "name": "印度教寺庙" },
      { emoj: "🕍", "name": "犹太教堂" },
      { emoj: "⛩️", "name": "神社" },
      { emoj: "🕋", "name": "天房" },
      { emoj: "⛲", "name": "喷泉" },
      { emoj: "⛺", "name": "帐篷" },
      { emoj: "🌁", "name": "有雾" },
      { emoj: "🌃", "name": "有星星的夜晚" },
      { emoj: "🏙️", "name": "城市景观" },
      { emoj: "🌄", "name": "山上的日出" },
      { emoj: "🌅", "name": "日出" },
      { emoj: "🌆", "name": "黄昏时的城市景观" },
      { emoj: "🌇", "name": "日落" },
      { emoj: "🌉", "name": "晚上的桥" },
      { emoj: "♨️", "name": "温泉" },
      { emoj: "🎠", "name": "旋转木马" },
      { emoj: "🛝", "name": "游乐场滑梯" },
      { emoj: "🎡", "name": "摩天轮" },
      { emoj: "🎢", "name": "过山车" },
      { emoj: "💈", "name": "理发店招牌" },
      { emoj: "🎪", "name": "马戏团帐篷" },
      { emoj: "🚂", "name": "机车" },
      { emoj: "🚃", "name": "火车车厢" },
      { emoj: "🚄", "name": "高速火车" },
      { emoj: "🚅", "name": "子弹头列车" },
      { emoj: "🚆", "name": "火车" },
      { emoj: "🚇", "name": "地铁" },
      { emoj: "🚈", "name": "轻轨" },
      { emoj: "🚉", "name": "车站" },
      { emoj: "🚊", "name": "电车" },
      { emoj: "🚝", "name": "单轨铁路" },
      { emoj: "🚞", "name": "山区铁路" },
      { emoj: "🚋", "name": "有轨电车" },
      { emoj: "🚌", "name": "公共汽车" },
      { emoj: "🚍", "name": "迎面而来的巴士" },
      { emoj: "🚎", "name": "电车" },
      { emoj: "🚐", "name": "小巴" },
      { emoj: "🚑", "name": "救护车" },
      { emoj: "🚒", "name": "消防车" },
      { emoj: "🚓", "name": "警车" },
      { emoj: "🚔", "name": "迎面而来的警车" },
      { emoj: "🚕", "name": "出租车" },
      { emoj: "🚖", "name": "迎面而来的出租车" },
      { emoj: "🚗", "name": "汽车" },
      { emoj: "🚘", "name": "迎面而来的汽车" },
      { emoj: "🚙", "name": "运动型多用途车" },
      { emoj: "🛻", "name": "皮卡车" },
      { emoj: "🚚", "name": "送货卡车" },
      { emoj: "🚛", "name": "铰接式货车" },
      { emoj: "🚜", "name": "拖拉机" },
      { emoj: "🏎️", "name": "赛车" },
      { emoj: "🏍️", "name": "摩托车" },
      { emoj: "⚓", "name": "锚" },
      { emoj: "🛟", "name": "环形浮标" },
      { emoj: "⛵", "name": "帆船" },
      { emoj: "🛶", "name": "独木舟" },
      { emoj: "🚤", "name": "快艇" },
      { emoj: "🛳️", "name": "客船" },
      { emoj: "⛴️", "name": "渡船" },
      { emoj: "🛥️", "name": "摩托艇" },
      { emoj: "🚢", "name": "船" },
      { emoj: "✈️", "name": "飞机" },
      { emoj: "🛫", "name": "飞机起飞" },
      { emoj: "🛬", "name": "飞机到达" },
      { emoj: "🛩️", "name": "小飞机" },
      { emoj: "🪂", "name": "降落伞" },
      { emoj: "💺", "name": "座位" },
      { emoj: "🚁", "name": "直升机" },
      { emoj: "🚟", "name": "悬索铁路" },
      { emoj: "🚠", "name": "山地索道" },
      { emoj: "🚡", "name": "空中缆车" },
      { emoj: "🛰️", "name": "卫星" },
      { emoj: "🚀", "name": "火箭" },
      { emoj: "🛸", "name": "飞碟" },
      { emoj: "🛎️", "name": "侍者铃" },
      { emoj: "🧳", "name": "行李" },
      { emoj: "⌛", "name": "沙漏完成" },
      { emoj: "⏳", "name": "沙漏未完成" },
      { emoj: "⌚", "name": "手表" },
      { emoj: "⏰", "name": "闹钟" },
      { emoj: "⏱️", "name": "跑表" },
      { emoj: "⏲️", "name": "定时器时钟" },
      { emoj: "🕰️", "name": "壁炉台钟" },
      { emoj: "🕛", "name": "12点" },
      { emoj: "🕧", "name": "12点半" },
      { emoj: "🕐", "name": "1点" },
      { emoj: "🕜", "name": "1点半" },
      { emoj: "🕑", "name": "2点" },
      { emoj: "🕝", "name": "2点半" },
      { emoj: "🕒", "name": "3点" },
      { emoj: "🕞", "name": "3点半" },
      { emoj: "🕓", "name": "4点" },
      { emoj: "🕟", "name": "4点半" },
      { emoj: "🕔", "name": "5点" },
      { emoj: "🕠", "name": "5点半" },
      { emoj: "🕕", "name": "6点" },
      { emoj: "🕡", "name": "6点半" },
      { emoj: "🕖", "name": "7点" },
      { emoj: "🕢", "name": "7点半" },
      { emoj: "🕗", "name": "8点" },
      { emoj: "🕣", "name": "8点半" },
      { emoj: "🕘", "name": "9点" },
      { emoj: "🕤", "name": "9点半" },
      { emoj: "🕙", "name": "10点" },
      { emoj: "🕥", "name": "10点半" },
      { emoj: "🌑", "name": "新月" },
      { emoj: "🌒", "name": "峨眉月（初亏月）" },
      { emoj: "🌓", "name": "上弦月" },
      { emoj: "🌔", "name": "盈凸月" },
      { emoj: "🌕", "name": "满月" },
      { emoj: "🌖", "name": "亏凸月" },
      { emoj: "🌗", "name": "下弦月" },
      { emoj: "🌘", "name": "残月" },
      { emoj: "🌙", "name": "弯弯的月亮" },
      { emoj: "🌚", "name": "新月脸" },
      { emoj: "🌛", "name": "上弦月脸" },
      { emoj: "🌜", "name": "下弦月脸" },
      { emoj: "🌡️", "name": "温度计" },
      { emoj: "☀️", "name": "太阳" },
      { emoj: "🌝", "name": "满月脸" },
      { emoj: "🌞", "name": "太阳笑脸" },
      { emoj: "🪐", "name": "环行星" },
      { emoj: "⭐", "name": "星星" },
      { emoj: "🌟", "name": "闪烁的星星" },
      { emoj: "🌠", "name": "流星" },
      { emoj: "🌌", "name": "银河系" },
      { emoj: "☁️", "name": "云" },
      { emoj: "⛅", "name": "太阳和云" },
      { emoj: "⛈️", "name": "雷雨云" },
      { emoj: "🌤️", "name": "阳光穿过小云" },
      { emoj: "🌥️", "name": "太阳在大片云后" },
      { emoj: "🌦️", "name": "太阳在雨云后" },
      { emoj: "🌧️", "name": "下雨的云" },
      { emoj: "🌨️", "name": "下雪的云" },
      { emoj: "🌩️", "name": "闪电的云" },
      { emoj: "🌪️", "name": "龙卷风" },
      { emoj: "🌫️", "name": "雾" },
      { emoj: "🌬️", "name": "风脸" },
      { emoj: "🌀", "name": "漩涡" },
      { emoj: "🌈", "name": "彩虹" },
      { emoj: "🌂", "name": "折叠伞" },
      { emoj: "☂️", "name": "伞" },
      { emoj: "☔", "name": "带雨滴的伞" },
      { emoj: "⛱️", "name": "沙滩伞" },
      { emoj: "⚡", "name": "高压电" },
      { emoj: "❄️", "name": "雪花" },
      { emoj: "☃️", "name": "雪人" },
      { emoj: "⛄", "name": "无雪的雪人" },
      { emoj: "☄️", "name": "彗星" },
      { emoj: "🔥", "name": "火焰" },
      { emoj: "💧", "name": "水滴" },
      { emoj: "🌊", "name": "海浪" }
    ]
  },
  {
    name: '活动的表情符号',
    children: [
      {
        name: '事件',
        children: [
          { emoj: "🎃", "name": "南瓜灯（万圣节）" },
          { emoj: "🎄", "name": "圣诞树" },
          { emoj: "🎆", "name": "大型烟花" },
          { emoj: "🎇", "name": "火花烟花" },
          { emoj: "🧨", "name": "鞭炮" },
          { emoj: "✨", "name": "闪烁星星" },
          { emoj: "🎈", "name": "气球" },
          { emoj: "🎉", "name": "派对礼花筒" },
          { emoj: "🎊", "name": "五彩纸屑球" },
          { emoj: "🎋", "name": "竹饰日式七夕装饰" },
          { emoj: "🎍", "name": "松木新年装饰" },
          { emoj: "🎎", "name": "日本玩偶" },
          { emoj: "🎏", "name": "鲤鱼旗（日本儿童节）" },
          { emoj: "🎐", "name": "风铃" },
          { emoj: "🎑", "name": "赏月活动" },
          { emoj: "🧧", "name": "红包" },
          { emoj: "🎀", "name": "丝带" },
          { emoj: "🎁", "name": "礼物" },
          { emoj: "🎗️", "name": "纪念或提醒丝带" },
          { emoj: "🎟️", "name": "入场券" },
          { emoj: "🎫", "name": "票" }
        ]
      },
      {
        name: '奖项与奖牌',
        children: [
          { emoj: "🎖️", "name": "军事奖章" },
          { emoj: "🏆", "name": "奖杯" },
          { emoj: "🏅", "name": "体育奖牌" },
          { emoj: "🥇", "name": "第一名金牌" },
          { emoj: "🥈", "name": "第二名银牌" },
          { emoj: "🥉", "name": "第三名铜牌" }
        ]
      },
      {
        name: '运动',
        children: [
          { emoj: "⚽", "name": "足球" },
          { emoj: "⚾", "name": "棒球" },
          { emoj: "🥎", "name": "垒球" },
          { emoj: "🏀", "name": "篮球" },
          { emoj: "🏐", "name": "排球" },
          { emoj: "🏈", "name": "美式足球" },
          { emoj: "🏉", "name": "橄榄球" },
          { emoj: "🎾", "name": "网球" },
          { emoj: "🥏", "name": "飞盘" },
          { emoj: "🎳", "name": "保龄球" },
          { emoj: "🏏", "name": "板球比赛" },
          { emoj: "🏑", "name": "曲棍球" },
          { emoj: "🏒", "name": "冰球" },
          { emoj: "🥍", "name": "长曲棍球" },
          { emoj: "🏓", "name": "乒乓球" },
          { emoj: "🏸", "name": "羽毛球" },
          { emoj: "🥊", "name": "拳击手套" },
          { emoj: "🥋", "name": "武术服" },
          { emoj: "🥅", "name": "球门网" },
          { emoj: "⛳", "name": "高尔夫球入洞" },
          { emoj: "⛸️", "name": "滑冰" },
          { emoj: "🎣", "name": "钓鱼竿" },
          { emoj: "🤿", "name": "潜水装备" },
          { emoj: "🎽", "name": "跑步衫" },
          { emoj: "🎿", "name": "滑雪板" },
          { emoj: "🛷", "name": "雪橇" },
          { emoj: "🥌", "name": "冰壶石" }
        ]
      },
      {
        name: '游戏',
        children: [
          { emoj: "🎯", "name": "靶心" },
          { emoj: "🪀", "name": "悠悠球" },
          { emoj: "🪁", "name": "风筝" },
          { emoj: "🔫", "name": "手枪（在此语境下可能指水枪）" },
          { emoj: "🎱", "name": "台球8号球" },
          { emoj: "🔮", "name": "水晶球" },
          { emoj: "🪄", "name": "魔法棒" },
          { emoj: "🎮", "name": "视频游戏控制器" },
          { emoj: "🕹️", "name": "操纵杆" },
          { emoj: "🎰", "name": "老虎机" },
          { emoj: "🎲", "name": "骰子" },
          { emoj: "🧩", "name": "拼图块" },
          { emoj: "🧸", "name": "泰迪熊" },
          { emoj: "🪅", "name": "皮纳塔" },
          { emoj: "🪩", "name": "镜球舞池灯" },
          { emoj: "🪆", "name": "俄罗斯套娃" },
          { emoj: "♠️", "name": "黑桃" },
          { emoj: "♥️", "name": "红心" },
          { emoj: "♦️", "name": "方片" },
          { emoj: "♣️", "name": "梅花" },
          { emoj: "♟️", "name": "国际象棋兵" },
          { emoj: "🃏", "name": "小丑牌" },
          { emoj: "🀄", "name": "麻将牌中的红中" },
          { emoj: "🎴", "name": "日本花札纸牌" }
        ]
      },
      {
        name: '艺术与手工艺',
        children: [
          { emoj: "🎭", "name": "戏剧面具，代表表演艺术" },
          { emoj: "🖼️", "name": "带框的画作" },
          { emoj: "🖼", "name": "带框的画作" },
          { emoj: "🎨", "name": "艺术家的调色板" },
          { emoj: "🧵", "name": "线或细绳" },
          { emoj: "🪡", "name": "缝纫针" },
          { emoj: "🧶", "name": "毛线或纱线" },
          { emoj: "🪢", "name": "绳结" }
        ]
      }
    ]
  },
  {
    name: '物品的表情符号',
    children: [
      {
        name: '服装',
        children: [
          { emoj: "👓", "name": "眼镜" },
          { emoj: "🕶️", "name": "太阳镜" },
          { emoj: "🥽", "name": "护目镜或风镜" },
          { emoj: "🥼", "name": "实验服" },
          { emoj: "🦺", "name": "安全背心" },
          { emoj: "👔", "name": "领带" },
          { emoj: "👕", "name": "T恤衫" },
          { emoj: "👖", "name": "牛仔裤" },
          { emoj: "🧣", "name": "围巾" },
          { emoj: "🧤", "name": "手套" },
          { emoj: "🧥", "name": "外套" },
          { emoj: "🧦", "name": "袜子" },
          { emoj: "👗", "name": "裙子" },
          { emoj: "👘", "name": "和服" },
          { emoj: "🥻", "name": "纱丽" },
          { emoj: "🩱", "name": "连体泳衣" },
          { emoj: "🩲", "name": "男士内裤" },
          { emoj: "🩳", "name": "短裤" },
          { emoj: "👙", "name": "比基尼泳装" },
          { emoj: "👚", "name": "女士服装" },
          { emoj: "🪭", "name": "折扇" },
          { emoj: "👛", "name": "钱包" },
          { emoj: "👜", "name": "手提包" },
          { emoj: "👝", "name": "手抓包" },
          { emoj: "🛍️", "name": "购物袋" },
          { emoj: "🎒", "name": "背包" },
          { emoj: "🩴", "name": "人字拖鞋" },
          { emoj: "👞", "name": "男士鞋子" },
          { emoj: "👟", "name": "跑鞋" },
          { emoj: "🥾", "name": "登山靴" }
        ]
      },
      {
        name: '声音',
        children: [
          { emoj: "🔇", "name": "静音扬声器" },
          { emoj: "🔈", "name": "低音量扬声器" },
          { emoj: "🔉", "name": "中等音量扬声器" },
          { emoj: "🔊", "name": "高音量扬声器" },
          { emoj: "📢", "name": "大声公或公告喇叭" },
          { emoj: "📣", "name": "扩音器" },
          { emoj: "📯", "name": "邮递员的号角" },
          { emoj: "🔔", "name": "钟铃" },
          { emoj: "🔕", "name": "禁止铃声或静音符号" }
        ]
      },
      {
        name: '音乐',
        children: [
          { emoj: "🎼", "name": "乐谱" },
          { emoj: "🎵", "name": "单个音符" },
          { emoj: "🎶", "name": "多个音符" },
          { emoj: "🎙️", "name": "录音室麦克风" },
          { emoj: "🎙", "name": "录音室麦克风" },
          { emoj: "🎚️", "name": "音量控制滑块" },
          { emoj: "🎚", "name": "音量控制滑块" },
          { emoj: "🎛️", "name": "控制面板旋钮" },
          { emoj: "🎛", "name": "控制面板旋钮" },
          { emoj: "🎤", "name": "麦克风" },
          { emoj: "🎧", "name": "耳机" },
          { emoj: "📻", "name": "收音机" }
        ]
      },
      {
        name: '乐器',
        children: [
          { emoj: "🎷", "name": "萨克斯管" },
          { emoj: "🪗", "name": "手风琴" },
          { emoj: "🎸", "name": "吉他" },
          { emoj: "🎹", "name": "电子钢琴或音乐键盘" },
          { emoj: "🎺", "name": "喇叭或小号" },
          { emoj: "🎻", "name": "小提琴" },
          { emoj: "🪕", "name": "班卓琴" },
          { emoj: "🥁", "name": "鼓" },
          { emoj: "🪘", "name": "非洲长鼓或其他大型鼓" },
          { emoj: "🪇", "name": "马拉卡斯（一种拉丁美洲打击乐器）" },
          { emoj: "🪈", "name": "长笛" }
        ]
      },
      {
        name: '手机',
        children: [
          { emoj: "📱", "name": "智能手机" },
          { emoj: "📲", "name": "指向右方的手机，表示接收或拨打电话" },
          { emoj: "☎️", "name": "传统电话" },
          { emoj: "📞", "name": "电话听筒" },
          { emoj: "📟", "name": "寻呼机或BP机" },
          { emoj: "📠", "name": "传真机" }
        ]
      },
      {
        name: '计算机',
        children: [
          { emoj: "🔋", "name": "电池" },
          { emoj: "🪫", "name": "低电量电池" },
          { emoj: "🔌", "name": "电源插头" },
          { emoj: "💻", "name": "笔记本电脑" },
          { emoj: "🖥️", "name": "台式电脑" },
          { emoj: "🖨️", "name": "打印机" },
          { emoj: "⌨", "name": "键盘" },
          { emoj: "🖱️", "name": "电脑鼠标" },
          { emoj: "🖲️", "name": "轨迹球" },
          { emoj: "💽", "name": "迷你光盘（MD）或硬盘图标" },
          { emoj: "💾", "name": "软盘" },
          { emoj: "💿", "name": "光盘" },
          { emoj: "📀", "name": "数字多功能光盘（DVD）" },
          { emoj: "🧮", "name": "算盘" }
        ]
      },
      {
        name: '光与视频',
        children: [
          { emoj: "🎥", "name": "电影摄影机" },
          { emoj: "🎞️", "name": "胶片帧" },
          { emoj: "🎞", "name": "胶片帧" },
          { emoj: "📽️", "name": "电影放映机" },
          { emoj: "🎬", "name": "场记板" },
          { emoj: "📺", "name": "电视机" },
          { emoj: "📷", "name": "相机" },
          { emoj: "📸", "name": "带闪光灯的相机" },
          { emoj: "📹", "name": "摄像机" },
          { emoj: "📼", "name": "录像带" },
          { emoj: "🔍", "name": "向左倾斜的放大镜" },
          { emoj: "🔎", "name": "向右倾斜的放大镜" },
          { emoj: "🕯️", "name": "蜡烛" },
          { emoj: "💡", "name": "灯泡" },
          { emoj: "🔦", "name": "手电筒" },
          { emoj: "🏮", "name": "红纸灯笼" },
          { emoj: "🪔", "name": "迪亚灯（印度油灯）" }
        ]
      },
      {
        name: '书与纸',
        children: [
          { emoj: "📔", "name": "带装饰封面的笔记本" },
          { emoj: "📕", "name": "合上的书" },
          { emoj: "📖", "name": "打开的书" },
          { emoj: "📗", "name": "绿色封面的书" },
          { emoj: "📘", "name": "蓝色封面的书" },
          { emoj: "📙", "name": "橙色封面的书" },
          { emoj: "📚", "name": "一堆图书" },
          { emoj: "📓", "name": "笔记本" },
          { emoj: "📒", "name": "分类账簿" },
          { emoj: "📃", "name": "卷曲的页面" },
          { emoj: "📜", "name": "古代卷轴" },
          { emoj: "📄", "name": "正面朝上的文件页" },
          { emoj: "📰", "name": "报纸" },
          { emoj: "🗞️", "name": "卷起的报纸" },
          { emoj: "📑", "name": "标记标签（书签标签）" },
          { emoj: "🔖", "name": "书签" },
          { emoj: "🏷️", "name": "标签" },
        ]
      },
      {
        name: '货币',
        children: [
          { emoj: "💰", "name": "钱袋子或一捆钞票" },
          { emoj: "🪙", "name": "硬币" },
          { emoj: "💴", "name": "日元纸币" },
          { emoj: "💵", "name": "美元纸币" },
          { emoj: "💶", "name": "欧元纸币" },
          { emoj: "💷", "name": "英镑纸币" },
          { emoj: "💸", "name": "飞舞的钞票，象征快速花钱或赚钱" },
          { emoj: "💳", "name": "信用卡" },
          { emoj: "🧾", "name": "收据或发票" },
          { emoj: "💹", "name": "上升的图表和日元符号，表示市场增长或盈利" }
        ]
      },
      {
        name: '邮件',
        children: [
          { emoj: "✉", "name": "信封" },
          { emoj: "📧", "name": "电子邮件" },
          { emoj: "📨", "name": "传入的邮件" },
          { emoj: "📩", "name": "带有箭头指向右侧的信封，表示已发送或传出邮件" },
          { emoj: "📤", "name": "发件箱或发出邮件的托盘" },
          { emoj: "📥", "name": "收件箱或收到邮件的托盘" },
          { emoj: "📦", "name": "包裹" },
          { emoj: "📫", "name": "闭合且升起红旗的邮箱，表示可以投递邮件" },
          { emoj: "📪", "name": "闭合且降下红旗的邮箱，表示暂时无法投递邮件" },
          { emoj: "📬", "name": "打开且升起红旗的邮箱，表示可放入邮件" },
          { emoj: "📭", "name": "打开且降下红旗的邮箱，表示已经收取过邮件" },
          { emoj: "📮", "name": "邮箱" },
          { emoj: "🗳️", "name": "带选票的投票箱" },
        ]
      },
      {
        name: '写作',
        children: [
          { emoj: "✏️", "name": "铅笔" },
          { emoj: "✒️", "name": "蘸水笔或黑色笔尖" },
          { emoj: "🖋", "name": "钢笔" },
          { emoj: "🖊", "name": "圆珠笔或一般笔" },
          { emoj: "🖌️", "name": "画笔" },
          { emoj: "🖍️", "name": "蜡笔" },
          { emoj: "📝", "name": "备忘录或便签纸" }
        ]
      },
      {
        name: '办公室',
        children: [
          { emoj: "💼", "name": "公文包" },
          { emoj: "📁", "name": "文件夹" },
          { emoj: "📂", "name": "打开的文件夹" },
          { emoj: "🗂️", "name": "卡片索引分隔线" },
          { emoj: "📅", "name": "日历" },
          { emoj: "📆", "name": "可撕式日历" },
          { emoj: "🗒️", "name": "螺旋记事本" },
          { emoj: "🗓", "name": "螺旋日历" },
          { emoj: "📇", "name": "卡片索引" },
          { emoj: "📈", "name": "上升趋势图表" },
          { emoj: "📉", "name": "下降趋势图表" },
          { emoj: "📊", "name": "条形图或柱状图" },
          { emoj: "📋", "name": "剪贴板" },
          { emoj: "📌", "name": "图钉" },
          { emoj: "📍", "name": "圆形图钉" },
          { emoj: "📎", "name": "回形针" },
          { emoj: "🖇", "name": "链接在一起的回形针" },
          { emoj: "📏", "name": "直尺" },
          { emoj: "📐", "name": "三角尺" },
          { emoj: "✂️", "name": "剪刀" },
          { emoj: "🗃️", "name": "卡片文件盒" },
          { emoj: "🗄️", "name": "文件柜" },
          { emoj: "🗑", "name": "废纸篓" }
        ]
      },
      {
        name: '锁',
        children: [
          { emoj: "🔒", "name": "锁定" },
          { emoj: "🔓", "name": "解锁" },
          { emoj: "🔏", "name": "用笔保护或私密锁定" },
          { emoj: "🔐", "name": "用钥匙锁定的安全锁" },
          { emoj: "🔑", "name": "钥匙" },
          { emoj: "🗝", "name": "老式或神秘的钥匙" }
        ]
      },
      {
        name: '工具',
        children: [
          { emoj: "🔨", "name": "锤子" },
          { emoj: "🪓", "name": "斧头" },
          { emoj: "⛏️", "name": "镐" },
          { emoj: "⛏", "name": "镐" },
          { emoj: "⚒", "name": "锤子与镐组合" },
          { emoj: "🛠", "name": "锤子与扳手组合" },
          { emoj: "🗡", "name": "匕首" },
          { emoj: "⚔", "name": "交叉的剑" },
          { emoj: "💣", "name": "炸弹" },
          { emoj: "🪃", "name": "回旋镖" },
          { emoj: "🏹", "name": "弓箭" },
          { emoj: "🛡", "name": "盾牌" },
          { emoj: "🪚", "name": "木工锯" },
          { emoj: "🔧", "name": "扳手" },
          { emoj: "🪛", "name": "螺丝刀" },
          { emoj: "🔩", "name": "螺母和螺栓" },
          { emoj: "⚙️", "name": "齿轮" },
          { emoj: "⚙", "name": "齿轮" },
          { emoj: "🗜️", "name": "夹钳或压力机" },
          { emoj: "⚖️", "name": "天平秤" },
          { emoj: "🦯", "name": "盲人手杖" },
          { emoj: "🔗", "name": "链接或关联" },
          { emoj: "⛓", "name": "链条" },
          { emoj: "🪝", "name": "鱼钩" }
        ]
      },
      {
        name: '科学',
        children: [
          { emoj: "⚗️", "name": "蒸馏器或化学实验瓶" },
          { emoj: "🧪", "name": "试管" },
          { emoj: "🧫", "name": "培养皿" },
          { emoj: "🧬", "name": "脱氧核糖核酸（DNA）" },
          { emoj: "🔬", "name": "显微镜" },
          { emoj: "🔭", "name": "望远镜" },
          { emoj: "📡", "name": "卫星天线" }
        ]
      },
      {
        name: '医学',
        children: [
          { emoj: "💉", "name": "注射器" },
          { emoj: "🩸", "name": "一滴血" },
          { emoj: "💊", "name": "药丸" },
          { emoj: "🩹", "name": "创可贴或粘性绷带" },
          { emoj: "🩼", "name": "拐杖" },
          { emoj: "🩺", "name": "听诊器" },
          { emoj: "🩻", "name": "X射线照片" }
        ]
      },
      {
        name: '家居用品',
        children: [
          { emoj: "🚪", "name": "门" },
          { emoj: "🛗", "name": "电梯" },
          { emoj: "🪞", "name": "镜子" },
          { emoj: "🪟", "name": "窗户" },
          { emoj: "🛏", "name": "床" },
          { emoj: "🛋️", "name": "沙发和落地灯" },
          { emoj: "🪑", "name": "椅子" },
          { emoj: "🚽", "name": "坐便器" },
          { emoj: "🪠", "name": "马桶搋子" },
          { emoj: "🚿", "name": "淋浴" },
          { emoj: "🛁", "name": "浴缸" },
          { emoj: "🪤", "name": "捕鼠器" },
          { emoj: "🪒", "name": "剃须刀" },
          { emoj: "🧴", "name": "乳液瓶或护肤品容器" },
          { emoj: "🧷", "name": "安全别针" },
          { emoj: "🧹", "name": "扫帚" },
          { emoj: "🧺", "name": "篮子" },
          { emoj: "🧻", "name": "卷纸或厨房纸巾" },
          { emoj: "🪣", "name": "桶" },
          { emoj: "🧼", "name": "肥皂" },
          { emoj: "🫧", "name": "泡沫或洗洁精泡泡" },
          { emoj: "🪥", "name": "牙刷" },
          { emoj: "🧽", "name": "海绵" },
          { emoj: "🧯", "name": "灭火器" },
          { emoj: "🛒", "name": "购物车" }
        ]
      },
      {
        name: '其他物品',
        children: [
          { emoj: "🚬", "name": "香烟" },
          { emoj: "⚰️", "name": "棺材" },
          { emoj: "🪦", "name": "墓碑" },
          { emoj: "⚱️", "name": "骨灰盒" },
          { emoj: "⚱", "name": "骨灰盒" },
          { emoj: "🧿", "name": "邪恶之眼护符或纳扎尔护身符" },
          { emoj: "🪬", "name": "哈姆萨（伊斯兰教吉祥标志）" },
          { emoj: "🗿", "name": "摩艾石像" },
          { emoj: "🪧", "name": "标语牌或广告牌" },
          { emoj: "🪪", "name": "身份证或证件" }
        ]
      }
    ]
  },
  {
    name: '符号的表情符号',
    children: [
      {
        name: '交通标志',
        children: [
          { emoj: "🏧", "name": "自动取款机标志" },
          { emoj: "🚮", "name": "垃圾桶标志，意为丢弃垃圾在此" },
          { emoj: "🚰", "name": "饮用水" },
          { emoj: "♿", "name": "轮椅符号，表示无障碍设施" },
          { emoj: "🚹", "name": "男厕所" },
          { emoj: "🚺", "name": "女厕所" },
          { emoj: "🚻", "name": "通用卫生间或洗手间" },
          { emoj: "🚼", "name": "婴儿室或更换尿布符号" },
          { emoj: "🚾", "name": "洗手间或厕所" },
          { emoj: "🛂", "name": "护照检查或护照控制" },
          { emoj: "🛃", "name": "海关" },
          { emoj: "🛄", "name": "行李提取或行李领取处" },
          { emoj: "🛅", "name": "行李寄存处" }
        ]
      },
      {
        name: '警告',
        children: [
          { emoj: "⚠️", "name": "警告" },
          { emoj: "⚠", "name": "警告" },
          { emoj: "🚸", "name": "儿童过马路，请慢行" },
          { emoj: "⛔", "name": "禁止驶入" },
          { emoj: "🚫", "name": "禁止" },
          { emoj: "🚳", "name": "禁止自行车通行" },
          { emoj: "🚭", "name": "禁止吸烟" },
          { emoj: "🚯", "name": "请勿乱扔垃圾" },
          { emoj: "🚱", "name": "非饮用水" },
          { emoj: "🚷", "name": "行人禁止通行" },
          { emoj: "📵", "name": "禁止使用手机" },
          { emoj: "🔞", "name": "未满18岁禁止进入或观看" },
          { emoj: "☢️", "name": "放射性物质" },
          { emoj: "☢", "name": "放射性物质" },
          { emoj: "☣️", "name": "生物危害" },
          { emoj: "☣", "name": "生物危害" }
        ]
      },
      {
        name: '箭头',
        children: [
          { emoj: "⬆️", "name": "向上箭头" },
          { emoj: "⬆", "name": "向上箭头" },
          { emoj: "↗️", "name": "右上箭头" },
          { emoj: "↗", "name": "右上箭头" },
          { emoj: "➡️", "name": "右箭头" },
          { emoj: "➡", "name": "右箭头" },
          { emoj: "↘️", "name": "右下箭头" },
          { emoj: "↘", "name": "右下箭头" },
          { emoj: "⬇️", "name": "向下箭头" },
          { emoj: "⬇", "name": "向下箭头" },
          { emoj: "↙️", "name": "左下箭头" },
          { emoj: "↙", "name": "左下箭头" },
          { emoj: "⬅️", "name": "左箭头" },
          { emoj: "⬅", "name": "左箭头" },
          { emoj: "↖️", "name": "左上箭头" },
          { emoj: "↖", "name": "左上箭头" },
          { emoj: "↕️", "name": "上下箭头" },
          { emoj: "↕", "name": "上下箭头" },
          { emoj: "↔️", "name": "左右箭头" },
          { emoj: "↔", "name": "左右箭头" },
          { emoj: "↩️", "name": "右箭头向左弯曲" },
          { emoj: "↩", "name": "右箭头向左弯曲" },
          { emoj: "↪️", "name": "左箭头向右弯曲" },
          { emoj: "↪", "name": "左箭头向右弯曲" },
          { emoj: "⤴️", "name": "右箭头向上弯曲" },
          { emoj: "⤴", "name": "右箭头向上弯曲" },
          { emoj: "⤵️", "name": "右箭头向下弯曲" },
          { emoj: "⤵", "name": "右箭头向下弯曲" },
          { emoj: "🔃", "name": "顺时针循环或重新加载箭头" },
          { emoj: "🔄", "name": "逆时针循环箭头或反向旋转按钮" },
          { emoj: "🔙", "name": "返回箭头" },
          { emoj: "🔚", "name": "结束箭头" }
        ]
      },
      {
        name: '宗教',
        children: [
          { emoj: "🛐", "name": "宗教场所" },
          { emoj: "⚛️", "name": "原子符号，代表无神论、科学或理性" },
          { emoj: "⚛", "name": "原子符号" },
          { emoj: "🕉️", "name": "奥姆，印度教或佛教符号，代表宇宙意识" },
          { emoj: "🕉", "name": "奥姆" },
          { emoj: "✡️", "name": "大卫之星，犹太教符号" },
          { emoj: "✡", "name": "大卫之星" },
          { emoj: "☸️", "name": "法轮，佛教符号，代表佛法和觉悟" },
          { emoj: "☸", "name": "法轮" },
          { emoj: "☯️", "name": "阴阳，道教和中国哲学的象征，代表对立统一" },
          { emoj: "☯", "name": "阴阳" },
          { emoj: "✝️", "name": "拉丁十字，基督教尤其是罗马天主教的标志" },
          { emoj: "✝", "name": "拉丁十字" },
          { emoj: "☦️", "name": "东正教十字架，东正教标志，带有耶稣名缩写INRI" },
          { emoj: "☦", "name": "东正教十字架" },
          { emoj: "☪️", "name": "星星和新月，伊斯兰教标志" },
          { emoj: "☪", "name": "星星和新月" },
          { emoj: "☮️", "name": "和平象征" },
          { emoj: "☮", "name": "和平象征" },
          { emoj: "🕎", "name": "烛台，七分支烛台，犹太教的梅诺拉烛台" },
          { emoj: "🔯", "name": "虚线六角星，有时作为魔法或幸运符号" },
          { emoj: "🪯", "name": "似乎是错误引用，无法确定对应于哪个具体符号；若指“kadomatsu”则是一种日本新年装饰物" }
        ]
      },
      {
        name: '十二星座',
        children: [
          { emoj: "♈", "name": "白羊座" },
          { emoj: "♉", "name": "金牛座" },
          { emoj: "♊", "name": "双子座" },
          { emoj: "♋", "name": "巨蟹座" },
          { emoj: "♌", "name": "狮子座" },
          { emoj: "♍", "name": "处女座" },
          { emoj: "♎", "name": "天秤座" },
          { emoj: "♏", "name": "天蝎座" },
          { emoj: "♐", "name": "射手座" },
          { emoj: "♑", "name": "摩羯座" },
          { emoj: "♒", "name": "水瓶座" },
          { emoj: "♓", "name": "双鱼座" },
          { emoj: "⛎", "name": "蛇夫座" }
        ]
      },
      {
        name: '音视频与符号',
        children: [
          { emoj: "🔀", "name": "随机播放曲目按钮" },
          { emoj: "🔁", "name": "重复播放按钮" },
          { emoj: "🔂", "name": "单曲循环播放按钮" },
          { emoj: "▶️", "name": "播放按钮" },
          { emoj: "▶", "name": "播放按钮" },
          { emoj: "⏩", "name": "快进按钮" },
          { emoj: "⏭️", "name": "下一曲目按钮" },
          { emoj: "⏭", "name": "下一曲目按钮" },
          { emoj: "⏯️", "name": "播放/暂停按钮" },
          { emoj: "⏯", "name": "播放/暂停按钮" },
          { emoj: "◀️", "name": "倒退按钮" },
          { emoj: "◀", "name": "倒退按钮" },
          { emoj: "⏪", "name": "快退按钮" },
          { emoj: "⏮️", "name": "上一曲目按钮" },
          { emoj: "⏮", "name": "上一曲目按钮" },
          { emoj: "🔼", "name": "向上按钮" },
          { emoj: "⏫", "name": "快速向上按钮" },
          { emoj: "🔽", "name": "向下按钮" },
          { emoj: "⏬", "name": "快速向下按钮" },
          { emoj: "⏸️", "name": "暂停按钮" },
          { emoj: "⏸", "name": "暂停按钮" },
          { emoj: "⏹️", "name": "停止按钮" },
          { emoj: "⏹", "name": "停止按钮" },
          { emoj: "⏺️", "name": "录音按钮" },
          { emoj: "⏺", "name": "录音按钮" },
          { emoj: "⏏️", "name": "弹出或退出按钮" },
          { emoj: "⏏", "name": "弹出或退出按钮" },
          { emoj: "🎦", "name": "电影院" },
          { emoj: "🔅", "name": "调暗或降低亮度按钮" },
          { emoj: "🔆", "name": "调亮或增加亮度按钮" },
          { emoj: "📶", "name": "信号强度条或无线网络信号强度" },
          { emoj: "🛜", "name": "此emoj可能表示无线通信或传输，但并非标准符号，可能存在误用或理解差异" }
        ]
      },
      {
        name: '性别',
        children: [
          { emoj: "♀", "name": "女性标志" },
          { emoj: "♂️", "name": "男性标志" },
          { emoj: "⚧️", "name": "跨性别符号" },
          { emoj: "⚧", "name": "跨性别符号" }
        ]
      },
      {
        name: '数学',
        children: [
          { emoj: "✖️", "name": "乘号或取消标记" },
          { emoj: "✖", "name": "乘号或取消标记" },
          { emoj: "➕", "name": "加号" },
          { emoj: "➖", "name": "减号" },
          { emoj: "➗", "name": "除号或分割符号" },
          { emoj: "🟰", "name": "重等号，强调等于关系或严格相等" },
          { emoj: "♾️", "name": "无穷符号，代表无限、永恒的概念" },
          { emoj: "♾", "name": "无穷符号" }
        ]
      },
      {
        name: '标点符号',
        children: [
          { emoj: "‼️", "name": "双感叹号，表示强烈惊讶或强调" },
          { emoj: "‼", "name": "双感叹号" },
          { emoj: "⁉️", "name": "感叹号问号，表示惊讶疑问或矛盾情绪" },
          { emoj: "⁉", "name": "感叹号问号" },
          { emoj: "❓", "name": "红色问号，表示疑问或不确定性" },
          { emoj: "❔", "name": "白色问号，通常用于轻色调背景下的疑问表达" },
          { emoj: "❕", "name": "白色感叹号，通常用于轻色调背景下的惊叹表达" },
          { emoj: "❗", "name": "红色感叹号，表示惊叹、警告或引起注意" },
          { emoj: "〰️", "name": "波浪破折号，通常用于表示延续、转折或中断" },
          { emoj: "〰", "name": "波浪破折号" }
        ]
      },
      {
        name: '货币符号',
        children: [
          { emoj: "💱", "name": "货币兑换，表示货币交易、外汇兑换或支付结算" },
          { emoj: "💲", "name": "重美元符号，常用于强调与美元有关的金融话题或财富概念" }
        ]
      },
      {
        name: '其他符号',
        children: [
          { emoj: "⚕️", "name": "医学符号，代表医疗、健康、医生、护士等相关行业或服务" },
          { emoj: "⚕", "name": "医学符号" },
          { emoj: "♻️", "name": "回收符号，代表环保、循环利用或可回收物品" },
          { emoj: "♻", "name": "回收符号" },
          { emoj: "⚜️", "name": "百合花，常用于象征法国或中世纪骑士勋章，也用于装饰或艺术设计" },
          { emoj: "⚜", "name": "百合花" },
          { emoj: "🔱", "name": "三叉戟徽章，代表海神波塞冬的武器，也被用于象征力量、领导力或海洋主题" },
          { emoj: "📛", "name": "名卡，通常表示姓名标签或身份标识" },
          { emoj: "🔰", "name": "初学者的日语符号，表示新手或入门级别" },
          { emoj: "⭕", "name": "空心红色圆圈，常用于表示选择或确认，或者作为一个通用图形元素" },
          { emoj: "✅", "name": "复选标记按钮，表示确认、完成或正确选项" },
          { emoj: "☑️", "name": "带复选标记的复选框，用于表单或问卷中的选择项" },
          { emoj: "☑", "name": "带复选标记的复选框" },
          { emoj: "✔️", "name": "复选标记，表示同意、确认或正确" },
          { emoj: "✔", "name": "复选标记" },
          { emoj: "❌", "name": "十字标记，表示取消、错误或否决" },
          { emoj: "❎", "name": "十字标记按钮，表示拒绝或关闭操作" },
          { emoj: "➰", "name": "卷曲环，一种图形符号，可以表示循环、纠结或复杂关系" },
          { emoj: "➿", "name": "双卷曲环，常用于表示无限循环或反复执行" },
          { emoj: "〽️", "name": "零件交替标记，源自日本，用于表示部分交替、阶段变化或部件更换" },
          { emoj: "〽", "name": "零件交替标记" },
          { emoj: "✳️", "name": "八辐星号" },
          { emoj: "✳", "name": "八角星，用于装饰或强调" },
          { emoj: "✴️", "name": "八角星" },
          { emoj: "❇️", "name": "火花，象征闪耀、灵感或兴奋" },
          { emoj: "❇", "name": "火花" },
          { emoj: "©️", "name": "版权，表示作品受版权保护" },
          { emoj: "©", "name": "版权" },
          { emoj: "®️", "name": "注册商标符号，表示已注册的商标" },
          { emoj: "®", "name": "注册商标" },
          { emoj: "™️", "name": "商标，表示商品或服务的商标，不一定经过正式注册" },
          { emoj: "™", "name": "商标" }
        ]
      },
      {
        name: '键帽',
        children: [
          { emoj: "#️⃣", "name": "数字井号键帽，通常表示标签、主题或键盘上的#键" },
          { emoj: "*️⃣", "name": "星号键帽，通常用于键盘上的*键，或代表通配符" },
          { emoj: "0️⃣", "name": "数字0键帽" },
          { emoj: "1️⃣", "name": "数字1键帽" },
          { emoj: "2️⃣", "name": "数字2键帽" },
          { emoj: "3️⃣", "name": "数字3键帽" },
          { emoj: "4️⃣", "name": "数字4键帽" },
          { emoj: "5️⃣", "name": "数字5键帽" },
          { emoj: "6️⃣", "name": "数字6键帽" },
          { emoj: "7️⃣", "name": "数字7键帽" },
          { emoj: "8️⃣", "name": "数字8键帽" },
          { emoj: "9️⃣", "name": "数字9键帽" },
          { emoj: "🔟", "name": "数字10键帽" }
        ]
      },
      {
        name: '字母数字',
        children: [
          { emoj: "🔠", "name": "输入拉丁大写字母" },
          { emoj: "🔡", "name": "输入拉丁小写字母" },
          { emoj: "🔢", "name": "输入数字" },
          { emoj: "🔣", "name": "输入符号" },
          { emoj: "🔤", "name": "输入拉丁字母" },
          { emoj: "🅰️", "name": "A按钮，用于表示血型A或一般意义上的A" },
          { emoj: "🅰", "name": "A按钮（血型）" },
          { emoj: "🆎", "name": "AB按钮，用于表示血型AB" },
          { emoj: "🅱️", "name": "B按钮，用于表示血型B或一般意义上的B" },
          { emoj: "🅱", "name": "B按钮（血型）" },
          { emoj: "🆑", "name": "CL按钮，一般表示清除或结束某项操作" },
          { emoj: "🆒", "name": "酷按钮，表示很酷、很棒或某种流行文化" },
          { emoj: "🆓", "name": "免费按钮，表示免费或无需付费" },
          { emoj: "ℹ️", "name": "信息，表示提供信息或获取帮助" },
          { emoj: "ℹ", "name": "信息" },
          { emoj: "🆔", "name": "身份识别按钮，常用于表示ID、身份证件或身份证明" },
          { emoj: "Ⓜ️", "name": "圆圈中的M，多用于品牌或logo设计" },
          { emoj: "Ⓜ", "name": "圆圈中的M" },
          { emoj: "🆕", "name": "新按钮，表示新事物、新品或更新" },
          { emoj: "🆖", "name": "不合格按钮，表示不可接受、禁止或不合格" },
          { emoj: "🅾️", "name": "O型按钮，用于表示血型O" },
          { emoj: "🅾", "name": "O型按钮（血型）" },
          { emoj: "🆗", "name": "确定按钮，表示一切正常、批准或同意" },
          { emoj: "🅿️", "name": "P按钮，常用于表示停车场" },
          { emoj: "🅿", "name": "P按钮" },
          { emoj: "🆘", "name": "求救按钮，表示紧急求助或SOS信号" },
          { emoj: "🆙", "name": "向上！按钮，表示上升、积极或提升关注度" },
          { emoj: "🆚", "name": "VS按钮，表示对比、对抗或对阵，比如比赛中的对决" },
          { emoj: "🈁", "name": "日语‘此处’按钮，表示这里、这个地方" },
          { emoj: "🈂️", "name": "日语‘服务费’按钮，表示附加费用或小费" },
          { emoj: "🈂", "name": "日语‘服务费’按钮" },
          { emoj: "🈷️", "name": "日语‘每月金额’按钮，表示按月计算的费用或周期" }
        ]
      },
      {
        name: '几何形状',
        children: [
          { emoj: "🔴", "name": "红色圆圈" },
          { emoj: "🟠", "name": "橙色圆圈" },
          { emoj: "🟡", "name": "黄色圆圈" },
          { emoj: "🟢", "name": "绿色圆圈" },
          { emoj: "🔵", "name": "蓝色圆圈" },
          { emoj: "🟣", "name": "紫色圆圈" },
          { emoj: "🟤", "name": "棕色圆圈" },
          { emoj: "⚫", "name": "黑色圆圈" },
          { emoj: "⚪", "name": "白色圆圈" },
          { emoj: "🟥", "name": "红色方格" },
          { emoj: "🟧", "name": "橙色方块" },
          { emoj: "🟨", "name": "黄色方块" },
          { emoj: "🟩", "name": "绿色正方形" },
          { emoj: "🟦", "name": "蓝色方块" },
          { emoj: "🟪", "name": "紫色方块" },
          { emoj: "🟫", "name": "棕色方块" },
          { emoj: "⬛", "name": "黑色大方块" },
          { emoj: "⬜", "name": "白色大正方形" },
          { emoj: "◼️", "name": "黑色中方形" },
          { emoj: "◼", "name": "黑色中方形" },
          { emoj: "◻️", "name": "白色中方形" },
          { emoj: "◻", "name": "白色中方形" },
          { emoj: "◾", "name": "黑色中小方块" },
          { emoj: "◽", "name": "白色中小正方形" },
          { emoj: "▪️", "name": "黑色小方块" },
          { emoj: "▪", "name": "黑色小方块" },
          { emoj: "▫️", "name": "白色小方块" },
          { emoj: "▫", "name": "白色小方块" },
          { emoj: "🔶", "name": "大橙色钻石" },
          { emoj: "🔷", "name": "大蓝色钻石" },
          { emoj: "🔸", "name": "小橙色钻石" },
          { emoj: "🔹", "name": "小蓝色钻石" }
        ]
      }
    ]
  },
  {
    name: '旗帜的表情符号',
    children: [
      {
        name: '国旗',
        children: [
          { emoj: "🏁", "name": "方格旗，常用于赛车比赛终点或其他竞赛活动" },
          { emoj: "🚩", "name": "三角旗，指路标志或用于指示地点" },
          { emoj: "🎌", "name": "交叉旗帜，代表日本，也可表示国际合作或庆祝活动" },
          { emoj: "🏴", "name": "黑旗，可以代表无政府主义或历史上船舰投降的信号" },
          { emoj: "🏳", "name": "白旗" },
          { emoj: "🏳‍🌈", "name": "彩虹旗" },
          { emoj: "🏳‍⚧️", "name": "跨性别旗帜" },
          { emoj: "🏴‍☠", "name": "海盗旗" }
        ]
      },
      {
        name: '国家与旗帜',
        children: [
          { emoj: "🇦🇨", "name": "旗: 阿森松岛" },
          { emoj: "🇦🇩", "name": "旗: 安道尔" },
          { emoj: "🇦🇪", "name": "旗: 阿拉伯联合酋长国" },
          { emoj: "🇦🇫", "name": "旗: 阿富汗" },
          { emoj: "🇦🇬", "name": "旗: 安提瓜和巴布达" },
          { emoj: "🇦🇮", "name": "旗: 安圭拉" },
          { emoj: "🇦🇱", "name": "旗: 阿尔巴尼亚" },
          { emoj: "🇦🇲", "name": "旗: 亚美尼亚" },
          { emoj: "🇦🇴", "name": "旗: 安哥拉" },
          { emoj: "🇦🇶", "name": "旗: 南极洲" },
          { emoj: "🇦🇷", "name": "旗: 阿根廷" },
          { emoj: "🇦🇸", "name": "旗: 美属萨摩亚" },
          { emoj: "🇦🇹", "name": "旗: 奥地利" },
          { emoj: "🇦🇺", "name": "旗: 澳大利亚" },
          { emoj: "🇦🇼", "name": "旗: 阿鲁巴" },
          { emoj: "🇦🇽", "name": "旗: 奥兰群岛" },
          { emoj: "🇦🇿", "name": "旗: 阿塞拜疆" },
          { emoj: "🇧🇦", "name": "旗: 波斯尼亚和黑塞哥维那" },
          { emoj: "🇧🇧", "name": "旗: 巴巴多斯" },
          { emoj: "🇧🇩", "name": "旗: 孟加拉国" },
          { emoj: "🇧🇪", "name": "旗: 比利时" },
          { emoj: "🇧🇫", "name": "旗: 布基纳法索" },
          { emoj: "🇧🇬", "name": "旗: 保加利亚" },
          { emoj: "🇧🇭", "name": "旗: 巴林" },
          { emoj: "🇧🇮", "name": "旗: 布隆迪" },
          { emoj: "🇧🇯", "name": "旗: 贝宁" },
          { emoj: "🇧🇱", "name": "旗: 圣巴泰勒米" },
          { emoj: "🇧🇲", "name": "旗: 百慕大" },
          { emoj: "🇧🇳", "name": "旗: 文莱" },
          { emoj: "🇧🇴", "name": "旗: 玻利维亚" },
          { emoj: "🇧🇶", "name": "旗: 荷属加勒比区" },
          { emoj: "🇧🇷", "name": "旗: 巴西" },
          { emoj: "🇧🇸", "name": "旗: 巴哈马" },
          { emoj: "🇧🇹", "name": "旗: 不丹" },
          { emoj: "🇧🇻", "name": "旗: 布韦岛" },
          { emoj: "🇧🇼", "name": "旗: 博茨瓦纳" },
          { emoj: "🇧🇾", "name": "旗: 白俄罗斯" },
          { emoj: "🇧🇿", "name": "旗: 伯利兹" },
          { emoj: "🇨🇦", "name": "旗: 加拿大" },
          { emoj: "🇨🇨", "name": "旗: 科科斯（基林）群岛" },
          { emoj: "🇨🇩", "name": "旗: 刚果（金）" },
          { emoj: "🇨🇫", "name": "旗: 中非共和国" },
          { emoj: "🇨🇬", "name": "旗: 刚果（布）" },
          { emoj: "🇨🇭", "name": "旗: 瑞士" },
          { emoj: "🇨🇮", "name": "旗: 科特迪瓦" },
          { emoj: "🇨🇰", "name": "旗: 库克群岛" },
          { emoj: "🇨🇱", "name": "旗: 智利" },
          { emoj: "🇨🇲", "name": "旗: 喀麦隆" },
          { emoj: "🇨🇳", "name": "旗: 中国" },
          { emoj: "🇨🇴", "name": "旗: 哥伦比亚" },
          { emoj: "🇨🇵", "name": "旗: 克利珀顿岛" },
          { emoj: "🇨🇷", "name": "旗: 哥斯达黎加" },
          { emoj: "🇨🇺", "name": "旗: 古巴" },
          { emoj: "🇨🇻", "name": "旗: 佛得角" },
          { emoj: "🇨🇼", "name": "旗: 库拉索" },
          { emoj: "🇨🇽", "name": "旗: 圣诞岛" },
          { emoj: "🇨🇾", "name": "旗: 塞浦路斯" },
          { emoj: "🇨🇿", "name": "旗: 捷克" },
          { emoj: "🇩🇪", "name": "旗: 德国" },
          { emoj: "🇩🇬", "name": "旗: 迪戈加西亚岛" },
          { emoj: "🇩🇯", "name": "旗: 吉布提" },
          { emoj: "🇩🇰", "name": "旗: 丹麦" },
          { emoj: "🇩🇲", "name": "旗: 多米尼克" },
          { emoj: "🇩🇴", "name": "旗: 多米尼加共和国" },
          { emoj: "🇩🇿", "name": "旗: 阿尔及利亚" },
          { emoj: "🇪🇦", "name": "旗: 休达及梅利利亚" },
          { emoj: "🇪🇨", "name": "旗: 厄瓜多尔" },
          { emoj: "🇪🇪", "name": "旗: 爱沙尼亚" },
          { emoj: "🇪🇬", "name": "旗: 埃及" },
          { emoj: "🇪🇭", "name": "旗: 西撒哈拉" },
          { emoj: "🇪🇷", "name": "旗: 厄立特里亚" },
          { emoj: "🇪🇸", "name": "旗: 西班牙" },
          { emoj: "🇪🇹", "name": "旗: 埃塞俄比亚" },
          { emoj: "🇪🇺", "name": "旗: 欧盟" },
          { emoj: "🇫🇮", "name": "旗: 芬兰" },
          { emoj: "🇫🇯", "name": "旗: 斐济" },
          { emoj: "🇫🇰", "name": "旗: 福克兰群岛" },
          { emoj: "🇫🇲", "name": "旗: 密克罗尼西亚" },
          { emoj: "🇫🇴", "name": "旗: 法罗群岛" },
          { emoj: "🇫🇷", "name": "旗: 法国" },
          { emoj: "🇬🇦", "name": "旗: 加蓬" },
          { emoj: "🇬🇧", "name": "旗: 英国" },
          { emoj: "🇬🇩", "name": "旗: 格林纳达" },
          { emoj: "🇬🇪", "name": "旗: 格鲁吉亚" },
          { emoj: "🇬🇫", "name": "旗: 法属圭亚那" },
          { emoj: "🇬🇬", "name": "旗: 根西岛" },
          { emoj: "🇬🇭", "name": "旗: 加纳" },
          { emoj: "🇬🇮", "name": "旗: 直布罗陀" },
          { emoj: "🇬🇱", "name": "旗: 格陵兰" },
          { emoj: "🇬🇲", "name": "旗: 冈比亚" },
          { emoj: "🇬🇳", "name": "旗: 几内亚" },
          { emoj: "🇬🇵", "name": "旗: 瓜德罗普" },
          { emoj: "🇬🇶", "name": "旗: 赤道几内亚" },
          { emoj: "🇬🇷", "name": "旗: 希腊" },
          { emoj: "🇬🇸", "name": "旗: 南乔治亚和南桑威奇群岛" },
          { emoj: "🇬🇹", "name": "旗: 危地马拉" },
          { emoj: "🇬🇺", "name": "旗: 关岛" },
          { emoj: "🇬🇼", "name": "旗: 几内亚比绍" },
          { emoj: "🇬🇾", "name": "旗: 圭亚那" },
          { emoj: "🇭🇰", "name": "旗: 中国香港特别行政区" },
          { emoj: "🇭🇲", "name": "旗: 赫德岛和麦克唐纳群岛" },
          { emoj: "🇭🇳", "name": "旗: 洪都拉斯" },
          { emoj: "🇭🇷", "name": "旗: 克罗地亚" },
          { emoj: "🇭🇹", "name": "旗: 海地" },
          { emoj: "🇭🇺", "name": "旗: 匈牙利" },
          { emoj: "🇮🇨", "name": "旗: 加纳利群岛" },
          { emoj: "🇮🇩", "name": "旗: 印度尼西亚" },
          { emoj: "🇮🇪", "name": "旗: 爱尔兰" },
          { emoj: "🇮🇱", "name": "旗: 以色列" },
          { emoj: "🇮🇲", "name": "旗: 马恩岛" },
          { emoj: "🇮🇳", "name": "旗: 印度" },
          { emoj: "🇮🇴", "name": "旗: 英属印度洋领地" },
          { emoj: "🇮🇶", "name": "旗: 伊拉克" },
          { emoj: "🇮🇷", "name": "旗: 伊朗" },
          { emoj: "🇮🇸", "name": "旗: 冰岛" },
          { emoj: "🇮🇹", "name": "旗: 意大利" },
          { emoj: "🇯🇪", "name": "旗: 泽西岛" },
          { emoj: "🇯🇲", "name": "旗: 牙买加" },
          { emoj: "🇯🇴", "name": "旗: 约旦" },
          { emoj: "🇯🇵", "name": "旗: 日本" },
          { emoj: "🇰🇪", "name": "旗: 肯尼亚" },
          { emoj: "🇰🇬", "name": "旗: 吉尔吉斯斯坦" },
          { emoj: "🇰🇭", "name": "旗: 柬埔寨" },
          { emoj: "🇰🇮", "name": "旗: 基里巴斯" },
          { emoj: "🇰🇲", "name": "旗: 科摩罗" },
          { emoj: "🇰🇳", "name": "旗: 圣基茨和尼维斯" },
          { emoj: "🇰🇵", "name": "旗: 朝鲜" },
          { emoj: "🇰🇷", "name": "旗: 韩国" },
          { emoj: "🇰🇼", "name": "旗: 科威特" },
          { emoj: "🇰🇾", "name": "旗: 开曼群岛" },
          { emoj: "🇰🇿", "name": "旗: 哈萨克斯坦" },
          { emoj: "🇱🇦", "name": "旗: 老挝" },
          { emoj: "🇱🇧", "name": "旗: 黎巴嫩" },
          { emoj: "🇱🇨", "name": "旗: 圣卢西亚" },
          { emoj: "🇱🇮", "name": "旗: 列支敦士登" },
          { emoj: "🇱🇰", "name": "旗: 斯里兰卡" },
          { emoj: "🇱🇷", "name": "旗: 利比里亚" },
          { emoj: "🇱🇸", "name": "旗: 莱索托" },
          { emoj: "🇱🇹", "name": "旗: 立陶宛" },
          { emoj: "🇱🇺", "name": "旗: 卢森堡" },
          { emoj: "🇱🇻", "name": "旗: 拉脱维亚" },
          { emoj: "🇱🇾", "name": "旗: 利比亚" },
          { emoj: "🇲🇦", "name": "旗: 摩洛哥" },
          { emoj: "🇲🇨", "name": "旗: 摩纳哥" },
          { emoj: "🇲🇩", "name": "旗: 摩尔多瓦" },
          { emoj: "🇲🇪", "name": "旗: 黑山" },
          { emoj: "🇲🇫", "name": "旗: 法属圣马丁" },
          { emoj: "🇲🇬", "name": "旗: 马达加斯加" },
          { emoj: "🇲🇭", "name": "旗: 马绍尔群岛" },
          { emoj: "🇲🇰", "name": "旗: 北马其顿" },
          { emoj: "🇲🇱", "name": "旗: 马里" },
          { emoj: "🇲🇲", "name": "旗: 缅甸" },
          { emoj: "🇲🇳", "name": "旗: 蒙古" },
          { emoj: "🇲🇴", "name": "旗: 中国澳门特别行政区" },
          { emoj: "🇲🇵", "name": "旗: 北马里亚纳群岛" },
          { emoj: "🇲🇶", "name": "旗: 马提尼克" },
          { emoj: "🇲🇷", "name": "旗: 毛里塔尼亚" },
          { emoj: "🇲🇸", "name": "旗: 蒙特塞拉特" },
          { emoj: "🇲🇹", "name": "旗: 马耳他" },
          { emoj: "🇲🇺", "name": "旗: 毛里求斯" },
          { emoj: "🇲🇻", "name": "旗: 马尔代夫" },
          { emoj: "🇲🇼", "name": "旗: 马拉维" },
          { emoj: "🇲🇽", "name": "旗: 墨西哥" },
          { emoj: "🇲🇾", "name": "旗: 马来西亚" },
          { emoj: "🇲🇿", "name": "旗: 莫桑比克" },
          { emoj: "🇳🇦", "name": "旗: 纳米比亚" },
          { emoj: "🇳🇨", "name": "旗: 新喀里多尼亚" },
          { emoj: "🇳🇪", "name": "旗: 尼日尔" },
          { emoj: "🇳🇫", "name": "旗: 诺福克岛" },
          { emoj: "🇳🇬", "name": "旗: 尼日利亚" },
          { emoj: "🇳🇮", "name": "旗: 尼加拉瓜" },
          { emoj: "🇳🇱", "name": "旗: 荷兰" },
          { emoj: "🇳🇴", "name": "旗: 挪威" },
          { emoj: "🇳🇵", "name": "旗: 尼泊尔" },
          { emoj: "🇳🇷", "name": "旗: 瑙鲁" },
          { emoj: "🇳🇺", "name": "旗: 纽埃" },
          { emoj: "🇳🇿", "name": "旗: 新西兰" },
          { emoj: "🇴🇲", "name": "旗: 阿曼" },
          { emoj: "🇵🇦", "name": "旗: 巴拿马" },
          { emoj: "🇵🇪", "name": "旗: 秘鲁" },
          { emoj: "🇵🇫", "name": "旗: 法属波利尼西亚" },
          { emoj: "🇵🇬", "name": "旗: 巴布亚新几内亚" },
          { emoj: "🇵🇭", "name": "旗: 菲律宾" },
          { emoj: "🇵🇰", "name": "旗: 巴基斯坦" },
          { emoj: "🇵🇱", "name": "旗: 波兰" },
          { emoj: "🇵🇲", "name": "旗: 圣皮埃尔和密克隆群岛" },
          { emoj: "🇵🇳", "name": "旗: 皮特凯恩群岛" },
          { emoj: "🇵🇷", "name": "旗: 波多黎各" },
          { emoj: "🇵🇸", "name": "旗: 巴勒斯坦领土" },
          { emoj: "🇵🇹", "name": "旗: 葡萄牙" },
          { emoj: "🇵🇼", "name": "旗: 帕劳" },
          { emoj: "🇵🇾", "name": "旗: 巴拉圭" },
          { emoj: "🇶🇦", "name": "旗: 卡塔尔" },
          { emoj: "🇷🇪", "name": "旗: 留尼汪" },
          { emoj: "🇷🇴", "name": "旗: 罗马尼亚" },
          { emoj: "🇷🇸", "name": "旗: 塞尔维亚" },
          { emoj: "🇷🇺", "name": "旗: 俄罗斯" },
          { emoj: "🇷🇼", "name": "旗: 卢旺达" },
          { emoj: "🇸🇦", "name": "旗: 沙特阿拉伯" },
          { emoj: "🇸🇧", "name": "旗: 所罗门群岛" },
          { emoj: "🇸🇨", "name": "旗: 塞舌尔" },
          { emoj: "🇸🇩", "name": "旗: 苏丹" },
          { emoj: "🇸🇪", "name": "旗: 瑞典" },
          { emoj: "🇸🇬", "name": "旗: 新加坡" },
          { emoj: "🇸🇭", "name": "旗: 圣赫勒拿" },
          { emoj: "🇸🇮", "name": "旗: 斯洛文尼亚" },
          { emoj: "🇸🇯", "name": "旗: 斯瓦尔巴和扬马延" },
          { emoj: "🇸🇰", "name": "旗: 斯洛伐克" },
          { emoj: "🇸🇱", "name": "旗: 塞拉利昂" },
          { emoj: "🇸🇲", "name": "旗: 圣马力诺" },
          { emoj: "🇸🇳", "name": "旗: 塞内加尔" },
          { emoj: "🇸🇴", "name": "旗: 索马里" },
          { emoj: "🇸🇷", "name": "旗: 苏里南" },
          { emoj: "🇸🇸", "name": "旗: 南苏丹" },
          { emoj: "🇸🇹", "name": "旗: 圣多美和普林西比" },
          { emoj: "🇸🇻", "name": "旗: 萨尔瓦多" },
          { emoj: "🇸🇽", "name": "旗: 荷属圣马丁" },
          { emoj: "🇸🇾", "name": "旗: 叙利亚" },
          { emoj: "🇸🇿", "name": "旗: 斯威士兰" },
          { emoj: "🇹🇦", "name": "旗: 特里斯坦-达库尼亚群岛" },
          { emoj: "🇹🇨", "name": "旗: 特克斯和凯科斯群岛" },
          { emoj: "🇹🇩", "name": "旗: 乍得" },
          { emoj: "🇹🇫", "name": "旗: 法属南部领地" },
          { emoj: "🇹🇬", "name": "旗: 多哥" },
          { emoj: "🇹🇭", "name": "旗: 泰国" },
          { emoj: "🇹🇯", "name": "旗: 塔吉克斯坦" },
          { emoj: "🇹🇰", "name": "旗: 托克劳" },
          { emoj: "🇹🇱", "name": "旗: 东帝汶" },
          { emoj: "🇹🇲", "name": "旗: 土库曼斯坦" },
          { emoj: "🇹🇳", "name": "旗: 突尼斯" },
          { emoj: "🇹🇴", "name": "旗: 汤加" },
          { emoj: "🇹🇷", "name": "旗: 土耳其" },
          { emoj: "🇹🇹", "name": "旗: 特立尼达和多巴哥" },
          { emoj: "🇹🇻", "name": "旗: 图瓦卢" },
          { emoj: "🇹🇿", "name": "旗: 坦桑尼亚" },
          { emoj: "🇺🇦", "name": "旗: 乌克兰" },
          { emoj: "🇺🇬", "name": "旗: 乌干达" },
          { emoj: "🇺🇲", "name": "旗: 美国本土外小岛屿" },
          { emoj: "🇺🇳", "name": "旗: 联合国" },
          { emoj: "🇺🇸", "name": "旗: 美国" },
          { emoj: "🇺🇾", "name": "旗: 乌拉圭" },
          { emoj: "🇺🇿", "name": "旗: 乌兹别克斯坦" },
          { emoj: "🇻🇦", "name": "旗: 梵蒂冈" },
          { emoj: "🇻🇨", "name": "旗: 圣文森特和格林纳丁斯" },
          { emoj: "🇻🇪", "name": "旗: 委内瑞拉" },
          { emoj: "🇻🇬", "name": "旗: 英属维尔京群岛" },
          { emoj: "🇻🇮", "name": "旗: 美属维尔京群岛" },
          { emoj: "🇻🇳", "name": "旗: 越南" },
          { emoj: "🇻🇺", "name": "旗: 瓦努阿图" },
          { emoj: "🇼🇫", "name": "旗: 瓦利斯和富图纳" },
          { emoj: "🇼🇸", "name": "旗: 萨摩亚" },
          { emoj: "🇽🇰", "name": "旗: 科索沃" },
          { emoj: "🇾🇪", "name": "旗: 也门" },
          { emoj: "🇾🇹", "name": "旗: 马约特" },
          { emoj: "🇿🇦", "name": "旗: 南非" },
          { emoj: "🇿🇲", "name": "旗: 赞比亚" },
          { emoj: "🇿🇼", "name": "旗: 津巴布韦" }
        ]
      },
      {
        name: '特殊地区旗帜',
        children: [
          { emoj: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: '旗: 英格兰' },
          { emoj: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: '旗: 苏格兰' },
          { emoj: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: '旗: 威尔士' },
        ]
      }
    ]
  }
]
